language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      env: TOX_ENV=static-font-compiles
      install: pip install --upgrade fontmake
      script: 
        - fontmake -g source/GoogleSans-Text/GoogleSansText-Beta.glyphs --interpolate -o ttf
        - fontmake -g source/GoogleSans-Text/GoogleSansText-Italic-Beta.glyphs --interpolate -o ttf
    - python: 3.7
      dist: xenial
      env: TOX_ENV=variable-font-compiles
      install: pip install --upgrade fontmake
      script: 
        - fontmake -g source/GoogleSans-Text/GoogleSansText-Beta.glyphs -o variable
        - fontmake -g source/GoogleSans-Text/GoogleSansText-Italic-Beta.glyphs -o variable

notifications:
  email: false