familyName: Google Sans

sources:
  - GoogleSans.designspace
  - GoogleSans-Italic.designspace

recipe:
  ../fonts/.intermediate/GoogleSans[GRAD,opsz,wght].ttf:
    - source: GoogleSans.designspace
    - operation: buildVariable
      args: --no-auto-use-my-metrics
    - operation: fix
      args: --skip-fvar-instances
    - operation: hbsubset
  ../fonts/.intermediate/GoogleSans-Italic[GRAD,opsz,wght].ttf:
    - source: GoogleSans-Italic.designspace
    - operation: buildVariable
      args: --no-auto-use-my-metrics
    - operation: fix
      args: --skip-fvar-instances
    - operation: hbsubset
