sources:
  - GoogleSans.designspace
  - GoogleSans-Italic.designspace

familyName: Google Sans

buildVariable: true
# XXX: to be enabled once its compatible with fontc. For now, we will slice them
# ourselves
buildStatic: false
buildOTF: false
buildWebfont: false

extraFontmakeArgs: --no-auto-use-my-metrics
