[input]
script = "arab"
direction = "ltr"
text = [
    "۝٧",
    "۝۵",
    "۝7",
    "۝٠١",
    "۝۲۲",
    "۝77",
    "۝١٠٣",
    "۝۶۵۵",
    "۝335",
    "۝١ۜ",
    "۝١٢ۜ",
    "۝١٢٣ۜ",
    "࣢٩",
    "࣢۵",
    "࣢6",
    "࣢٢٩",
    "࣢۷۵",
    "࣢02",
    "࣢٨٨٩",
    "࣢۷۵۴",
    "࣢394",
    "؁٨",
    "؁۲",
    "؁2",
    "؁٣٠",
    "؁۷۴",
    "؁12",
    "؁٥٠٤",
    "؁۶۶۵",
    "؁588",
    "؁٩٨٧٦",
    "؁۶۵۶۲",
    "؁6718",
    "؄٤",
    "؄۶",
    "؄7",
    "؄٦٩",
    "؄۴۵",
    "؄71",
    "؄٢٢٧",
    "؄۴۲۴",
    "؄766",
    "؄٦٩٤٦",
    "؄۶۴۴۶",
    "؄5159",
    "؃١",
    "؃۲",
    "؃1",
    "؃٩٧",
    "؃۲۵",
    "؃24",
    "؃٠٥٨",
    "؃۵۵۲",
    "؃066",
    "؀٢",
    "؀۵",
    "؀9",
    "؀٧١",
    "؀۶۶",
    "؀40",
    "؀٢٤٨",
    "؀۷۵۲",
    "؀914",
    "؂١",
    "؂۲",
    "؂3",
    "؂٠٦",
    "؂۴۴",
    "؂11",
    "࢑٨",
    "࢑۲",
    "࢑3",
    "࢑٦٨",
    "࢑۲۶",
    "࢑73",
    "࢑٧٣٢",
    "࢑۷۶۶",
    "࢑297",
    "࢐٠",
    "࢐۲",
    "࢐6",
    "࢐٣٥",
    "࢐۷۲",
    "࢐07",
    "࢐٣٥٥",
    "࢐۵۶۴",
    "࢐826",
]
