[meta]
build_commit = "55336dd03493f41ff2427f970568120c8bcfdcd1"

[input.features]
calt = true

[input]
text = [
    "ա-մ", # hyphen used between armenian lowercase – shifts down
    "Ա-Մ", # hypohen used between armenian uppercase – no shift
    "ա֊մ", # hyphen-arm used between armenian lowercase – shifts down
    "Ա֊Մ" # hyphen-arm used between armenian uppercase – no shift
]
