[meta]
build_commit = ""

[input.features]
calt = true

[input]
text = [
    "x; ե;",
    "ա-ր a-p",
    "ե+ւ=և",
    "Ո՞ն Ը՞ն Օ՞ն Ե՞ն Է՞ն Ւ՞ն Ա՞ն",
    "զոզիզյ",
    "ղողիղյ",
    "վովիվյ",
    "լոլիլյ",
    "զջյ"
]
