[meta]
build_commit = ""

[input.features]
ccmp = true

[input]
text = [
    "Ո՞ո՞ Ը՞ը՞ Օ՞օ՞ Ե՞ե՞ Է՞է՞ Ւ՞ւ՞ Ա՞ա՞ Ի՞ի՞ և՞",
    "Ո՜ո՜ Ը՜ը՜ Օ՜օ՜ Ե՜ե՜ Է՜է՜ Ւ՜ւ՜ Ա՜ա՜ Ի՜ի՜ և՜",
    "Ո՛ո՛ Ը՛ը՛ Օ՛օ՛ Ե՛ե՛ Է՛է՛ Ւ՛ւ՛ Ա՛ա՛ Ի՛ի՛ և՛",
    "ﬔ՞ ﬔ՜ ﬔ՛",
    "ﬕ՞ ﬕ՜ ﬕ՛"
]
