[meta]
build_commit = "63559902ed6174bf979b08fde7b6ddcec9bd9eac"

[input.features]
c2sc = true

[input]
text = [
    "GS ĢȘ",
    "ԵԳԶՋԷԾ",
    "\u002c; ՚Ի Ե։ Ս՝",
    "Ո՞ Ը՞ Օ՞ Ե՞ Է՞ Ւ՞ Ա՞ Ի՞",
    "Ո՜ Ը՜ Օ՜ Ե՜ Է՜ Ւ՜ Ա՜ Ի՜",
    "Ո՛ Ը՛ Օ՛ Ե՛ Է՛ Ւ՛ Ա՛ Ի՛"
]
