[meta]
build_commit = ""

[input.features]
smcp = true

[input]
text = [
    "g եգզջծէ",
    "՚ի ե։ ս՝",
    "ո՞ ը՞ օ՞ ե՞ է՞ ւ՞ ա՞ ի՞ և՞",
    "ո՜ ը՜ օ՜ ե՜ է՜ ւ՜ ա՜ ի՜ և՜",
    "ո՛ ը՛ օ՛ ե՛ է՛ ւ՛ ա՛ ի՛ և՛",
    "ﬔ՞ն ﬔ՜ն ﬔ՛ն",
    "ﬕ՞ն ﬕ՜ն ﬕ՛ն"
]
script = "armn"
language = "hy"
