[meta]
build_commit  = ""

[input.features]
half = true
cjct = true
pres = true

[input]
script = "bng2"
language = "dflt"
comparison_mode = "full"
text = [
	"ট্রে ট্টে ল্রে শ্রে ষ্টে", # For combinations with too little space
	"ক্মে ব্দে জ্ঝে ল্কে ল্তে", # For combinations with too much space
]
