[meta]
build_commit  = "b82064346c297d12cb3a2c6fa3674cf516f9e89d"

[input.features]
init = true

[input]
script = "bng2"
language = "dflt"
comparison_mode = "full"
text = [
	"ককে কে", # Initial eMatra
	"ককৈ কৈ", # Initial aiMatra
]