[meta]
build_commit  = "b82064346c297d12cb3a2c6fa3674cf516f9e89d"

[input.features]
half = true
cjct = true
pres = true
blws = true

[input]
script = "beng"
language = "dflt"
comparison_mode = "full"
text = [
	"গু রু শু হু জ্রু প্তু ভ্রু ল্গু গ্রু ত্রু থ্রু দ্রু ধ্রু ন্তু ন্দ্রু প্তু প্রু ব্রু ম্তু ম্রু শ্রু স্তু স্রু স্লু হ্যু", # uMatra ligatures
	"রূ জ্রূ ব্রূ গ্রূ ত্রূ থ্রূ দ্রূ ধ্রূ ন্দ্রূ প্রূ ব্রূ ম্রূ শ্রূ স্রূ স্লূ", # uuMatra ligatures
]