[meta]
build_commit  = "b82064346c297d12cb3a2c6fa3674cf516f9e89d"

[input.features]
rphf = true
half = true
cjct = true
pres = true
blwm = true

[input]
script = "bng2"
language = "dflt"
comparison_mode = "full"
text = [
	"র্টিঁ র্ক্টিঁ র্ট্বিঁ র্ট্রিঁ র্ট্মিঁ র্ট্ট্রিঁ র্ণ্টিঁ র্ণ্ট্রিঁ র্ন্টিঁ র্ন্ট্রিঁ র্প্টিঁ র্ফ্টিঁ র্ল্টিঁ র্ল্ট্রিঁ র্ষ্টিঁ র্ষ্ট্রিঁ র্স্টিঁ র্স্ট্রিঁ" #Tallest clusters
]