[meta]
build_commit  = "b82064346c297d12cb3a2c6fa3674cf516f9e89d"

[input.features]
half = true
cjct = true
pres = true
psts = true

[input]
script = "bng2"
language = "dflt"
comparison_mode = "full"
text = [
	"নী টী ক্টী পী প্তী", # Alternate iiMatras
	"ঠী ঠ্রী ণ্ঠী ণ্ঠ্রী ন্ঠী ষ্ঠী ঠ্বী" # iiMatra ttha ligatures
]
