[meta]
build_commit  = "b82064346c297d12cb3a2c6fa3674cf516f9e89d"

[input.features]
half = true
cjct = true
pres = true

[input]
script = "beng"
comparison_mode = "full"
text = [
	"র্মি র্কি র্ল্রি র্দ্ভি র্স্ত্বি র্ণ্মি র্ষ্ফি র্প্মি র্ম্দ্রি র্ঙ্মি র্ব্বি র্ড্ডি র্ল্ঘি র্জ্জি র্ক্ষ্মি", # Alternate iMatras with reph
	"মিঁ কিঁ ল্রিঁ দ্ভিঁ স্ত্বিঁ ণ্মিঁ ষ্ফিঁ প্মিঁ ম্দ্রিঁ ঙ্মিঁ ব্বিঁ ড্ডিঁ ল্ঘিঁ জ্জিঁ ক্ষ্মিঁ", # Alternate iMatras with Candrabindu
	"র্মিঁ র্কিঁ র্ল্রিঁ র্দ্ভিঁ র্স্ত্বিঁ র্ণ্মিঁ র্ষ্ফিঁ র্প্মিঁ র্ম্দ্রিঁ র্ঙ্মিঁ র্ব্বিঁ র্ড্ডিঁ র্ল্ঘিঁ র্জ্জিঁ র্ক্ষ্মিঁ",  # Alternate iMatras with Candrabindu and Reph
]