[meta]
build_commit  = "b82064346c297d12cb3a2c6fa3674cf516f9e89d"

[input.features]
pstf = true
psts = true

[input]
script = "beng"
language = "dflt"
comparison_mode = "full"
text = [
	"ক্য হ্য", #Ya post-forms
]