[meta]
build_commit  = "b82064346c297d12cb3a2c6fa3674cf516f9e89d"

[input.features]
half = true
cjct = true
pres = true

[input]
script = "beng"
language = "dflt"
comparison_mode = "full"
text = [
	"ন্ক্ত ঘ্দ্ব ক্ট্র স্ক্ল", # Precomposed Triconsonants
	"ক্ক চ্ছ ণ্থ প্ত ল্ঘ হ্ম ক্ব ব্র" # Precomposed Biconsonants
]