[meta]
build_commit  = "b82064346c297d12cb3a2c6fa3674cf516f9e89d"

[input.features]
half = true
cjct = true
pres = true

[input]
script = "beng"
comparison_mode = "full"
text = [
	"ট্রে ট্টে ল্রে শ্রে ষ্টে", # For combinations with too little space
	"ক্মে ব্দে জ্ঝে ল্কে ল্তে", # For combinations with too much space
]
