[meta]
build_commit  = "e2766096416e641da5edff0ced5c1f8f9dcc0e5b"

[input.features]
calt = true

[input]
direction = "ltr"
comparison_mode = "glyphstream"
text = [ 
    "Google_logo google_logo", # logo
    "google_G google_g", # G logo
    "super_G_logo super_g_logo", # Super G logo
    "G_logo", # G logo
    "e_logo", # e logo
    "g_logo", # g logo
    "l_logo", # l logo
    "o_logo", # o logo
    "09:30 1:20pm", # colon time used between figures in calt feature
]