[meta]
build_commit  = "a5a5dcdd350495ddf662476f49c7271e8b38ab81"

[input.features]
case = true

[input]
script = "DFLT"
language = "dflt"
direction = "ltr"
comparison_mode = "glyphstream"
text = [ 
    "0123456789", # figures
    "09:30 1:20pm", # time values with `case` active should use colon.time centered colon
    "@[](){}¿¡-–—‹›«»·•", # punctuation
    "#%‰‱",
    "°℉℃", # temperature symbols
    "¢$₣£¤¥₤₩₫₮₸₹₺₽₱₴₪ƒ€", # currency
    "Μήλα ή αχλάδια", # Greek string with lower case surrounding etatonos (see https://github.com/googlefonts/googlesans/issues/157)
    "ΜΗΛΑ Ή ΑΧΛΑΔΙΑ", # Greek string with all caps including Etatonos (see https://github.com/googlefonts/googlesans/issues/157)
]