[meta]
build_commit  = ""

[input.features]
ccmp = true
c2sc = true
smcp = true

[input]
script = "latn"
language = "dflt"
direction = "ltr"
comparison_mode = "full"
text = [
    "i̊i̮̊j̮̊", # idotless and jdotless
    "W̆́w̆́",
    "W̊̊ẘ̊",
    "ííj́ ÍÍJ́ j̣ j̈́ j̣̈́ ḯ ị̈́ J̣ J̈́ J̣̈́ Ḯ Ị̈́"
]
