[meta]
build_commit = "ed195a4a252bb8d585c3c16a56133f7585e84894"

[input.features]
ccmp = true

[input]
script = "laoo"
language = "dflt"
direction = "ltr"
comparison_mode = "full"
text = [
    "ກ່ຂ່ຄ່ຆ່ງ່ຈ່ຉ່ຊ່ຌ່ຍ່ຎ່ຏ່ຐ່ຑ່ຒ່ຓ່ດ່ຕ່ຖ່ທ່ຘ່ນ່ບ່ປ່ຜ່ຝ່ພ່ຟ່ຠ່ມ່ຢ່ຣ່ລ່ວ່ຨ່ຩ່ສ່ຫ່ອ່ຮ່ຬ່ໜ່ໝ່ໞ່ໟ່",
    "ກ້ຂ້ຄ້ຆ້ງ້ຈ້ຉ້ຊ້ຌ້ຍ້ຎ້ຏ້ຐ້ຑ້ຒ້ຓ້ດ້ຕ້ຖ້ທ້ຘ້ນ້ບ້ປ້ຜ້ຝ້ພ້ຟ້ຠ້ມ້ຢ້ຣ້ລ້ວ້ຨ້ຩ້ສ້ຫ້ອ້ຮ້ຬ້ໜ້ໝ້ໞ້ໟ້",
    "ກ໊ຂ໊ຄ໊ຆ໊ງ໊ຈ໊ຉ໊ຊ໊ຌ໊ຍ໊ຎ໊ຏ໊ຐ໊ຑ໊ຒ໊ຓ໊ດ໊ຕ໊ຖ໊ທ໊ຘ໊ນ໊ບ໊ປ໊ຜ໊ຝ໊ພ໊ຟ໊ຠ໊ມ໊ຢ໊ຣ໊ລ໊ວ໊ຨ໊ຩ໊ສ໊ຫ໊ອ໊ຮ໊ຬ໊ໜ໊ໝ໊ໞ໊ໟ໊",
    "ກ໋ຂ໋ຄ໋ຆ໋ງ໋ຈ໋ຉ໋ຊ໋ຌ໋ຍ໋ຎ໋ຏ໋ຐ໋ຑ໋ຒ໋ຓ໋ດ໋ຕ໋ຖ໋ທ໋ຘ໋ນ໋ບ໋ປ໋ຜ໋ຝ໋ພ໋ຟ໋ຠ໋ມ໋ຢ໋ຣ໋ລ໋ວ໋ຨ໋ຩ໋ສ໋ຫ໋ອ໋ຮ໋ຬ໋ໜ໋ໝ໋ໞ໋ໟ໋",
    "ກ໌ຂ໌ຄ໌ຆ໌ງ໌ຈ໌ຉ໌ຊ໌ຌ໌ຍ໌ຎ໌ຏ໌ຐ໌ຑ໌ຒ໌ຓ໌ດ໌ຕ໌ຖ໌ທ໌ຘ໌ນ໌ບ໌ປ໌ຜ໌ຝ໌ພ໌ຟ໌ຠ໌ມ໌ຢ໌ຣ໌ລ໌ວ໌ຨ໌ຩ໌ສ໌ຫ໌ອ໌ຮ໌ຬ໌ໜ໌ໝ໌ໞ໌ໟ໌",
    "ກຸຂຸຄຸຆຸງຸຈຸຉຸຊຸຌຸຍຸຎຸຏຸຐຸຑຸຒຸຓຸດຸຕຸຖຸທຸຘຸນຸບຸປຸຜຸຝຸພຸຟຸຠຸມຸຢຸຣຸລຸວຸຨຸຩຸສຸຫຸອຸຮຸຬຸໜຸໝຸໞຸໟຸ",
    "ກູຂູຄູຆູງູຈູຉູຊູຌູຍູຎູຏູຐູຑູຒູຓູດູຕູຖູທູຘູນູບູປູຜູຝູພູຟູຠູມູຢູຣູລູວູຨູຩູສູຫູອູຮູຬູໜູໝູໞູໟູ",
    "ກ຺ຂ຺ຄ຺ຆ຺ງ຺ຈ຺ຉ຺ຊ຺ຌ຺ຍ຺ຎ຺ຏ຺ຐ຺ຑ຺ຒ຺ຓ຺ດ຺ຕ຺ຖ຺ທ຺ຘ຺ນ຺ບ຺ປ຺ຜ຺ຝ຺ພ຺ຟ຺ຠ຺ມ຺ຢ຺ຣ຺ລ຺ວ຺ຨ຺ຩ຺ສ຺ຫ຺ອ຺ຮ຺ຬ຺ໜ຺ໝ຺ໞ຺ໟ຺",
    "ກຼຂຼຄຼຆຼງຼຈຼຉຼຊຼຌຼຍຼຎຼຏຼຐຼຑຼຒຼຓຼດຼຕຼຖຼທຼຘຼນຼບຼປຼຜຼຝຼພຼຟຼຠຼມຼຢຼຣຼລຼວຼຨຼຩຼສຼຫຼອຼຮຼຬຼໜຼໝຼໞຼໟຼ",
    "ກັຂັຄັຆັງັຈັຉັຊັຌັຍັຎັຏັຐັຑັຒັຓັດັຕັຖັທັຘັນັບັປັຜັຝັພັຟັຠັມັຢັຣັລັວັຨັຩັສັຫັອັຮັຬັໜັໝັໞັໟັ",
    "ກັ່ຂັ່ຄັ່ຆັ່ງັ່ຈັ່ຉັ່ຊັ່ຌັ່ຍັ່ຎັ່ຏັ່ຐັ່ຑັ່ຒັ່ຓັ່ດັ່ຕັ່ຖັ່ທັ່ຘັ່ນັ່ບັ່ປັ່ຜັ່ຝັ່ພັ່ຟັ່ຠັ່ມັ່ຢັ່ຣັ່ລັ່ວັ່ຨັ່ຩັ່ສັ່ຫັ່ອັ່ຮັ່ຬັ່ໜັ່ໝັ່ໞັ່ໟັ່",
    "ກັ້ຂັ້ຄັ້ຆັ້ງັ້ຈັ້ຉັ້ຊັ້ຌັ້ຍັ້ຎັ້ຏັ້ຐັ້ຑັ້ຒັ້ຓັ້ດັ້ຕັ້ຖັ້ທັ້ຘັ້ນັ້ບັ້ປັ້ຜັ້ຝັ້ພັ້ຟັ້ຠັ້ມັ້ຢັ້ຣັ້ລັ້ວັ້ຨັ້ຩັ້ສັ້ຫັ້ອັ້ຮັ້ຬັ້ໜັ້ໝັ້ໞັ້ໟັ້",
    "ກັ໊ຂັ໊ຄັ໊ຆັ໊ງັ໊ຈັ໊ຉັ໊ຊັ໊ຌັ໊ຍັ໊ຎັ໊ຏັ໊ຐັ໊ຑັ໊ຒັ໊ຓັ໊ດັ໊ຕັ໊ຖັ໊ທັ໊ຘັ໊ນັ໊ບັ໊ປັ໊ຜັ໊ຝັ໊ພັ໊ຟັ໊ຠັ໊ມັ໊ຢັ໊ຣັ໊ລັ໊ວັ໊ຨັ໊ຩັ໊ສັ໊ຫັ໊ອັ໊ຮັ໊ຬັ໊ໜັ໊ໝັ໊ໞັ໊ໟັ໊",
    "ກັ໋ຂັ໋ຄັ໋ຆັ໋ງັ໋ຈັ໋ຉັ໋ຊັ໋ຌັ໋ຍັ໋ຎັ໋ຏັ໋ຐັ໋ຑັ໋ຒັ໋ຓັ໋ດັ໋ຕັ໋ຖັ໋ທັ໋ຘັ໋ນັ໋ບັ໋ປັ໋ຜັ໋ຝັ໋ພັ໋ຟັ໋ຠັ໋ມັ໋ຢັ໋ຣັ໋ລັ໋ວັ໋ຨັ໋ຩັ໋ສັ໋ຫັ໋ອັ໋ຮັ໋ຬັ໋ໜັ໋ໝັ໋ໞັ໋ໟັ໋",
    "ກົຂົຄົຆົງົຈົຉົຊົຌົຍົຎົຏົຐົຑົຒົຓົດົຕົຖົທົຘົນົບົປົຜົຝົພົຟົຠົມົຢົຣົລົວົຨົຩົສົຫົອົຮົຬົໜົໝົໞົໟົ",
    "ກົ່ຂົ່ຄົ່ຆົ່ງົ່ຈົ່ຉົ່ຊົ່ຌົ່ຍົ່ຎົ່ຏົ່ຐົ່ຑົ່ຒົ່ຓົ່ດົ່ຕົ່ຖົ່ທົ່ຘົ່ນົ່ບົ່ປົ່ຜົ່ຝົ່ພົ່ຟົ່ຠົ່ມົ່ຢົ່ຣົ່ລົ່ວົ່ຨົ່ຩົ່ສົ່ຫົ່ອົ່ຮົ່ຬົ່ໜົ່ໝົ່ໞົ່ໟົ່",
    "ກົ້ຂົ້ຄົ້ຆົ້ງົ້ຈົ້ຉົ້ຊົ້ຌົ້ຍົ້ຎົ້ຏົ້ຐົ້ຑົ້ຒົ້ຓົ້ດົ້ຕົ້ຖົ້ທົ້ຘົ້ນົ້ບົ້ປົ້ຜົ້ຝົ້ພົ້ຟົ້ຠົ້ມົ້ຢົ້ຣົ້ລົ້ວົ້ຨົ້ຩົ້ສົ້ຫົ້ອົ້ຮົ້ຬົ້ໜົ້ໝົ້ໞົ້ໟົ້",
    "ກົ໊ຂົ໊ຄົ໊ຆົ໊ງົ໊ຈົ໊ຉົ໊ຊົ໊ຌົ໊ຍົ໊ຎົ໊ຏົ໊ຐົ໊ຑົ໊ຒົ໊ຓົ໊ດົ໊ຕົ໊ຖົ໊ທົ໊ຘົ໊ນົ໊ບົ໊ປົ໊ຜົ໊ຝົ໊ພົ໊ຟົ໊ຠົ໊ມົ໊ຢົ໊ຣົ໊ລົ໊ວົ໊ຨົ໊ຩົ໊ສົ໊ຫົ໊ອົ໊ຮົ໊ຬົ໊ໜົ໊ໝົ໊ໞົ໊ໟົ໊",
    "ກົ໋ຂົ໋ຄົ໋ຆົ໋ງົ໋ຈົ໋ຉົ໋ຊົ໋ຌົ໋ຍົ໋ຎົ໋ຏົ໋ຐົ໋ຑົ໋ຒົ໋ຓົ໋ດົ໋ຕົ໋ຖົ໋ທົ໋ຘົ໋ນົ໋ບົ໋ປົ໋ຜົ໋ຝົ໋ພົ໋ຟົ໋ຠົ໋ມົ໋ຢົ໋ຣົ໋ລົ໋ວົ໋ຨົ໋ຩົ໋ສົ໋ຫົ໋ອົ໋ຮົ໋ຬົ໋ໜົ໋ໝົ໋ໞົ໋ໟົ໋",
    "ກິຂິຄິຆິງິຈິຉິຊິຌິຍິຎິຏິຐິຑິຒິຓິດິຕິຖິທິຘິນິບິປິຜິຝິພິຟິຠິມິຢິຣິລິວິຨິຩິສິຫິອິຮິຬິໜິໝິໞິໟິ",
    "ກິ່ຂິ່ຄິ່ຆິ່ງິ່ຈິ່ຉິ່ຊິ່ຌິ່ຍິ່ຎິ່ຏິ່ຐິ່ຑິ່ຒິ່ຓິ່ດິ່ຕິ່ຖິ່ທິ່ຘິ່ນິ່ບິ່ປິ່ຜິ່ຝິ່ພິ່ຟິ່ຠິ່ມິ່ຢິ່ຣິ່ລິ່ວິ່ຨິ່ຩິ່ສິ່ຫິ່ອິ່ຮິ່ຬິ່ໜິ່ໝິ່ໞິ່ໟິ່",
    "ກິ້ຂິ້ຄິ້ຆິ້ງິ້ຈິ້ຉິ້ຊິ້ຌິ້ຍິ້ຎິ້ຏິ້ຐິ້ຑິ້ຒິ້ຓິ້ດິ້ຕິ້ຖິ້ທິ້ຘິ້ນິ້ບິ້ປິ້ຜິ້ຝິ້ພິ້ຟິ້ຠິ້ມິ້ຢິ້ຣິ້ລິ້ວິ້ຨິ້ຩິ້ສິ້ຫິ້ອິ້ຮິ້ຬິ້ໜິ້ໝິ້ໞິ້ໟິ້",
    "ກິ໊ຂິ໊ຄິ໊ຆິ໊ງິ໊ຈິ໊ຉິ໊ຊິ໊ຌິ໊ຍິ໊ຎິ໊ຏິ໊ຐິ໊ຑິ໊ຒິ໊ຓິ໊ດິ໊ຕິ໊ຖິ໊ທິ໊ຘິ໊ນິ໊ບິ໊ປິ໊ຜິ໊ຝິ໊ພິ໊ຟິ໊ຠິ໊ມິ໊ຢິ໊ຣິ໊ລິ໊ວິ໊ຨິ໊ຩິ໊ສິ໊ຫິ໊ອິ໊ຮິ໊ຬິ໊ໜິ໊ໝິ໊ໞິ໊ໟິ໊",
    "ກິ໋ຂິ໋ຄິ໋ຆິ໋ງິ໋ຈິ໋ຉິ໋ຊິ໋ຌິ໋ຍິ໋ຎິ໋ຏິ໋ຐິ໋ຑິ໋ຒິ໋ຓິ໋ດິ໋ຕິ໋ຖິ໋ທິ໋ຘິ໋ນິ໋ບິ໋ປິ໋ຜິ໋ຝິ໋ພິ໋ຟິ໋ຠິ໋ມິ໋ຢິ໋ຣິ໋ລິ໋ວິ໋ຨິ໋ຩິ໋ສິ໋ຫິ໋ອິ໋ຮິ໋ຬິ໋ໜິ໋ໝິ໋ໞິ໋ໟິ໋",
    "ກິ໌ຂິ໌ຄິ໌ຆິ໌ງິ໌ຈິ໌ຉິ໌ຊິ໌ຌິ໌ຍິ໌ຎິ໌ຏິ໌ຐິ໌ຑິ໌ຒິ໌ຓິ໌ດິ໌ຕິ໌ຖິ໌ທິ໌ຘິ໌ນິ໌ບິ໌ປິ໌ຜິ໌ຝິ໌ພິ໌ຟິ໌ຠິ໌ມິ໌ຢິ໌ຣິ໌ລິ໌ວິ໌ຨິ໌ຩິ໌ສິ໌ຫິ໌ອິ໌ຮິ໌ຬິ໌ໜິ໌ໝິ໌ໞິ໌ໟິ໌",
    "ກີຂີຄີຆີງີຈີຉີຊີຌີຍີຎີຏີຐີຑີຒີຓີດີຕີຖີທີຘີນີບີປີຜີຝີພີຟີຠີມີຢີຣີລີວີຨີຩີສີຫີອີຮີຬີໜີໝີໞີໟີ",
    "ກີ່ຂີ່ຄີ່ຆີ່ງີ່ຈີ່ຉີ່ຊີ່ຌີ່ຍີ່ຎີ່ຏີ່ຐີ່ຑີ່ຒີ່ຓີ່ດີ່ຕີ່ຖີ່ທີ່ຘີ່ນີ່ບີ່ປີ່ຜີ່ຝີ່ພີ່ຟີ່ຠີ່ມີ່ຢີ່ຣີ່ລີ່ວີ່ຨີ່ຩີ່ສີ່ຫີ່ອີ່ຮີ່ຬີ່ໜີ່ໝີ່ໞີ່ໟີ່",
    "ກີ້ຂີ້ຄີ້ຆີ້ງີ້ຈີ້ຉີ້ຊີ້ຌີ້ຍີ້ຎີ້ຏີ້ຐີ້ຑີ້ຒີ້ຓີ້ດີ້ຕີ້ຖີ້ທີ້ຘີ້ນີ້ບີ້ປີ້ຜີ້ຝີ້ພີ້ຟີ້ຠີ້ມີ້ຢີ້ຣີ້ລີ້ວີ້ຨີ້ຩີ້ສີ້ຫີ້ອີ້ຮີ້ຬີ້ໜີ້ໝີ້ໞີ້ໟີ້",
    "ກີ໊ຂີ໊ຄີ໊ຆີ໊ງີ໊ຈີ໊ຉີ໊ຊີ໊ຌີ໊ຍີ໊ຎີ໊ຏີ໊ຐີ໊ຑີ໊ຒີ໊ຓີ໊ດີ໊ຕີ໊ຖີ໊ທີ໊ຘີ໊ນີ໊ບີ໊ປີ໊ຜີ໊ຝີ໊ພີ໊ຟີ໊ຠີ໊ມີ໊ຢີ໊ຣີ໊ລີ໊ວີ໊ຨີ໊ຩີ໊ສີ໊ຫີ໊ອີ໊ຮີ໊ຬີ໊ໜີ໊ໝີ໊ໞີ໊ໟີ໊",
    "ກີ໋ຂີ໋ຄີ໋ຆີ໋ງີ໋ຈີ໋ຉີ໋ຊີ໋ຌີ໋ຍີ໋ຎີ໋ຏີ໋ຐີ໋ຑີ໋ຒີ໋ຓີ໋ດີ໋ຕີ໋ຖີ໋ທີ໋ຘີ໋ນີ໋ບີ໋ປີ໋ຜີ໋ຝີ໋ພີ໋ຟີ໋ຠີ໋ມີ໋ຢີ໋ຣີ໋ລີ໋ວີ໋ຨີ໋ຩີ໋ສີ໋ຫີ໋ອີ໋ຮີ໋ຬີ໋ໜີ໋ໝີ໋ໞີ໋ໟີ໋",
    "ກີ໌ຂີ໌ຄີ໌ຆີ໌ງີ໌ຈີ໌ຉີ໌ຊີ໌ຌີ໌ຍີ໌ຎີ໌ຏີ໌ຐີ໌ຑີ໌ຒີ໌ຓີ໌ດີ໌ຕີ໌ຖີ໌ທີ໌ຘີ໌ນີ໌ບີ໌ປີ໌ຜີ໌ຝີ໌ພີ໌ຟີ໌ຠີ໌ມີ໌ຢີ໌ຣີ໌ລີ໌ວີ໌ຨີ໌ຩີ໌ສີ໌ຫີ໌ອີ໌ຮີ໌ຬີ໌ໜີ໌ໝີ໌ໞີ໌ໟີ໌",
    "ກຶຂຶຄຶຆຶງຶຈຶຉຶຊຶຌຶຍຶຎຶຏຶຐຶຑຶຒຶຓຶດຶຕຶຖຶທຶຘຶນຶບຶປຶຜຶຝຶພຶຟຶຠຶມຶຢຶຣຶລຶວຶຨຶຩຶສຶຫຶອຶຮຶຬຶໜຶໝຶໞຶໟຶ",
    "ກຶ່ຂຶ່ຄຶ່ຆຶ່ງຶ່ຈຶ່ຉຶ່ຊຶ່ຌຶ່ຍຶ່ຎຶ່ຏຶ່ຐຶ່ຑຶ່ຒຶ່ຓຶ່ດຶ່ຕຶ່ຖຶ່ທຶ່ຘຶ່ນຶ່ບຶ່ປຶ່ຜຶ່ຝຶ່ພຶ່ຟຶ່ຠຶ່ມຶ່ຢຶ່ຣຶ່ລຶ່ວຶ່ຨຶ່ຩຶ່ສຶ່ຫຶ່ອຶ່ຮຶ່ຬຶ່ໜຶ່ໝຶ່ໞຶ່ໟຶ່",
    "ກຶ້ຂຶ້ຄຶ້ຆຶ້ງຶ້ຈຶ້ຉຶ້ຊຶ້ຌຶ້ຍຶ້ຎຶ້ຏຶ້ຐຶ້ຑຶ້ຒຶ້ຓຶ້ດຶ້ຕຶ້ຖຶ້ທຶ້ຘຶ້ນຶ້ບຶ້ປຶ້ຜຶ້ຝຶ້ພຶ້ຟຶ້ຠຶ້ມຶ້ຢຶ້ຣຶ້ລຶ້ວຶ້ຨຶ້ຩຶ້ສຶ້ຫຶ້ອຶ້ຮຶ້ຬຶ້ໜຶ້ໝຶ້ໞຶ້ໟຶ້",
    "ກຶ໊ຂຶ໊ຄຶ໊ຆຶ໊ງຶ໊ຈຶ໊ຉຶ໊ຊຶ໊ຌຶ໊ຍຶ໊ຎຶ໊ຏຶ໊ຐຶ໊ຑຶ໊ຒຶ໊ຓຶ໊ດຶ໊ຕຶ໊ຖຶ໊ທຶ໊ຘຶ໊ນຶ໊ບຶ໊ປຶ໊ຜຶ໊ຝຶ໊ພຶ໊ຟຶ໊ຠຶ໊ມຶ໊ຢຶ໊ຣຶ໊ລຶ໊ວຶ໊ຨຶ໊ຩຶ໊ສຶ໊ຫຶ໊ອຶ໊ຮຶ໊ຬຶ໊ໜຶ໊ໝຶ໊ໞຶ໊ໟຶ໊",
    "ກຶ໋ຂຶ໋ຄຶ໋ຆຶ໋ງຶ໋ຈຶ໋ຉຶ໋ຊຶ໋ຌຶ໋ຍຶ໋ຎຶ໋ຏຶ໋ຐຶ໋ຑຶ໋ຒຶ໋ຓຶ໋ດຶ໋ຕຶ໋ຖຶ໋ທຶ໋ຘຶ໋ນຶ໋ບຶ໋ປຶ໋ຜຶ໋ຝຶ໋ພຶ໋ຟຶ໋ຠຶ໋ມຶ໋ຢຶ໋ຣຶ໋ລຶ໋ວຶ໋ຨຶ໋ຩຶ໋ສຶ໋ຫຶ໋ອຶ໋ຮຶ໋ຬຶ໋ໜຶ໋ໝຶ໋ໞຶ໋ໟຶ໋",
    "ກຶ໌ຂຶ໌ຄຶ໌ຆຶ໌ງຶ໌ຈຶ໌ຉຶ໌ຊຶ໌ຌຶ໌ຍຶ໌ຎຶ໌ຏຶ໌ຐຶ໌ຑຶ໌ຒຶ໌ຓຶ໌ດຶ໌ຕຶ໌ຖຶ໌ທຶ໌ຘຶ໌ນຶ໌ບຶ໌ປຶ໌ຜຶ໌ຝຶ໌ພຶ໌ຟຶ໌ຠຶ໌ມຶ໌ຢຶ໌ຣຶ໌ລຶ໌ວຶ໌ຨຶ໌ຩຶ໌ສຶ໌ຫຶ໌ອຶ໌ຮຶ໌ຬຶ໌ໜຶ໌ໝຶ໌ໞຶ໌ໟຶ໌",
    "ກືຂືຄືຆືງືຈືຉືຊືຌືຍືຎືຏືຐືຑືຒືຓືດືຕືຖືທືຘືນືບືປືຜືຝືພືຟືຠືມືຢືຣືລືວືຨືຩືສືຫືອືຮືຬືໜືໝືໞືໟື",
    "ກື່ຂື່ຄື່ຆື່ງື່ຈື່ຉື່ຊື່ຌື່ຍື່ຎື່ຏື່ຐື່ຑື່ຒື່ຓື່ດື່ຕື່ຖື່ທື່ຘື່ນື່ບື່ປື່ຜື່ຝື່ພື່ຟື່ຠື່ມື່ຢື່ຣື່ລື່ວື່ຨື່ຩື່ສື່ຫື່ອື່ຮື່ຬື່ໜື່ໝື່ໞື່ໟື່",
    "ກື້ຂື້ຄື້ຆື້ງື້ຈື້ຉື້ຊື້ຌື້ຍື້ຎື້ຏື້ຐື້ຑື້ຒື້ຓື້ດື້ຕື້ຖື້ທື້ຘື້ນື້ບື້ປື້ຜື້ຝື້ພື້ຟື້ຠື້ມື້ຢື້ຣື້ລື້ວື້ຨື້ຩື້ສື້ຫື້ອື້ຮື້ຬື້ໜື້ໝື້ໞື້ໟື້",
    "ກື໊ຂື໊ຄື໊ຆື໊ງື໊ຈື໊ຉື໊ຊື໊ຌື໊ຍື໊ຎື໊ຏື໊ຐື໊ຑື໊ຒື໊ຓື໊ດື໊ຕື໊ຖື໊ທື໊ຘື໊ນື໊ບື໊ປື໊ຜື໊ຝື໊ພື໊ຟື໊ຠື໊ມື໊ຢື໊ຣື໊ລື໊ວື໊ຨື໊ຩື໊ສື໊ຫື໊ອື໊ຮື໊ຬື໊ໜື໊ໝື໊ໞື໊ໟື໊",
    "ກື໋ຂື໋ຄື໋ຆື໋ງື໋ຈື໋ຉື໋ຊື໋ຌື໋ຍື໋ຎື໋ຏື໋ຐື໋ຑື໋ຒື໋ຓື໋ດື໋ຕື໋ຖື໋ທື໋ຘື໋ນື໋ບື໋ປື໋ຜື໋ຝື໋ພື໋ຟື໋ຠື໋ມື໋ຢື໋ຣື໋ລື໋ວື໋ຨື໋ຩື໋ສື໋ຫື໋ອື໋ຮື໋ຬື໋ໜື໋ໝື໋ໞື໋ໟື໋",
    "ກື໌ຂື໌ຄື໌ຆື໌ງື໌ຈື໌ຉື໌ຊື໌ຌື໌ຍື໌ຎື໌ຏື໌ຐື໌ຑື໌ຒື໌ຓື໌ດື໌ຕື໌ຖື໌ທື໌ຘື໌ນື໌ບື໌ປື໌ຜື໌ຝື໌ພື໌ຟື໌ຠື໌ມື໌ຢື໌ຣື໌ລື໌ວື໌ຨື໌ຩື໌ສື໌ຫື໌ອື໌ຮື໌ຬື໌ໜື໌ໝື໌ໞື໌ໟື໌",
    "ກໍຂໍຄໍຆໍງໍຈໍຉໍຊໍຌໍຍໍຎໍຏໍຐໍຑໍຒໍຓໍດໍຕໍຖໍທໍຘໍນໍບໍປໍຜໍຝໍພໍຟໍຠໍມໍຢໍຣໍລໍວໍຨໍຩໍສໍຫໍອໍຮໍຬໍໜໍໝໍໞໍໟໍ",
    "ກໍ່ຂໍ່ຄໍ່ຆໍ່ງໍ່ຈໍ່ຉໍ່ຊໍ່ຌໍ່ຍໍ່ຎໍ່ຏໍ່ຐໍ່ຑໍ່ຒໍ່ຓໍ່ດໍ່ຕໍ່ຖໍ່ທໍ່ຘໍ່ນໍ່ບໍ່ປໍ່ຜໍ່ຝໍ່ພໍ່ຟໍ່ຠໍ່ມໍ່ຢໍ່ຣໍ່ລໍ່ວໍ່ຨໍ່ຩໍ່ສໍ່ຫໍ່ອໍ່ຮໍ່ຬໍ່ໜໍ່ໝໍ່ໞໍ່ໟໍ່",
    "ກໍ້ຂໍ້ຄໍ້ຆໍ້ງໍ້ຈໍ້ຉໍ້ຊໍ້ຌໍ້ຍໍ້ຎໍ້ຏໍ້ຐໍ້ຑໍ້ຒໍ້ຓໍ້ດໍ້ຕໍ້ຖໍ້ທໍ້ຘໍ້ນໍ້ບໍ້ປໍ້ຜໍ້ຝໍ້ພໍ້ຟໍ້ຠໍ້ມໍ້ຢໍ້ຣໍ້ລໍ້ວໍ້ຨໍ້ຩໍ້ສໍ້ຫໍ້ອໍ້ຮໍ້ຬໍ້ໜໍ້ໝໍ້ໞໍ້ໟໍ້",
    "ກໍ໊ຂໍ໊ຄໍ໊ຆໍ໊ງໍ໊ຈໍ໊ຉໍ໊ຊໍ໊ຌໍ໊ຍໍ໊ຎໍ໊ຏໍ໊ຐໍ໊ຑໍ໊ຒໍ໊ຓໍ໊ດໍ໊ຕໍ໊ຖໍ໊ທໍ໊ຘໍ໊ນໍ໊ບໍ໊ປໍ໊ຜໍ໊ຝໍ໊ພໍ໊ຟໍ໊ຠໍ໊ມໍ໊ຢໍ໊ຣໍ໊ລໍ໊ວໍ໊ຨໍ໊ຩໍ໊ສໍ໊ຫໍ໊ອໍ໊ຮໍ໊ຬໍ໊ໜໍ໊ໝໍ໊ໞໍ໊ໟໍ໊",
    "ກໍ໋ຂໍ໋ຄໍ໋ຆໍ໋ງໍ໋ຈໍ໋ຉໍ໋ຊໍ໋ຌໍ໋ຍໍ໋ຎໍ໋ຏໍ໋ຐໍ໋ຑໍ໋ຒໍ໋ຓໍ໋ດໍ໋ຕໍ໋ຖໍ໋ທໍ໋ຘໍ໋ນໍ໋ບໍ໋ປໍ໋ຜໍ໋ຝໍ໋ພໍ໋ຟໍ໋ຠໍ໋ມໍ໋ຢໍ໋ຣໍ໋ລໍ໋ວໍ໋ຨໍ໋ຩໍ໋ສໍ໋ຫໍ໋ອໍ໋ຮໍ໋ຬໍ໋ໜໍ໋ໝໍ໋ໞໍ໋ໟໍ໋",
]
