[meta]
build_commit  = ""

[input.features]
ccmp = true
c2sc = true
smcp = true

[input]
script = "latn"
language = "nl"
comparison_mode = "glyphstream"
text = [ 
    "ij",
    "IJ",
    "ĳ",
    "Ĳ",
    "íj",
    "ÍJ",
    "íj́",
    "ÍJ́",
    "ĳ́",
    "Ĳ́",
    "kijk, wíj eten een ijsje KIJK, WÍJ ETEN EEN IJSJE lijnbus rijbaan Bergeijk affijn ijzermans krijgen"
]
