[meta]
build_commit  = "e2766096416e641da5edff0ced5c1f8f9dcc0e5b"

[input.features]
ccmp = true

[input]
script = "latn"
direction = "ltr"
comparison_mode = "full"
text = [
    "i̊i̮̊j̮̊",  # idotless and jdotless
    "W̆́w̆́",
    "W̊̊ẘ̊",
    "ííj́ ÍÍJ́ j̣ j̈́ j̣̈́ ḯ ị̈́ J̣ J̈́ J̣̈́ Ḯ Ị̈́",
    "į į̀ į́ į̂ į̃ į̄ į̌ і́ ј́ fį fị", # Soft-dotted glyphs
    "ij",
    "IJ",
    "ĳ",
    "Ĳ",
    "íj",
    "ÍJ",
    "íj́",
    "ÍJ́",
    "ĳ́",
    "Ĳ́",
    "į̒i̒ị̒j̒і̒ј̒" # Soft-dotting with commaturnedabovecomb.
]
