[meta]
build_commit  = ""

[input.features]
rphf = true
abvs = true

[input]
script = "dev2"
language = "dflt"
comparison_mode = "full"
text = [
    "र्क र्का र्कि र्की र्के र्कें र्कै र्कैं र्कॅ र्कॆ र्कं" # Reph forms
]
