[meta]
build_commit  = ""

[input.features]
half = true
cjct = true
pres = true
abvs = true

[input]
script = "dev2"
language = "dflt"
comparison_mode = "full"
text = [
    "रि ट्टि कि क्रि र्क्कि घि क्षिं र्त्तिं ह्मि ट्यि ट्यिं" # iMatra lengths
]
