[meta]
build_commit  = "c571fb5be539a2386cfe3a994a2de3f01fd6b944"

[input.features]
pres = true

[input]
script = "deva"
comparison_mode = "full"
text = [
    "त्त प्त ष्ट ष्ठ" # All included, linear conjuncts
]
