[meta]
build_commit  = ""

[input.features]
dlig = true

[input]
script = "hebr"
language = "IWR"
direction = "rtl"  # NOTE: RTL writing system
comparison_mode = "glyphstream"
text = [ 
    "אל", # Yiddish: alef lamed
    "וו", # Yiddish: vav vav
    "יו", # Yiddish: yod vav
    "יי", # Yiddish: yod yod
]