[meta]
build_commit  = "cd849c8decc1788e75e48b69f1fa8c0fa723a812"

[input.features]
dlig = true

[input]
script = "hebr"
language = "IWR"
direction = "rtl"  # NOTE: RTL writing system
comparison_mode = "glyphstream"
text = [ 
    "אל", # Yiddish: alef lamed
    "וו", # Yiddish: vav vav
    "יו", # Yiddish: yod vav
    "וי", # Yiddish: vav yod
    "יי", # Yiddish: yod yod
]