[meta]
build_commit = "d2a5e8c5c0865baad74c9dd385fe559ed9141bfb"

[input.features]

[input]
text = [
    # Validate that single digits are NOT substituted with a positinal form
    "፪",
    # Validate that 2 digit numbers are substituted with the following pattern [*.init *.fina]
    "፶፪",
    # Validate that 3 digit numbers are substituted with the following pattern [*.init *.medi *.fina]
    "፻፶፪",
    # Validate that 5 digit numbers are substituted with the following pattern [*.init *.medi *.medi *.medi *.fina]
    "፲፱፻፳፯",
]
