[meta]
build_commit = ""

[input.features]
# Redundant feature to connect bars over and under ethiopic numbers for use with apps that fail to identify the Ethiopic script.
ss10 = true

[input]
text = [
    # Validate that single digits are NOT substituted with a positinal form
    "፪",
    # Validate that 2 digit numbers are substituted with the following pattern [*.init *.fina] 
    "፶፪",
    # Validate that 3 digit numbers are substituted with the following pattern [*.init *.medi *.fina]
    "፻፶፪",
    # Validate that 5 digit numbers are substituted with the following pattern [*.init *.medi *.medi *.medi *.fina]
    "፲፱፻፳፯",
]
