[meta]
build_commit = ""

[input.features]
calt = true

[input]
comparison_mode = "full"
text = [
    "abo- აბო-", # the dash and other marks located in punctuation.centered should be shifted down with 25 point more as same symbol next to the Latin character
    "abo· აბო·",
    "abo— აბო—",
    "abo+ აბო+",
    "abo - აბო -", # it should work when space is used between letters and marks
    "abo,- აბო,-", # it should work when other mark is used between letters and marks
]
