[meta]
build_commit = "9b0b2f7261b0b64c10572d18dea142ef3c6c08da"

[input.features]
case = true

[input]
text = [
    "აბგ ᲐᲑᲒ",  # It is like abc ABC
    "ამო჻ ᲐᲛᲝ჻", # the paragraph separator should be shifted up too
    "₾",  # lari currency symbol should have lari.cap form
]
