[meta]
build_commit  = ""

[input.features]
rphf = true
abvs = true
pres = true
psts = true
abvm = true
blwm = true

[input]
script = "gujr"
language = "dflt"
comparison_mode = "full"
text = [
    "ર્મે ર્મો ર્મેં ર્મોં ર્મૈ ર્મૌ ર્મૈં ર્મૌં ર્ક ર્કે ર્કેં ર્કો ર્કોં ર્કૈ ર્કૈં ર્કૌ ર્કૌં" # Above Matra Ligatures
]
