[meta]
build_commit  = ""

[input.features]
akhn = true
rkrf = true
half = true
psts = true
blwm = true
dist = true

[input]
script = "gujr"
language = "dflt"
comparison_mode = "full"
text = [
    "ક્ચ ખ્ચ ક્ષ્ચ શ્ર્ય" # Half forms
]
