[meta]
build_commit  = ""

[input.features]
rphf = true
psts = true
abvm = true
blwm = true

[input]
script = "gjr2"
language = "dflt"
comparison_mode = "full"
text = [
    "ર્મ ર્ક ર્ર ર્ઝ" # Reph forms
]
