[meta]
build_commit  = ""

[input.features]
akhn = true
rkrf = true
psts = true
blwm = true

[input]
script = "gjr2"
language = "dflt"
comparison_mode = "full"
text = [
    "ક્ર ખ્ર ગ્ર ઘ્ર ચ્ર જ્ર ઝ્ર ઞ્ર ટ્ર ઠ્ર ડ્ર ઢ્ર ણ્ર ત્ર થ્ર દ્ર ધ્ર ન્ર પ્ર ફ્ર બ્ર ભ્ર મ્ર ય્ર લ્ર ળ્ર વ્ર શ્ર ષ્ર સ્ર હ્ર ક્ષ્ર" # Base rakaar forms
]
