[meta]
build_commit  = "e2ec9733b2d33a1fe3ba47ac23cfc52de558d876"

[input.features]
nukt = true
blwf = true

[input]
script = "guru"
language = "dflt"
comparison_mode = "full"
text = [
    "ਕ੍ਹ ਖ੍ਹ ਗ੍ਹ ਘ੍ਹ ਙ੍ਹ ਚ੍ਹ ਛ੍ਹ ਜ੍ਹ ਝ੍ਹ ਞ੍ਹ ਟ੍ਹ ਠ੍ਹ ਡ੍ਹ ਢ੍ਹ ਣ੍ਹ ਤ੍ਹ ਥ੍ਹ ਦ੍ਹ ਧ੍ਹ ਨ੍ਹ ਪ੍ਹ ਫ੍ਹ ਬ੍ਹ ਭ੍ਹ ਮ੍ਹ ਯ੍ਹ ਰ੍ਹ ਲ੍ਹ ਲ਼੍ਹ ਵ੍ਹ ਸ਼੍ਹ ਸ੍ਹ ਹ੍ਹ ਖ਼੍ਹ ਗ਼੍ਹ ਜ਼੍ਹ ੜ੍ਹ ਫ਼੍ਹ", # Ha below conjuncts
    "ਕ੍ਰ ਖ੍ਰ ਗ੍ਰ ਘ੍ਰ ਙ੍ਰ ਚ੍ਰ ਛ੍ਰ ਜ੍ਰ ਝ੍ਰ ਞ੍ਰ ਟ੍ਰ ਠ੍ਰ ਡ੍ਰ ਢ੍ਰ ਣ੍ਰ ਤ੍ਰ ਥ੍ਰ ਦ੍ਰ ਧ੍ਰ ਨ੍ਰ ਪ੍ਰ ਫ੍ਰ ਬ੍ਰ ਭ੍ਰ ਮ੍ਰ ਯ੍ਰ ਰ੍ਰ ਲ੍ਰ ਲ਼੍ਰ ਵ੍ਰ ਸ਼੍ਰ ਸ੍ਰ ਹ੍ਰ ਖ਼੍ਰ ਗ਼੍ਰ ਜ਼੍ਰ ੜ੍ਰ ਫ਼੍ਰ", # Ra below conjuncts
    "ਕ੍ਵ ਖ੍ਵ ਗ੍ਵ ਘ੍ਵ ਙ੍ਵ ਚ੍ਵ ਛ੍ਵ ਜ੍ਵ ਝ੍ਵ ਞ੍ਵ ਟ੍ਵ ਠ੍ਵ ਡ੍ਵ ਢ੍ਵ ਣ੍ਵ ਤ੍ਵ ਥ੍ਵ ਦ੍ਵ ਧ੍ਵ ਨ੍ਵ ਪ੍ਵ ਫ੍ਵ ਬ੍ਵ ਭ੍ਵ ਮ੍ਵ ਯ੍ਵ ਰ੍ਵ ਲ੍ਵ ਲ਼੍ਵ ਵ੍ਵ ਸ਼੍ਵ ਸ੍ਵ ਹ੍ਵ ਖ਼੍ਵ ਗ਼੍ਵ ਜ਼੍ਵ ੜ੍ਵ ਫ਼੍ਵ" # Va below conjuncts
]
