[meta]
build_commit  = "e2ec9733b2d33a1fe3ba47ac23cfc52de558d876"

[input.features]
nukt = true
blwf = true
hist = true

[input]
script = "guru"
comparison_mode = "full"
text = [
    "ਕ੍ਚ ਖ੍ਚ ਗ੍ਚ ਘ੍ਚ ਙ੍ਚ ਚ੍ਚ ਛ੍ਚ ਜ੍ਚ ਝ੍ਚ ਞ੍ਚ ਟ੍ਚ ਠ੍ਚ ਡ੍ਚ ਢ੍ਚ ਣ੍ਚ ਤ੍ਚ ਥ੍ਚ ਦ੍ਚ ਧ੍ਚ ਨ੍ਚ ਪ੍ਚ ਫ੍ਚ ਬ੍ਚ ਭ੍ਚ ਮ੍ਚ ਯ੍ਚ ਰ੍ਚ ਲ੍ਚ ਲ਼੍ਚ ਵ੍ਚ ਸ਼੍ਚ ਸ੍ਚ ਹ੍ਚ ਖ਼੍ਚ ਗ਼੍ਚ ਜ਼੍ਚ ੜ੍ਚ ਫ਼੍ਚ", # Ha below conjuncts
    "ਕ੍ਟ ਖ੍ਟ ਗ੍ਟ ਘ੍ਟ ਙ੍ਟ ਚ੍ਟ ਛ੍ਟ ਜ੍ਟ ਝ੍ਟ ਞ੍ਟ ਟ੍ਟ ਠ੍ਟ ਡ੍ਟ ਢ੍ਟ ਣ੍ਟ ਤ੍ਟ ਥ੍ਟ ਦ੍ਟ ਧ੍ਟ ਨ੍ਟ ਪ੍ਟ ਫ੍ਟ ਬ੍ਟ ਭ੍ਟ ਮ੍ਟ ਯ੍ਟ ਰ੍ਟ ਲ੍ਟ ਲ਼੍ਟ ਵ੍ਟ ਸ਼੍ਟ ਸ੍ਟ ਹ੍ਟ ਖ਼੍ਟ ਗ਼੍ਟ ਜ਼੍ਟ ੜ੍ਟ ਫ਼੍ਟ", # Ra below conjuncts
    "ਕ੍ਤ ਖ੍ਤ ਗ੍ਤ ਘ੍ਤ ਙ੍ਤ ਚ੍ਤ ਛ੍ਤ ਜ੍ਤ ਝ੍ਤ ਞ੍ਤ ਟ੍ਤ ਠ੍ਤ ਡ੍ਤ ਢ੍ਤ ਣ੍ਤ ਤ੍ਤ ਥ੍ਤ ਦ੍ਤ ਧ੍ਤ ਨ੍ਤ ਪ੍ਤ ਫ੍ਤ ਬ੍ਤ ਭ੍ਤ ਮ੍ਤ ਯ੍ਤ ਰ੍ਤ ਲ੍ਤ ਲ਼੍ਤ ਵ੍ਤ ਸ਼੍ਤ ਸ੍ਤ ਹ੍ਤ ਖ਼੍ਤ ਗ਼੍ਤ ਜ਼੍ਤ ੜ੍ਤ ਫ਼੍ਤ" # Va below conjuncts
]
