[meta]
build_commit  = "e2ec9733b2d33a1fe3ba47ac23cfc52de558d876"

[input.features]
locl = true

[input]
script = "guru"
comparison_mode = "full"
text = [
    "ਕ। ਕ॥ ਕ. ਕ, ਕ: ਕ; ਕ… ਕ! ਕ? ਕ* (ਕ ਕ) {ਕ ਕ} [ਕ ਕ] ‘ਕ ਕ’ “ਕ ਕ”" # Localised punctuation
]
