[meta]
build_commit  = ""

[input.features]
locl = true

[input]
script = "guru"
language = "dflt"
comparison_mode = "full"
text = [
    "ਕ। ਕ॥ ਕ. ਕ, ਕ: ਕ; ਕ… ਕ! ਕ? ਕ* (ਕ ਕ) {ਕ ਕ} [ਕ ਕ] ‘ਕ ਕ’ “ਕ ਕ”" # Localised punctuation
]
