[meta]
build_commit  = ""

[input.features]
nukt = true
pstf = true

[input]
script = "guru"
language = "dflt"
comparison_mode = "full"
text = [
    "ਕ੍ਯ ਖ੍ਯ ਗ੍ਯ ਘ੍ਯ ਙ੍ਯ ਚ੍ਯ ਛ੍ਯ ਜ੍ਯ ਝ੍ਯ ਞ੍ਯ ਟ੍ਯ ਠ੍ਯ ਡ੍ਯ ਢ੍ਯ ਣ੍ਯ ਤ੍ਯ ਥ੍ਯ ਦ੍ਯ ਧ੍ਯ ਨ੍ਯ ਪ੍ਯ ਫ੍ਯ ਬ੍ਯ ਭ੍ਯ ਮ੍ਯ ਯ੍ਯ ਰ੍ਯ ਲ੍ਯ ਲ਼੍ਯ ਵ੍ਯ ਸ਼੍ਯ ਸ੍ਯ ਹ੍ਯ ਖ਼੍ਯ ਗ਼੍ਯ ਜ਼੍ਯ ੜ੍ਯ ਫ਼੍ਯ" # Post-base form of Ya
]
