[meta]
build_commit = "812c1e0e53e9b77b822efd4b3e0ceb0809e55ba8"

[input]
script = "hebr"
language = "he"
direction = "rtl"  # NOTE: RTL writing system
comparison_mode = "full"
text = [
    "וֺ֒ יֹ֓ וֺ֘ יֹ֜ וֺ֞ יֹ֟ וֺ֡ יֹ֩ וֺ֯ יֹ", # Add kerning for holam after a wide cantillation sits on top of a narrow letter
    "וֶ֥וֶ יֵ֣רָ לָֽרָ זַ֑דֲ נֱ֤זִ גֳ֦קְ", # Cantillation goes down between two wide diacritic marks
    "וֶ֥אֳ יֵ֣עֲ וָ֤מֳ יָ֤אֱ וָ֥טֱ", # Cantillation goes down between a wide mark and any letter with a very wide mark
    "רָקִ֑יעַ מִקֶּ֑דֶם קַ֛יִן", # Cantillation goes down under the letter Qof
    "אֶ֛ף נָ֣ך צֵ֤ן", # Cantillation goes down before finalNun, finalKaf, finalPe
    "גֱ֦ק גֱ֦קְ יֵ֣ע יֵ֣עֲ זַ֑ד זַ֑דֲ",
]
