[meta]
build_commit  = ""

[input.features]
blwf = true

[input]
script = "knda"
language = "dflt"
comparison_mode = "full"
text = [
    "ಡ್ಕ ಡ್ಖ ಡ್ಗ ಡ್ಘ ಡ್ಙ ಡ್ಚ ಡ್ಛ ಡ್ಜ ಡ್ಝ ಡ್ಞ ಡ್ಟ ಡ್ಠ ಡ್ಡ ಡ್ಢ ಡ್ಣ ಡ್ತ ಡ್ಥ ಡ್ದ ಡ್ಧ ಡ್ನ ಡ್ಪ ಡ್ಫ ಡ್ಬ ಡ್ಭ ಡ್ಮ ಡ್ಯ ಡ್ರ ಡ್ಱ ಡ್ಲ ಡ್ಳ ಡ್ವ ಡ್ಶ ಡ್ಷ ಡ್ಸ ಡ್ಹ ಡ್ೞ" # Kannada below-base forms (vattus)
]
