[meta]
build_commit  = ""

[input.features]
blwf = true
blws = true
abvm = true
blwm = true

[input]
script = "knda"
language = "dflt"
comparison_mode = "full"
text = [
    "ಡ್ಕ್ರ ಡ್ಖ್ರ ಡ್ಗ್ರ ಡ್ಘ್ರ ಡ್ಙ್ರ ಡ್ಚ್ರ ಡ್ಛ್ರ ಡ್ಜ್ರ ಡ್ಝ್ರ ಡ್ಞ್ರ ಡ್ಟ್ರ ಡ್ಠ್ರ ಡ್ಡ್ರ ಡ್ಢ್ರ ಡ್ಣ್ರ ಡ್ತ್ರ ಡ್ಥ್ರ ಡ್ದ್ರ ಡ್ಧ್ರ ಡ್ನ್ರ ಡ್ಪ್ರ ಡ್ಫ್ರ ಡ್ಬ್ರ ಡ್ಭ್ರ ಡ್ಮ್ರ ಡ್ಯ್ರ ಡ್ಱ್ರ ಡ್ಲ್ರ ಡ್ಳ್ರ ಡ್ವ್ರ ಡ್ಶ್ರ ಡ್ಷ್ರ ಡ್ಸ್ರ ಡ್ಹ್ರ ಡ್ೞ್ರ", # Kannada 2nd tier Ra below-base form
    "ಕ್ಷ್ರ" # Kannada 2nd tier Ra- below-base form with KSsa
]
