[meta]
build_commit = "c571fb5be539a2386cfe3a994a2de3f01fd6b944"

[input.features]
kern = true

[input]
script = "hebr"
language = "he"
direction = "rtl"  # NOTE: RTL writing system
comparison_mode = "full"
text = [
    "וֶרֶ יֶוֶ וֶ֣רֶ יֶ֣וֶ", # Kerning between narrow letters with wide marks
    "לֹשׁ", # Kerning between lamed holam and shindot
    "אֹשׁ בֹשׁ דֹשׁ הֹשׁ קֹשׁ", # Kerning back holam in busy places
    "פֹשׁ שֹשׁ", # Kerning back holam in busy places
    "וֺ֒ יֹ֓ וֺ֘ יֹ֜ וֺ֞ יֹ֟ וֺ֡ יֹ֩ וֺ֯ יֹ", # Add kerning for holam after a wide cantillation sits on top of a narrow letter
    "וֶ֥וֶ יֵ֣רָ לָֽרָ זַ֑דֲ נֱ֤זִ גֳ֦קְ", # Cantillation goes down between two wide diacritic marks
    "וֶ֥אֳ יֵ֣עֲ וָ֤מֳ יָ֤אֱ וָ֥טֱ", # Cantillation goes down between a wide mark and any letter with a very wide mark
    "רָקִ֑יעַ מִקֶּ֑דֶם קַ֛יִן", # Cantillation goes down under the letter Qof
    "אֶ֛ף נָ֣ך צֵ֤ן", # Cantillation goes down before finalNun, finalKaf, finalPe
]