[meta]
build_commit = "b82064346c297d12cb3a2c6fa3674cf516f9e89d"

[input]
script = "khmr"
language = "dflt"
direction = "ltr"
comparison_mode = "full"
text = [
    # Consonants
    "ក ខ គ ឃ ង ច ឆ ជ ឈ ញ ដ ឋ ឌ ឍ ណ ត ថ ទ ធ ន ប ផ ព ភ ម យ រ ល វ ឝ ឞ ស ហ ឡ អ ឥ ឦ ឧ ឨ ឩ ឪ ឫ ឬ ឭ ឮ ឯ ឰ ឱ ឲ ឳ",
    "០ ១ ២ ៣ ៤ ៥ ៦ ៧ ៨ ៩ ៛ ។ ៕ ៖ ៗ ។ល។",

    # Consonants and Subconsonants
    "ក្ក ខ្ខ គ្គ ឃ្ឃ ង្ង ច្ច ឆ្ឆ ជ្ជ ឈ្ឈ ញ្ញ ដ្ដ ឋ្ឋ ឌ្ឌ ឍ្ឍ ណ្ណ ត្ត ថ្ថ ទ្ទ ធ្ធ ន្ន ប្ប ផ្ផ ព្ព ភ្ភ ម្ម យ្យ រ្រ ល្ល វ្វ ឝ្ឝ ឞ្ឞ ស្ស ហ្ហ ឡ អ្អ",

    # Marks and Symbols
    "◌ា ◌ិ ◌ី ◌ឹ ◌ឺ ◌ុ ◌ូ ◌ួ ើ ឿ ៀ",
    "េ ែ ៃ ោ ៅ ◌ំ ◌ះ ◌ៈ ◌៉ ◌៊",
    "◌់ ◌៌ ◌៍ ◌៎ ◌៏ ◌័ ៛ ។ ៕ ៖ ៗ ៘",
    "#᧠ ᧡ ᧢ ᧣ ᧤ ᧥ ᧦ ᧧ ᧨ ᧩ ᧪ ᧫ ᧬ ᧭ ᧮ ᧯ ᧰ ᧱ ᧲ ᧳ ᧴ ᧵ ᧶ ᧷ ᧸ ᧹ ᧺ ᧻ ᧼ ᧽ ᧾ ᧿",

    # Test Word
    "វិទ្យាសាស្ត្រ​អនុវត្តន៍",
    "បរិយាកាសចម្រើនសុខភាព​",
    "សេចក្ដី​ប្រឹងប្រែង​ក្នុង​ជីវិត",
    "ទឡ្ហីករណ៍​នៅ​ក្នុង​តុលាការ",
]
