[meta]
build_commit = "4f0e8cc1ccfea89bef3116501f5b310ae72e18ee"

[input]
script = "khmr"
language = "dflt"
direction = "ltr"
comparison_mode = "full"
text = [
    # Coeng Forms and Below-base Vowels
    "ក្កុ​ក្ខុ​ក្គុ​ក្ឃុ​ក្ងុ​ក្ចុ​ក្ឆុ​ក្ជុ​ក្ឈុ​ក្ញុ​ក្ដុ​ក្ឋុ​ក្ឌុ​ក្ឍុ​ក្ណុ​ក្តុ​ក្ថុ​ក្ទុ​ក្ធុ​ក្នុ​ក្បុ​ក្ផុ​ក្ពុ​ក្ភុ​ក្មុ​ក្យុ​ក្រុ​ក្លុ​ក្វុ​ក្ឝុ​ក្ឞុ​ក្សុ​ក្ហុ​ក្អុ​",
    "ស្កុ​ស្ខុ​ស្គុ​ស្ឃុ​ស្ងុ​ស្ចុ​ស្ឆុ​ស្ជុ​ស្ឈុ​ស្ញុ​ស្ដុ​ស្ឋុ​ស្ឌុ​ស្ឍុ​ស្ណុ​ស្តុ​ស្ថុ​ស្ទុ​ស្ធុ​ស្នុ​ស្បុ​ស្ផុ​ស្ពុ​ស្ភុ​ស្មុ​ស្យុ​ស្រុ​ស្លុ​ស្វុ​ស្ឝុ​ស្ឞុ​ស្សុ​ស្ហុ​ស្អុ​",
    "ណ្កុ​ណ្ខុ​ណ្គុ​ណ្ឃុ​ណ្ងុ​ណ្ចុ​ណ្ឆុ​ណ្ជុ​ណ្ឈុ​ណ្ញុ​ណ្ដុ​ណ្ឋុ​ណ្ឌុ​ណ្ឍុ​ណ្ណុ​ណ្តុ​ណ្ថុ​ណ្ទុ​ណ្ធុ​ណ្នុ​ណ្បុ​ណ្ផុ​ណ្ពុ​ណ្ភុ​ណ្មុ​ណ្យុ​ណ្រុ​ណ្លុ​ណ្វុ​ណ្ឝុ​ណ្ឞុ​ណ្សុ​ណ្ហុ​ណ្អុ​",
    "ក្កូ​ក្ខូ​ក្គូ​ក្ឃូ​ក្ងូ​ក្ចូ​ក្ឆូ​ក្ជូ​ក្ឈូ​ក្ញូ​ក្ដូ​ក្ឋូ​ក្ឌូ​ក្ឍូ​ក្ណូ​ក្តូ​ក្ថូ​ក្ទូ​ក្ធូ​ក្នូ​ក្បូ​ក្ផូ​ក្ពូ​ក្ភូ​ក្មូ​ក្យូ​ក្រូ​ក្លូ​ក្វូ​ក្ឝូ​ក្ឞូ​ក្សូ​ក្ហូ​ក្អូ​",
    "ស្កូ​ស្ខូ​ស្គូ​ស្ឃូ​ស្ងូ​ស្ចូ​ស្ឆូ​ស្ជូ​ស្ឈូ​ស្ញូ​ស្ដូ​ស្ឋូ​ស្ឌូ​ស្ឍូ​ស្ណូ​ស្តូ​ស្ថូ​ស្ទូ​ស្ធូ​ស្នូ​ស្បូ​ស្ផូ​ស្ពូ​ស្ភូ​ស្មូ​ស្យូ​ស្រូ​ស្លូ​ស្វូ​ស្ឝូ​ស្ឞូ​ស្សូ​ស្ហូ​ស្អូ​",
    "ណ្កូ​ណ្ខូ​ណ្គូ​ណ្ឃូ​ណ្ងូ​ណ្ចូ​ណ្ឆូ​ណ្ជូ​ណ្ឈូ​ណ្ញូ​ណ្ដូ​ណ្ឋូ​ណ្ឌូ​ណ្ឍូ​ណ្ណូ​ណ្តូ​ណ្ថូ​ណ្ទូ​ណ្ធូ​ណ្នូ​ណ្បូ​ណ្ផូ​ណ្ពូ​ណ្ភូ​ណ្មូ​ណ្យូ​ណ្រូ​ណ្លូ​ណ្វូ​ណ្ឝូ​ណ្ឞូ​ណ្សូ​ណ្ហូ​ណ្អូ​",
    "ក្កួ​ក្ខួ​ក្គួ​ក្ឃួ​ក្ងួ​ក្ចួ​ក្ឆួ​ក្ជួ​ក្ឈួ​ក្ញួ​ក្ដួ​ក្ឋួ​ក្ឌួ​ក្ឍួ​ក្ណួ​ក្តួ​ក្ថួ​ក្ទួ​ក្ធួ​ក្នួ​ក្បួ​ក្ផួ​ក្ពួ​ក្ភួ​ក្មួ​ក្យួ​ក្រួ​ក្លួ​ក្វួ​ក្ឝួ​ក្ឞួ​ក្សួ​ក្ហួ​ក្អួ​",
    "ស្កួ​ស្ខួ​ស្គួ​ស្ឃួ​ស្ងួ​ស្ចួ​ស្ឆួ​ស្ជួ​ស្ឈួ​ស្ញួ​ស្ដួ​ស្ឋួ​ស្ឌួ​ស្ឍួ​ស្ណួ​ស្តួ​ស្ថួ​ស្ទួ​ស្ធួ​ស្នួ​ស្បួ​ស្ផួ​ស្ពួ​ស្ភួ​ស្មួ​ស្យួ​ស្រួ​ស្លួ​ស្វួ​ស្ឝួ​ស្ឞួ​ស្សួ​ស្ហួ​ស្អួ​",
    "ណ្កួ​ណ្ខួ​ណ្គួ​ណ្ឃួ​ណ្ងួ​ណ្ចួ​ណ្ឆួ​ណ្ជួ​ណ្ឈួ​ណ្ញួ​ណ្ដួ​ណ្ឋួ​ណ្ឌួ​ណ្ឍួ​ណ្ណួ​ណ្តួ​ណ្ថួ​ណ្ទួ​ណ្ធួ​ណ្នួ​ណ្បួ​ណ្ផួ​ណ្ពួ​ណ្ភួ​ណ្មួ​ណ្យួ​ណ្រួ​ណ្លួ​ណ្វួ​ណ្ឝួ​ណ្ឞួ​ណ្សួ​ណ្ហួ​ណ្អួ​",

    # Coeng RO and Below-base Vowels
    "ក្រុក្រូក្រួ ខ្រុខ្រូខ្រួ គ្រុគ្រូគ្រួ ឃ្រុឃ្រូឃ្រួ ង្រុង្រូង្រួ ច្រុច្រូច្រួ ឆ្រុឆ្រូឆ្រួ ជ្រុជ្រូជ្រួ ឈ្រុឈ្រូឈ្រួ ញ្រុញ្រូញ្រួ",
    "ដ្រុដ្រូដ្រួ ឋ្រុឋ្រូឋ្រួ ឌ្រុឌ្រូឌ្រួ ឍ្រុឍ្រូឍ្រួ ណ្រុណ្រូណ្រួ ត្រុត្រូត្រួ ថ្រុថ្រូថ្រួ ទ្រុទ្រូទ្រួ ធ្រុធ្រូធ្រួ ន្រុន្រូន្រួ ប្រុប្រូប្រួ",
    "ផ្រុផ្រូផ្រួ ព្រុព្រូព្រួ ភ្រុភ្រូភ្រួ ម្រុម្រូម្រួ យ្រុយ្រូយ្រួ រ្រុរ្រូរ្រួ ល្រុល្រូល្រួ វ្រុវ្រូវ្រួ ឝ្រុឝ្រូឝ្រួ ឞ្រុឞ្រូឞ្រួ ស្រុស្រូស្រួ",
    "ហ្រុហ្រូហ្រួ ឡ្រុឡ្រូឡ្រួ អ្រុអ្រូអ្រួ ក្ក្រុក្ក្រូក្ក្រួ ន្ទ្រុន្ទ្រូន្ទ្រួ ចម្រៀង ចង្ក្រៀង ចង្ក្រឿង",
]
