[meta]
build_commit = "4f0e8cc1ccfea89bef3116501f5b310ae72e18ee"

[input]
script = "khmr"
direction = "ltr"
comparison_mode = "full"
text = [
    "ត្រីស័ព្ទ",
    "ស៊ី ស្ស៊ី ហ៊ី អ៊ី ស្ក៊ី ស្ស៊ី ហ្ក៊ី អ្ក៊ី ស៊ាំ ស្ស៊ាំ ហ៊ាំ អ៊ាំ ស្ក៊ាំ ស្ស៊ាំ ហ្ក៊ាំ អ្ក៊ាំ",

    "មូសិកទន្ត (ធ្មេញកណ្ដុរ)",
    "ង៉ី ញ៉ី ន៉ី ប៉ី ប្ប៉ី ម៉ី យ៉ី យ្យ៉ី រ៉ី ល៉ី វ៉ី ង៉ាំ ញ៉ាំ ន៉ាំ ប៉ាំ ប្ប៉ាំ ម៉ាំ យ៉ាំ យ្យ៉ាំ រ៉ាំ ល៉ាំ វ៉ាំ ង៉័ ញ៉័ ន៉័ ប៉័ ប្ប៉័ ម៉័ យ៉័ យ្យ៉័ រ៉័ ល៉័ វ៉័",
]
