[meta]
build_commit = "4f0e8cc1ccfea89bef3116501f5b310ae72e18ee"

[input]
script = "khmr"
language = "dflt"
direction = "ltr"
comparison_mode = "full"
text = [
    "កិ​ខិ​គិ​ឃិ​ងិ​ចិ​ឆិ​ជិ​ឈិ​ញិ​ដិ​ឋិ​ឌិ​ឍិ​ណិ​តិ​ថិ​ទិ​ធិ​និ​បិ​ផិ​ពិ​ភិ​មិ​យិ​រិ​លិ​វិ​ឝិ​ឞិ​សិ​ហិ​ឡិ​អិ​ ក្ឃិក្ឈិក្ឍិក្បិក្យិក្ឞិក្សិ",
    "កី​ខី​គី​ឃី​ងី​ចី​ឆី​ជី​ឈី​ញី​ដី​ឋី​ឌី​ឍី​ណី​តី​ថី​ទី​ធី​នី​បី​ផី​ពី​ភី​មី​យី​រី​លី​វី​ឝី​ឞី​សី​ហី​ឡី​អី​ ក្ឃីក្ឈីក្ឍីក្បីក្យីក្ឞីក្សី",
    "កឹ​ខឹ​គឹ​ឃឹ​ងឹ​ចឹ​ឆឹ​ជឹ​ឈឹ​ញឹ​ដឹ​ឋឹ​ឌឹ​ឍឹ​ណឹ​តឹ​ថឹ​ទឹ​ធឹ​នឹ​បឹ​ផឹ​ពឹ​ភឹ​មឹ​យឹ​រឹ​លឹ​វឹ​ឝឹ​ឞឹ​សឹ​ហឹ​ឡឹ​អឹ​ ក្ឃឹក្ឈឹក្ឍឹក្បឹក្យឹក្ឞឹក្សឹ",
    "កឺ​ខឺ​គឺ​ឃឺ​ងឺ​ចឺ​ឆឺ​ជឺ​ឈឺ​ញឺ​ដឺ​ឋឺ​ឌឺ​ឍឺ​ណឺ​តឺ​ថឺ​ទឺ​ធឺ​នឺ​បឺ​ផឺ​ពឺ​ភឺ​មឺ​យឺ​រឺ​លឺ​វឺ​ឝឺ​ឞឺ​សឺ​ហឺ​ឡឺ​អឺ​ ក្ឃឺក្ឈឺក្ឍឺក្បឺក្យឺក្ឞឺក្សឺ",
    "កុ​ខុ​គុ​ឃុ​ងុ​ចុ​ឆុ​ជុ​ឈុ​ញុ​ដុ​ឋុ​ឌុ​ឍុ​ណុ​តុ​ថុ​ទុ​ធុ​នុ​បុ​ផុ​ពុ​ភុ​មុ​យុ​រុ​លុ​វុ​ឝុ​ឞុ​សុ​ហុ​ឡុ​អុ​ ក្ឃុក្ឈុក្ឍុក្បុក្យុក្ឞុក្សុ",
    "កូ​ខូ​គូ​ឃូ​ងូ​ចូ​ឆូ​ជូ​ឈូ​ញូ​ដូ​ឋូ​ឌូ​ឍូ​ណូ​តូ​ថូ​ទូ​ធូ​នូ​បូ​ផូ​ពូ​ភូ​មូ​យូ​រូ​លូ​វូ​ឝូ​ឞូ​សូ​ហូ​ឡូ​អូ​ ក្ឃូក្ឈូក្ឍូក្បូក្យូក្ឞូក្សូ",
    "កួ​ខួ​គួ​ឃួ​ងួ​ចួ​ឆួ​ជួ​ឈួ​ញួ​ដួ​ឋួ​ឌួ​ឍួ​ណួ​តួ​ថួ​ទួ​ធួ​នួ​បួ​ផួ​ពួ​ភួ​មួ​យួ​រួ​លួ​វួ​ឝួ​ឞួ​សួ​ហួ​ឡួ​អួ​ ក្ឃួក្ឈួក្ឍួក្បួក្យួក្ឞួក្សួ",
    "កំ​ខំ​គំ​ឃំ​ងំ​ចំ​ឆំ​ជំ​ឈំ​ញំ​ដំ​ឋំ​ឌំ​ឍំ​ណំ​តំ​ថំ​ទំ​ធំ​នំ​បំ​ផំ​ពំ​ភំ​មំ​យំ​រំ​លំ​វំ​ឝំ​ឞំ​សំ​ហំ​ឡំ​អំ​ ក្ឃំក្ឈំក្ឍំក្បំក្យំក្ឞំក្សំ",
    "ក៉​ខ៉​គ៉​ឃ៉​ង៉​ច៉​ឆ៉​ជ៉​ឈ៉​ញ៉​ដ៉​ឋ៉​ឌ៉​ឍ៉​ណ៉​ត៉​ថ៉​ទ៉​ធ៉​ន៉​ប៉​ផ៉​ព៉​ភ៉​ម៉​យ៉​រ៉​ល៉​វ៉​ឝ៉​ឞ៉​ស៉​ហ៉​ឡ៉​អ៉​ ក្ឃ៉ក្ឈ៉ក្ឍ៉ក្ប៉ក្យ៉ក្ឞ៉ក្ស៉",
    "ក៊​ខ៊​គ៊​ឃ៊​ង៊​ច៊​ឆ៊​ជ៊​ឈ៊​ញ៊​ដ៊​ឋ៊​ឌ៊​ឍ៊​ណ៊​ត៊​ថ៊​ទ៊​ធ៊​ន៊​ប៊​ផ៊​ព៊​ភ៊​ម៊​យ៊​រ៊​ល៊​វ៊​ឝ៊​ឞ៊​ស៊​ហ៊​ឡ៊​អ៊​ ក្ឃ៊ក្ឈ៊ក្ឍ៊ក្ប៊ក្យ៊ក្ឞ៊ក្ស៊",
    "ក់​ខ់​គ់​ឃ់​ង់​ច់​ឆ់​ជ់​ឈ់​ញ់​ដ់​ឋ់​ឌ់​ឍ់​ណ់​ត់​ថ់​ទ់​ធ់​ន់​ប់​ផ់​ព់​ភ់​ម់​យ់​រ់​ល់​វ់​ឝ់​ឞ់​ស់​ហ់​ឡ់​អ់​ ក្ឃ់ក្ឈ់ក្ឍ់ក្ប់ក្យ់ក្ឞ់ក្ស់",
    "ក៌​ខ៌​គ៌​ឃ៌​ង៌​ច៌​ឆ៌​ជ៌​ឈ៌​ញ៌​ដ៌​ឋ៌​ឌ៌​ឍ៌​ណ៌​ត៌​ថ៌​ទ៌​ធ៌​ន៌​ប៌​ផ៌​ព៌​ភ៌​ម៌​យ៌​រ៌​ល៌​វ៌​ឝ៌​ឞ៌​ស៌​ហ៌​ឡ៌​អ៌​ ",
    "ក៍​ខ៍​គ៍​ឃ៍​ង៍​ច៍​ឆ៍​ជ៍​ឈ៍​ញ៍​ដ៍​ឋ៍​ឌ៍​ឍ៍​ណ៍​ត៍​ថ៍​ទ៍​ធ៍​ន៍​ប៍​ផ៍​ព៍​ភ៍​ម៍​យ៍​រ៍​ល៍​វ៍​ឝ៍​ឞ៍​ស៍​ហ៍​ឡ៍​អ៍​ ក្ឃ៍ក្ឈ៍ក្ឍ៍ក្ប៍ក្យ៍ក្ឞ៍ក្ស៍",
    "ក៎​ខ៎​គ៎​ឃ៎​ង៎​ច៎​ឆ៎​ជ៎​ឈ៎​ញ៎​ដ៎​ឋ៎​ឌ៎​ឍ៎​ណ៎​ត៎​ថ៎​ទ៎​ធ៎​ន៎​ប៎​ផ៎​ព៎​ភ៎​ម៎​យ៎​រ៎​ល៎​វ៎​ឝ៎​ឞ៎​ស៎​ហ៎​ឡ៎​អ៎​ ក្ឃ៎ក្ឈ៎ក្ឍ៎ក្ប៎ក្យ៎ក្ឞ៎ក្ស៎",
    "ក៏​ខ៏​គ៏​ឃ៏​ង៏​ច៏​ឆ៏​ជ៏​ឈ៏​ញ៏​ដ៏​ឋ៏​ឌ៏​ឍ៏​ណ៏​ត៏​ថ៏​ទ៏​ធ៏​ន៏​ប៏​ផ៏​ព៏​ភ៏​ម៏​យ៏​រ៏​ល៏​វ៏​ឝ៏​ឞ៏​ស៏​ហ៏​ឡ៏​អ៏​ ",
    "ក័​ខ័​គ័​ឃ័​ង័​ច័​ឆ័​ជ័​ឈ័​ញ័​ដ័​ឋ័​ឌ័​ឍ័​ណ័​ត័​ថ័​ទ័​ធ័​ន័​ប័​ផ័​ព័​ភ័​ម័​យ័​រ័​ល័​វ័​ឝ័​ឞ័​ស័​ហ័​ឡ័​អ័​ ក្ឃ៏ក្ឈ៏ក្ឍ៏ក្ប៏ក្យ៏ក្ឞ៏ក្ស៏",

    "កេ​ខេ​គេ​ឃេ​ងេ​ចេ​ឆេ​ជេ​ឈេ​ញេ​ដេ​ឋេ​ឌេ​ឍេ​ណេ​តេ​ថេ​ទេ​ធេ​នេ​បេ​ផេ​ពេ​ភេ​មេ​យេ​រេ​លេ​វេ​ឝេ​ឞេ​សេ​ហេ​ឡេ​អេ​",
    "កែ​ខែ​គែ​ឃែ​ងែ​ចែ​ឆែ​ជែ​ឈែ​ញែ​ដែ​ឋែ​ឌែ​ឍែ​ណែ​តែ​ថែ​ទែ​ធែ​នែ​បែ​ផែ​ពែ​ភែ​មែ​យែ​រែ​លែ​វែ​ឝែ​ឞែ​សែ​ហែ​ឡែ​អែ​",
    "កៃ​ខៃ​គៃ​ឃៃ​ងៃ​ចៃ​ឆៃ​ជៃ​ឈៃ​ញៃ​ដៃ​ឋៃ​ឌៃ​ឍៃ​ណៃ​តៃ​ថៃ​ទៃ​ធៃ​នៃ​បៃ​ផៃ​ពៃ​ភៃ​មៃ​យៃ​រៃ​លៃ​វៃ​ឝៃ​ឞៃ​សៃ​ហៃ​ឡៃ​អៃ​",
    "ក៉េ​ខ៉េ​គ៉េ​ឃ៉េ​ង៉េ​ច៉េ​ឆ៉េ​ជ៉េ​ឈ៉េ​ញ៉េ​ដ៉េ​ឋ៉េ​ឌ៉េ​ឍ៉េ​ណ៉េ​ត៉េ​ថ៉េ​ទ៉េ​ធ៉េ​ន៉េ​ប៉េ​ផ៉េ​ព៉េ​ភ៉េ​ម៉េ​យ៉េ​រ៉េ​ល៉េ​វ៉េ​ឝ៉េ​ឞ៉េ​ស៉េ​ហ៉េ​ឡ៉េ​អ៉េ​",
    "ក៉ែ​ខ៉ែ​គ៉ែ​ឃ៉ែ​ង៉ែ​ច៉ែ​ឆ៉ែ​ជ៉ែ​ឈ៉ែ​ញ៉ែ​ដ៉ែ​ឋ៉ែ​ឌ៉ែ​ឍ៉ែ​ណ៉ែ​ត៉ែ​ថ៉ែ​ទ៉ែ​ធ៉ែ​ន៉ែ​ប៉ែ​ផ៉ែ​ព៉ែ​ភ៉ែ​ម៉ែ​យ៉ែ​រ៉ែ​ល៉ែ​វ៉ែ​ឝ៉ែ​ឞ៉ែ​ស៉ែ​ហ៉ែ​ឡ៉ែ​អ៉ែ​",
    "ក៉ៃ​ខ៉ៃ​គ៉ៃ​ឃ៉ៃ​ង៉ៃ​ច៉ៃ​ឆ៉ៃ​ជ៉ៃ​ឈ៉ៃ​ញ៉ៃ​ដ៉ៃ​ឋ៉ៃ​ឌ៉ៃ​ឍ៉ៃ​ណ៉ៃ​ត៉ៃ​ថ៉ៃ​ទ៉ៃ​ធ៉ៃ​ន៉ៃ​ប៉ៃ​ផ៉ៃ​ព៉ៃ​ភ៉ៃ​ម៉ៃ​យ៉ៃ​រ៉ៃ​ល៉ៃ​វ៉ៃ​ឝ៉ៃ​ឞ៉ៃ​ស៉ៃ​ហ៉ៃ​ឡ៉ៃ​អ៉ៃ​",
]
