[meta]
build_commit = "ed195a4a252bb8d585c3c16a56133f7585e84894"

[input.features]
ccmp = true

[input]
script = "laoo"
language = "dflt"
direction = "ltr"
comparison_mode = "full"
text = [
    # Characters
    "ກຂຄຆງຈຉຊຌຍຎຏຐຑຒຓດຕຖທຘນບປຜຝພຟຠມຢຣລວຨຩສຫອຮຬໜໝໞໟ",

    "ເກເຂເຄເຆເງເຈເຉເຊເຌເຍເຎເຏເຐເຑເຒເຓເດເຕເຖເທເຘເນເບເປເຜເຝເພເຟເຠເມເຢເຣເລເວເຨເຩເສເຫເອເຮເຬເໜເໝເໞເໟ",
    "ແກແຂແຄແຆແງແຈແຉແຊແຌແຍແຎແຏແຐແຑແຒແຓແດແຕແຖແທແຘແນແບແປແຜແຝແພແຟແຠແມແຢແຣແລແວແຨແຩແສແຫແອແຮແຬແໜແໝແໞແໟ",
    "ໂກໂຂໂຄໂຆໂງໂຈໂຉໂຊໂຌໂຍໂຎໂຏໂຐໂຑໂຒໂຓໂດໂຕໂຖໂທໂຘໂນໂບໂປໂຜໂຝໂພໂຟໂຠໂມໂຢໂຣໂລໂວໂຨໂຩໂສໂຫໂອໂຮໂຬໂໜໂໝໂໞໂໟ",
    "ໃກໃຂໃຄໃຆໃງໃຈໃຉໃຊໃຌໃຍໃຎໃຏໃຐໃຑໃຒໃຓໃດໃຕໃຖໃທໃຘໃນໃບໃປໃຜໃຝໃພໃຟໃຠໃມໃຢໃຣໃລໃວໃຨໃຩໃສໃຫໃອໃຮໃຬໃໜໃໝໃໞໃໟ",
    "ໄກໄຂໄຄໄຆໄງໄຈໄຉໄຊໄຌໄຍໄຎໄຏໄຐໄຑໄຒໄຓໄດໄຕໄຖໄທໄຘໄນໄບໄປໄຜໄຝໄພໄຟໄຠໄມໄຢໄຣໄລໄວໄຨໄຩໄສໄຫໄອໄຮໄຬໄໜໄໝໄໞໄໟ",

    "ກະຂະຄະຆະງະຈະຉະຊະຌະຍະຎະຏະຐະຑະຒະຓະດະຕະຖະທະຘະນະບະປະຜະຝະພະຟະຠະມະຢະຣະລະວະຨະຩະສະຫະອະຮະຬະໜະໝະໞະໟະ",
    "ກາຂາຄາຆາງາຈາຉາຊາຌາຍາຎາຏາຐາຑາຒາຓາດາຕາຖາທາຘານາບາປາຜາຝາພາຟາຠາມາຢາຣາລາວາຨາຩາສາຫາອາຮາຬາໜາໝາໞາໟາ",
    "ກໍາຂໍາຄໍາຆໍາງໍາຈໍາຉໍາຊໍາຌໍາຍໍາຎໍາຏໍາຐໍາຑໍາຒໍາຓໍາດໍາຕໍາຖໍາທໍາຘໍານໍາບໍາປໍາຜໍາຝໍາພໍາຟໍາຠໍາມໍາຢໍາຣໍາລໍາວໍາຨໍາຩໍາສໍາຫໍາອໍາຮໍາຬໍາໜໍາໝໍາໞໍາໟໍາ",

    # Vowels
    "ອະ ອາ ອິ ອີ ອຶ ອື ອໍ ອຸ ອູ ອຼ ອ຺",
    "ອ່ ອ້ ອ໊ ອ໋ ອ໌ ອັ ອົ ໂອ ໄອ ໃອ ໆ ຯ",

    # Numbers
    "໐ ໑ ໒ ໓ ໔ ໕ ໖ ໗ ໘ ໙",
]
