[meta]
build_commit  = "e2766096416e641da5edff0ced5c1f8f9dcc0e5b"

[input.features]
liga = true

[input]
direction = "ltr"
comparison_mode = "glyphstream"
text = [ 
    "fb", # two glyph -> one glyph
    "ff",
    "fh",
    "fi",
    "fj",
    "fk",
    "fl",
    "ft",
    "rf",
    "rt",
    "tf",
    "tt",
    "ffb", # three glyph -> one glyph
    "ffh",
    "ffi",
    "ffj",
    "ffk",
    "ffl",
    "fft",
    "rff",
    "Google_logo google_logo Googlelogoligature googlelogoligature", # logo ligatures
    "Glogoligature", # `G` logo ligature
    "ologoligature", # `o` logo ligature
    "glogoligature", # `g` logo ligature
    "llogoligature", # `l` logo ligature
    "elogoligature", # `e` logo ligature
]