[meta]
build_commit  = ""

[input.features]
locl = true

# In non-NLD languages, these shouldn't shape into special Dutch forms.
[input]
script = "latn"
comparison_mode = "glyphstream"
text = [ 
    "ij",
    "IJ",
    "ĳ",
    "Ĳ",
    "íj",
    "ÍJ",
    "íj́",
    "ÍJ́",
    "ĳ́",
    "Ĳ́",
    "kijk, wíj eten een ijsje KIJK, WÍJ ETEN EEN IJSJE lijnbus rijbaan Bergeijk affijn ijzermans krijgen"
]
