[meta]
build_commit  = ""

[input.features]
locl = true
c2sc = true
smcp = true

[input]
script = "cyrl"
language = "bg"
direction = "ltr"
comparison_mode = "glyphstream"
text = [ 
    "АБВГЃҐДЕЀЁЖЗИЙЍҊКЌЛМНОПРСТУЎФХЧЦШЩЏЬЪЫЉЊЅЄЭІЇЈЋЮЯЂѢѪѲѴҒҔҖҘҚҜҞҠҢҤԤҨҪҬҮҰҲҴҶҸҺԦҼҾӀӁӃӅӇӉӋӍӐӒӔӖӘӚӜӞӠӢӤӦӨӪӬӮӰӲӴӶӸӺӼӾԐԒԚԜҌҎԨԮ",
    "абвгѓґдеѐёжзийѝҋкќлмнопрстуўфхчцшщџьъыљњѕєэіїјћюяђѣѫѳѵғҕҗҙқҝҟҡңҥԥҩҫҭүұҳҵҷҹһԧҽҿӏӂӄӆӈӊӌӎӑӓӕӗәӛӝӟӡӣӥӧөӫӭӯӱӳӵӷӹӻӽӿԑԓԛԝҍҏԩԯ",
]
