[meta]
build_commit = ""

[input.features]
c2sc = true
smcp = true

[input]
script = "cyrl"
language = "ba"
direction = "ltr"
comparison_mode = "glyphstream"
text = [ 
    "ДЛФҒҘҪ",
    "вгджзийѝклфптцшщьъюығҙҫгѓбдптш",
]
