[meta]
build_commit  = ""

[input.features]
locl = true

[input]
script = "cyrl"
language = "bg"
direction = "ltr"
comparison_mode = "glyphstream"
text = [ 
    "ДЛФвгджзийѝклфптцшщьъюы", # Bulgarian localized form in both Roman and Italic
]