[meta]

[input]
script = "mlym"
language = "dflt"
comparison_mode = "full"
text = [
    "ക ൿ ക്ക ക്ത ക്ട ക്ല ക്ഷ ങ്ക",
    "ഗ ഗ് ഗ്ഗ ഗ്ദ ഗ്മ ഗ്ന ഗ്ല",
    "ജ ജ് ജ്ജ ജ്ഞ ഞ്ജ ജൢ ജൣ",
    "ട ട്ട ട ട് ട്ട ടൢ ടൣ",
    "യ യ്യ",
    "ദ്ദ ഞ്ച",
    "കൂ",
    "ത ത് ത്ല",
    "മ്ല",
    "അവര്‍",
    "അവൻ്റെ",
]
