[meta]
build_commit  = "a37fb604492435b19b0c46eb484e637066dede62"

[input.features]
blwf = true
blwm = true

[input]
script = "orya"
language = "dflt"
comparison_mode = "full"
text = [
	"ଗ୍କ ଗ୍ଖ ଗ୍ଗ ଗ୍ଘ ଗ୍ଙ ଗ୍ଚ ଗ୍ଛ ଗ୍ଜ ଗ୍ଝ ଗ୍ଟ ଗ୍ଠ ଗ୍ଡ ଗ୍ଢ ଗ୍ଣ ଗ୍ତ ଗ୍ଥ ଗ୍ଦ କ୍ଧ କ୍ନ କ୍ପ କ୍ଫ ଗ୍ବ ଗ୍ଭ ଗ୍ମ ଗ୍ର କ୍ଲ ଘ୍ଳ ଗ୍ଶ ଗ୍ଷ ଗ୍ସ ଗ୍ହ ଗ୍କ୍ଷ" # Below-base consonant forms
]