[meta]
build_commit  = "a37fb604492435b19b0c46eb484e637066dede62"

[input.features]
abvs = true
abvm = true

[input]
script = "orya"
comparison_mode = "full"
text = [
	"ର୍ଖି", # iMatra-reph ligature
	"କି ର୍କି", # iMatra & iMatra-reph length alternates
	"କୈ ଖୈ" # aiLength mark alternates
]