[meta]
build_commit = ""

[input]
script = "ory2"
language = "dflt"
comparison_mode = "full"
text = [
    "ର୍କି ର୍ଖି ର୍ଗି ର୍ଘି ର୍ଙି ର୍ଚି ର୍ଛି ର୍ଜି ର୍ଝି ର୍ଞି ର୍ଟି ର୍ଠି ର୍ଡି ର୍ଢି ର୍ଣି ର୍ତି ର୍ଥି ର୍ଦି ର୍ଧି ର୍ନି ର୍ପି ର୍ଫି ର୍ବି ର୍ଭି ର୍ମି ର୍ଯି ର୍ରି ର୍ଲି ର୍ଳି ର୍ଵି ର୍ଶି ର୍ଷି ର୍ସି ର୍ହି ର୍ଡ଼ି ର୍ଢ଼ି ର୍ୟି ର୍ୱି ର୍କ୍କି ର୍କ୍ଟି ର୍କ୍ଠି ର୍କ୍ତି ର୍କ୍ଷ୍ନି ର୍କ୍ବି ର୍କ୍ଷ୍ମି ର୍କ୍ଳି ର୍କ୍ଶି ର୍କ୍ଷି ର୍କ୍ସି ର୍ଗ୍ଦି ର୍ଗ୍ଧି ର୍ଗ୍ନି ର୍ଗ୍ଲି ର୍ଗ୍ଳି ର୍ଘ୍ନି ର୍ଙ୍କି ର୍ଙ୍ଖି ର୍ଙ୍ଗି ର୍ଙ୍ଘି ର୍ଙ୍କ୍ତି ର୍ଙ୍କ୍ତ୍ରି ର୍ଙ୍କ୍ଷି ର୍ଚ୍ଚି ର୍ଚ୍ଛି ର୍ଜ୍ଜି ର୍ଜ୍ଝି ର୍ଜ୍ଞି ର୍ଜ୍ଜ୍ବି ର୍ଞ୍ଚି ର୍ଞ୍ଛି ର୍ଞ୍ଜି ର୍ଞ୍ଝି ର୍ଟ୍ଟି ର୍ଡ୍ଗି ର୍ଡ୍ଡି ର୍ଣ୍ଟି ର୍ଣ୍ଠି ର୍ଣ୍ଡି ର୍ଣ୍ଢି ର୍ଣ୍ଣି ର୍ଣ୍ବି ର୍ତ୍କି ର୍ତ୍ତି ର୍ତ୍ଥି ର୍ତ୍ନି ର୍ତ୍ସ୍ନି ର୍ତ୍ପି ର୍ତ୍ତ୍ବି ର୍ତ୍ବି ର୍ତ୍ମି ର୍ତ୍ସି ର୍ଦ୍ଗି ର୍ଦ୍ଘି ର୍ଦ୍ଦି ର୍ଦ୍ଧି ର୍ଦ୍ବି ର୍ଦ୍ଭି ର୍ଦ୍ମି ର୍ଧ୍ବି ର୍ଧ୍ଯି ର୍ଧ୍ୟି ର୍ନ୍ତି ର୍ନ୍ତ୍ରି ର୍ନ୍ଥି ର୍ନ୍ଦି ର୍ନ୍ଧି ର୍ନ୍ନି ର୍ନ୍ତ୍ବି ର୍ନ୍ଦ୍ବି ର୍ନ୍ବି ର୍ନ୍ଧ୍ଭି ର୍ନ୍ମି ର୍ନ୍ସି ର୍ପ୍ଟି ର୍ପ୍ତି ର୍ପ୍ନି ର୍ପ୍ପି ର୍ପ୍ଳି ର୍ପ୍ସି ର୍ଫ୍ଟି ର୍ବ୍ଘି ର୍ବ୍ଜି ର୍ବ୍ଦି ର୍ବ୍ଧି ର୍ମ୍ନି ର୍ମ୍ପି ର୍ମ୍ଫି ର୍ମ୍ବି ର୍ମ୍ଭି ର୍ମ୍ମି ର୍ଲ୍କି ର୍ଲ୍ଗି ର୍ଲ୍ଡି ର୍ଲ୍ପି ର୍ଲ୍ମି ର୍ଲ୍ଲି ର୍ଳ୍କି ର୍ଳ୍ପି ର୍ଳ୍ଫି ର୍ଳ୍ଭି ର୍ଶ୍ଚି ର୍ଶ୍ଛି ର୍ଶ୍ନି ର୍ଶ୍ଳି ର୍ଷ୍କି ର୍ଷ୍ଟି ର୍ଷ୍ଠି ର୍ଷ୍ଣି ର୍ଷ୍ପି ର୍ଷ୍ଫି ର୍ଷ୍ମି ର୍ସ୍କି ର୍ସ୍ଖି ର୍ସ୍ଟି ର୍ସ୍ତି ର୍ସ୍ଥି ର୍ସ୍ନି ର୍ସ୍ପି ର୍ସ୍ଫି ର୍ସ୍ବି ର୍ସ୍ମି ର୍ସ୍ତ୍ରି ର୍ହ୍ଣି ର୍ହ୍ନି ର୍ହ୍ବି ର୍ହ୍ଲି",
]
