[meta]
build_commit  = ""

[input.features]
abvs = true
abvm = true

[input]
script = "orya"
language = "dflt"
comparison_mode = "full"
text = [
	"ର୍ଖି", # iMatra-reph ligature
	"କି ର୍କି", # iMatra & iMatra-reph length alternates
	"କୈ ଖୈ" # aiLength mark alternates
]