[meta]
build_commit  = "a37fb604492435b19b0c46eb484e637066dede62"

[input.features]
rphf = true
abvm = true

[input]
script = "orya"
language = "dflt"
comparison_mode = "full"
text = [
	"ର୍କ ର୍ଖ ର୍ଗ ର୍ଘ ର୍ଙ ର୍ଚ ର୍ଛ ର୍ଜ ର୍ଝ ର୍ଞ ର୍ଟ ର୍ଠ ର୍ଡ ର୍ଢ ର୍ଣ ର୍ତ ର୍ଥ ର୍ଦ ର୍ଧ ର୍ନ ର୍ପ ର୍ଫ ର୍ବ ର୍ଭ ର୍ମ ର୍ଯ ର୍ର ର୍ଲ ର୍ଳ ର୍ଵ ର୍ଶ ର୍ଷ ର୍ସ ର୍ହ ର୍ଡ଼ ର୍ଢ଼ ର୍ୟ ର୍ୱ", # Reph positioning
	"ର୍କି ର୍ଖି ର୍ଗି ର୍ଘି ର୍ଙି ର୍ଚି ର୍ଛି ର୍ଜି ର୍ଝି ର୍ଞି ର୍ଟି ର୍ଠି ର୍ଡି ର୍ଢି ର୍ଣି ର୍ତି ର୍ଥି ର୍ଦି ର୍ଧି ର୍ନି ର୍ପି ର୍ଫି ର୍ବି ର୍ଭି ର୍ମି ର୍ଯି ର୍ରି ର୍ଲି ର୍ଳି ର୍ଵି ର୍ଶି ର୍ଷି ର୍ସି ର୍ହି ର୍ଡ଼ି ର୍ଢ଼ି ର୍ୟି ର୍ୱି" # iMatra-Reph ligatures
]