[meta]
build_commit = ""

[input]
script = "ory2"
language = "dflt"
comparison_mode = "full"
text = [
    "କ୍କା କ୍କି କ୍କୀ କ୍କୁ କ୍କୂ କ୍କେ କ୍କୈ କ୍କୋ କ୍କୌ କ୍କୖ କ୍କୗ କ୍କୢ କ୍କୣ କ୍କୃ କ୍କୄ",
    "କ୍ଟା କ୍ଟି କ୍ଟୀ କ୍ଟୁ କ୍ଟୂ କ୍ଟେ କ୍ଟୈ କ୍ଟୋ କ୍ଟୌ କ୍ଟୖ କ୍ଟୗ କ୍ଟୢ କ୍ଟୣ କ୍ଟୃ କ୍ଟୄ",
    "କ୍ଠା କ୍ଠି କ୍ଠୀ କ୍ଠୁ କ୍ଠୂ କ୍ଠେ କ୍ଠୈ କ୍ଠୋ କ୍ଠୌ କ୍ଠୖ କ୍ଠୗ କ୍ଠୢ କ୍ଠୣ କ୍ଠୃ କ୍ଠୄ",
    "କ୍ତା କ୍ତି କ୍ତୀ କ୍ତୁ କ୍ତୂ କ୍ତେ କ୍ତୈ କ୍ତୋ କ୍ତୌ କ୍ତୖ କ୍ତୗ କ୍ତୢ କ୍ତୣ କ୍ତୃ କ୍ତୄ",
    "କ୍ଷ୍ନା କ୍ଷ୍ନି କ୍ଷ୍ନୀ କ୍ଷ୍ନୁ କ୍ଷ୍ନୂ କ୍ଷ୍ନେ କ୍ଷ୍ନୈ କ୍ଷ୍ନୋ କ୍ଷ୍ନୌ କ୍ଷ୍ନୖ କ୍ଷ୍ନୗ କ୍ଷ୍ନୢ କ୍ଷ୍ନୣ କ୍ଷ୍ନୃ କ୍ଷ୍ନୄ",
    "କ୍ବା କ୍ବି କ୍ବୀ କ୍ବୁ କ୍ବୂ କ୍ବେ କ୍ବୈ କ୍ବୋ କ୍ବୌ କ୍ବୖ କ୍ବୗ କ୍ବୢ କ୍ବୣ କ୍ବୃ କ୍ବୄ",
    "କ୍ଷ୍ମା କ୍ଷ୍ମି କ୍ଷ୍ମୀ କ୍ଷ୍ମୁ କ୍ଷ୍ମୂ କ୍ଷ୍ମେ କ୍ଷ୍ମୈ କ୍ଷ୍ମୋ କ୍ଷ୍ମୌ କ୍ଷ୍ମୖ କ୍ଷ୍ମୗ କ୍ଷ୍ମୢ କ୍ଷ୍ମୣ କ୍ଷ୍ମୃ କ୍ଷ୍ମୄ",
    "କ୍ଳା କ୍ଳି କ୍ଳୀ କ୍ଳୁ କ୍ଳୂ କ୍ଳେ କ୍ଳୈ କ୍ଳୋ କ୍ଳୌ କ୍ଳୖ କ୍ଳୗ କ୍ଳୢ କ୍ଳୣ କ୍ଳୃ କ୍ଳୄ",
    "କ୍ଶା କ୍ଶି କ୍ଶୀ କ୍ଶୁ କ୍ଶୂ କ୍ଶେ କ୍ଶୈ କ୍ଶୋ କ୍ଶୌ କ୍ଶୖ କ୍ଶୗ କ୍ଶୢ କ୍ଶୣ କ୍ଶୃ କ୍ଶୄ",
    "କ୍ଷା କ୍ଷି କ୍ଷୀ କ୍ଷୁ କ୍ଷୂ କ୍ଷେ କ୍ଷୈ କ୍ଷୋ କ୍ଷୌ କ୍ଷୖ କ୍ଷୗ କ୍ଷୢ କ୍ଷୣ କ୍ଷୃ କ୍ଷୄ",
    "କ୍ସା କ୍ସି କ୍ସୀ କ୍ସୁ କ୍ସୂ କ୍ସେ କ୍ସୈ କ୍ସୋ କ୍ସୌ କ୍ସୖ କ୍ସୗ କ୍ସୢ କ୍ସୣ କ୍ସୃ କ୍ସୄ",
    "ଗ୍ଦା ଗ୍ଦି ଗ୍ଦୀ ଗ୍ଦୁ ଗ୍ଦୂ ଗ୍ଦେ ଗ୍ଦୈ ଗ୍ଦୋ ଗ୍ଦୌ ଗ୍ଦୖ ଗ୍ଦୗ ଗ୍ଦୢ ଗ୍ଦୣ ଗ୍ଦୃ ଗ୍ଦୄ",
    "ଗ୍ଧା ଗ୍ଧି ଗ୍ଧୀ ଗ୍ଧୁ ଗ୍ଧୂ ଗ୍ଧେ ଗ୍ଧୈ ଗ୍ଧୋ ଗ୍ଧୌ ଗ୍ଧୖ ଗ୍ଧୗ ଗ୍ଧୢ ଗ୍ଧୣ ଗ୍ଧୃ ଗ୍ଧୄ",
    "ଗ୍ନା ଗ୍ନି ଗ୍ନୀ ଗ୍ନୁ ଗ୍ନୂ ଗ୍ନେ ଗ୍ନୈ ଗ୍ନୋ ଗ୍ନୌ ଗ୍ନୖ ଗ୍ନୗ ଗ୍ନୢ ଗ୍ନୣ ଗ୍ନୃ ଗ୍ନୄ",
    "ଗ୍ଲା ଗ୍ଲି ଗ୍ଲୀ ଗ୍ଲୁ ଗ୍ଲୂ ଗ୍ଲେ ଗ୍ଲୈ ଗ୍ଲୋ ଗ୍ଲୌ ଗ୍ଲୖ ଗ୍ଲୗ ଗ୍ଲୢ ଗ୍ଲୣ ଗ୍ଲୃ ଗ୍ଲୄ",
    "ଗ୍ଳା ଗ୍ଳି ଗ୍ଳୀ ଗ୍ଳୁ ଗ୍ଳୂ ଗ୍ଳେ ଗ୍ଳୈ ଗ୍ଳୋ ଗ୍ଳୌ ଗ୍ଳୖ ଗ୍ଳୗ ଗ୍ଳୢ ଗ୍ଳୣ ଗ୍ଳୃ ଗ୍ଳୄ",
    "ଘ୍ନା ଘ୍ନି ଘ୍ନୀ ଘ୍ନୁ ଘ୍ନୂ ଘ୍ନେ ଘ୍ନୈ ଘ୍ନୋ ଘ୍ନୌ ଘ୍ନୖ ଘ୍ନୗ ଘ୍ନୢ ଘ୍ନୣ ଘ୍ନୃ ଘ୍ନୄ",
    "ଙ୍କା ଙ୍କି ଙ୍କୀ ଙ୍କୁ ଙ୍କୂ ଙ୍କେ ଙ୍କୈ ଙ୍କୋ ଙ୍କୌ ଙ୍କୖ ଙ୍କୗ ଙ୍କୢ ଙ୍କୣ ଙ୍କୃ ଙ୍କୄ",
    "ଙ୍ଖା ଙ୍ଖି ଙ୍ଖୀ ଙ୍ଖୁ ଙ୍ଖୂ ଙ୍ଖେ ଙ୍ଖୈ ଙ୍ଖୋ ଙ୍ଖୌ ଙ୍ଖୖ ଙ୍ଖୗ ଙ୍ଖୢ ଙ୍ଖୣ ଙ୍ଖୃ ଙ୍ଖୄ",
    "ଙ୍ଗା ଙ୍ଗି ଙ୍ଗୀ ଙ୍ଗୁ ଙ୍ଗୂ ଙ୍ଗେ ଙ୍ଗୈ ଙ୍ଗୋ ଙ୍ଗୌ ଙ୍ଗୖ ଙ୍ଗୗ ଙ୍ଗୢ ଙ୍ଗୣ ଙ୍ଗୃ ଙ୍ଗୄ",
    "ଙ୍ଘା ଙ୍ଘି ଙ୍ଘୀ ଙ୍ଘୁ ଙ୍ଘୂ ଙ୍ଘେ ଙ୍ଘୈ ଙ୍ଘୋ ଙ୍ଘୌ ଙ୍ଘୖ ଙ୍ଘୗ ଙ୍ଘୢ ଙ୍ଘୣ ଙ୍ଘୃ ଙ୍ଘୄ",
    "ଙ୍କ୍ତା ଙ୍କ୍ତି ଙ୍କ୍ତୀ ଙ୍କ୍ତୁ ଙ୍କ୍ତୂ ଙ୍କ୍ତେ ଙ୍କ୍ତୈ ଙ୍କ୍ତୋ ଙ୍କ୍ତୌ ଙ୍କ୍ତୖ ଙ୍କ୍ତୗ ଙ୍କ୍ତୢ ଙ୍କ୍ତୣ ଙ୍କ୍ତୃ ଙ୍କ୍ତୄ",
    "ଙ୍କ୍ତ୍ରା ଙ୍କ୍ତ୍ରି ଙ୍କ୍ତ୍ରୀ ଙ୍କ୍ତ୍ରୁ ଙ୍କ୍ତ୍ରୂ ଙ୍କ୍ତ୍ରେ ଙ୍କ୍ତ୍ରୈ ଙ୍କ୍ତ୍ରୋ ଙ୍କ୍ତ୍ରୌ ଙ୍କ୍ତ୍ରୖ ଙ୍କ୍ତ୍ରୗ ଙ୍କ୍ତ୍ରୢ ଙ୍କ୍ତ୍ରୣ ଙ୍କ୍ତ୍ରୃ ଙ୍କ୍ତ୍ରୄ",
    "ଙ୍କ୍ଷା ଙ୍କ୍ଷି ଙ୍କ୍ଷୀ ଙ୍କ୍ଷୁ ଙ୍କ୍ଷୂ ଙ୍କ୍ଷେ ଙ୍କ୍ଷୈ ଙ୍କ୍ଷୋ ଙ୍କ୍ଷୌ ଙ୍କ୍ଷୖ ଙ୍କ୍ଷୗ ଙ୍କ୍ଷୢ ଙ୍କ୍ଷୣ ଙ୍କ୍ଷୃ ଙ୍କ୍ଷୄ",
    "ଚ୍ଚା ଚ୍ଚି ଚ୍ଚୀ ଚ୍ଚୁ ଚ୍ଚୂ ଚ୍ଚେ ଚ୍ଚୈ ଚ୍ଚୋ ଚ୍ଚୌ ଚ୍ଚୖ ଚ୍ଚୗ ଚ୍ଚୢ ଚ୍ଚୣ ଚ୍ଚୃ ଚ୍ଚୄ",
    "ଚ୍ଛା ଚ୍ଛି ଚ୍ଛୀ ଚ୍ଛୁ ଚ୍ଛୂ ଚ୍ଛେ ଚ୍ଛୈ ଚ୍ଛୋ ଚ୍ଛୌ ଚ୍ଛୖ ଚ୍ଛୗ ଚ୍ଛୢ ଚ୍ଛୣ ଚ୍ଛୃ ଚ୍ଛୄ",
    "ଜ୍ଜା ଜ୍ଜି ଜ୍ଜୀ ଜ୍ଜୁ ଜ୍ଜୂ ଜ୍ଜେ ଜ୍ଜୈ ଜ୍ଜୋ ଜ୍ଜୌ ଜ୍ଜୖ ଜ୍ଜୗ ଜ୍ଜୢ ଜ୍ଜୣ ଜ୍ଜୃ ଜ୍ଜୄ",
    "ଜ୍ଝା ଜ୍ଝି ଜ୍ଝୀ ଜ୍ଝୁ ଜ୍ଝୂ ଜ୍ଝେ ଜ୍ଝୈ ଜ୍ଝୋ ଜ୍ଝୌ ଜ୍ଝୖ ଜ୍ଝୗ ଜ୍ଝୢ ଜ୍ଝୣ ଜ୍ଝୃ ଜ୍ଝୄ",
    "ଜ୍ଞା ଜ୍ଞି ଜ୍ଞୀ ଜ୍ଞୁ ଜ୍ଞୂ ଜ୍ଞେ ଜ୍ଞୈ ଜ୍ଞୋ ଜ୍ଞୌ ଜ୍ଞୖ ଜ୍ଞୗ ଜ୍ଞୢ ଜ୍ଞୣ ଜ୍ଞୃ ଜ୍ଞୄ",
    "ଜ୍ଜ୍ବା ଜ୍ଜ୍ବି ଜ୍ଜ୍ବୀ ଜ୍ଜ୍ବୁ ଜ୍ଜ୍ବୂ ଜ୍ଜ୍ବେ ଜ୍ଜ୍ବୈ ଜ୍ଜ୍ବୋ ଜ୍ଜ୍ବୌ ଜ୍ଜ୍ବୖ ଜ୍ଜ୍ବୗ ଜ୍ଜ୍ବୢ ଜ୍ଜ୍ବୣ ଜ୍ଜ୍ବୃ ଜ୍ଜ୍ବୄ",
    "ଞ୍ଚା ଞ୍ଚି ଞ୍ଚୀ ଞ୍ଚୁ ଞ୍ଚୂ ଞ୍ଚେ ଞ୍ଚୈ ଞ୍ଚୋ ଞ୍ଚୌ ଞ୍ଚୖ ଞ୍ଚୗ ଞ୍ଚୢ ଞ୍ଚୣ ଞ୍ଚୃ ଞ୍ଚୄ",
    "ଞ୍ଛା ଞ୍ଛି ଞ୍ଛୀ ଞ୍ଛୁ ଞ୍ଛୂ ଞ୍ଛେ ଞ୍ଛୈ ଞ୍ଛୋ ଞ୍ଛୌ ଞ୍ଛୖ ଞ୍ଛୗ ଞ୍ଛୢ ଞ୍ଛୣ ଞ୍ଛୃ ଞ୍ଛୄ",
    "ଞ୍ଜା ଞ୍ଜି ଞ୍ଜୀ ଞ୍ଜୁ ଞ୍ଜୂ ଞ୍ଜେ ଞ୍ଜୈ ଞ୍ଜୋ ଞ୍ଜୌ ଞ୍ଜୖ ଞ୍ଜୗ ଞ୍ଜୢ ଞ୍ଜୣ ଞ୍ଜୃ ଞ୍ଜୄ",
    "ଞ୍ଝା ଞ୍ଝି ଞ୍ଝୀ ଞ୍ଝୁ ଞ୍ଝୂ ଞ୍ଝେ ଞ୍ଝୈ ଞ୍ଝୋ ଞ୍ଝୌ ଞ୍ଝୖ ଞ୍ଝୗ ଞ୍ଝୢ ଞ୍ଝୣ ଞ୍ଝୃ ଞ୍ଝୄ",
    "ଟ୍ଟା ଟ୍ଟି ଟ୍ଟୀ ଟ୍ଟୁ ଟ୍ଟୂ ଟ୍ଟେ ଟ୍ଟୈ ଟ୍ଟୋ ଟ୍ଟୌ ଟ୍ଟୖ ଟ୍ଟୗ ଟ୍ଟୢ ଟ୍ଟୣ ଟ୍ଟୃ ଟ୍ଟୄ",
    "ଡ୍ଗା ଡ୍ଗି ଡ୍ଗୀ ଡ୍ଗୁ ଡ୍ଗୂ ଡ୍ଗେ ଡ୍ଗୈ ଡ୍ଗୋ ଡ୍ଗୌ ଡ୍ଗୖ ଡ୍ଗୗ ଡ୍ଗୢ ଡ୍ଗୣ ଡ୍ଗୃ ଡ୍ଗୄ",
    "ଡ୍ଡା ଡ୍ଡି ଡ୍ଡୀ ଡ୍ଡୁ ଡ୍ଡୂ ଡ୍ଡେ ଡ୍ଡୈ ଡ୍ଡୋ ଡ୍ଡୌ ଡ୍ଡୖ ଡ୍ଡୗ ଡ୍ଡୢ ଡ୍ଡୣ ଡ୍ଡୃ ଡ୍ଡୄ",
    "ଣ୍ଟା ଣ୍ଟି ଣ୍ଟୀ ଣ୍ଟୁ ଣ୍ଟୂ ଣ୍ଟେ ଣ୍ଟୈ ଣ୍ଟୋ ଣ୍ଟୌ ଣ୍ଟୖ ଣ୍ଟୗ ଣ୍ଟୢ ଣ୍ଟୣ ଣ୍ଟୃ ଣ୍ଟୄ",
    "ଣ୍ଠା ଣ୍ଠି ଣ୍ଠୀ ଣ୍ଠୁ ଣ୍ଠୂ ଣ୍ଠେ ଣ୍ଠୈ ଣ୍ଠୋ ଣ୍ଠୌ ଣ୍ଠୖ ଣ୍ଠୗ ଣ୍ଠୢ ଣ୍ଠୣ ଣ୍ଠୃ ଣ୍ଠୄ",
    "ଣ୍ଡା ଣ୍ଡି ଣ୍ଡୀ ଣ୍ଡୁ ଣ୍ଡୂ ଣ୍ଡେ ଣ୍ଡୈ ଣ୍ଡୋ ଣ୍ଡୌ ଣ୍ଡୖ ଣ୍ଡୗ ଣ୍ଡୢ ଣ୍ଡୣ ଣ୍ଡୃ ଣ୍ଡୄ",
    "ଣ୍ଢା ଣ୍ଢି ଣ୍ଢୀ ଣ୍ଢୁ ଣ୍ଢୂ ଣ୍ଢେ ଣ୍ଢୈ ଣ୍ଢୋ ଣ୍ଢୌ ଣ୍ଢୖ ଣ୍ଢୗ ଣ୍ଢୢ ଣ୍ଢୣ ଣ୍ଢୃ ଣ୍ଢୄ",
    "ଣ୍ଣା ଣ୍ଣି ଣ୍ଣୀ ଣ୍ଣୁ ଣ୍ଣୂ ଣ୍ଣେ ଣ୍ଣୈ ଣ୍ଣୋ ଣ୍ଣୌ ଣ୍ଣୖ ଣ୍ଣୗ ଣ୍ଣୢ ଣ୍ଣୣ ଣ୍ଣୃ ଣ୍ଣୄ",
    "ଣ୍ବା ଣ୍ବି ଣ୍ବୀ ଣ୍ବୁ ଣ୍ବୂ ଣ୍ବେ ଣ୍ବୈ ଣ୍ବୋ ଣ୍ବୌ ଣ୍ବୖ ଣ୍ବୗ ଣ୍ବୢ ଣ୍ବୣ ଣ୍ବୃ ଣ୍ବୄ",
    "ତ୍କା ତ୍କି ତ୍କୀ ତ୍କୁ ତ୍କୂ ତ୍କେ ତ୍କୈ ତ୍କୋ ତ୍କୌ ତ୍କୖ ତ୍କୗ ତ୍କୢ ତ୍କୣ ତ୍କୃ ତ୍କୄ",
    "ତ୍ତା ତ୍ତି ତ୍ତୀ ତ୍ତୁ ତ୍ତୂ ତ୍ତେ ତ୍ତୈ ତ୍ତୋ ତ୍ତୌ ତ୍ତୖ ତ୍ତୗ ତ୍ତୢ ତ୍ତୣ ତ୍ତୃ ତ୍ତୄ",
    "ତ୍ଥା ତ୍ଥି ତ୍ଥୀ ତ୍ଥୁ ତ୍ଥୂ ତ୍ଥେ ତ୍ଥୈ ତ୍ଥୋ ତ୍ଥୌ ତ୍ଥୖ ତ୍ଥୗ ତ୍ଥୢ ତ୍ଥୣ ତ୍ଥୃ ତ୍ଥୄ",
    "ତ୍ନା ତ୍ନି ତ୍ନୀ ତ୍ନୁ ତ୍ନୂ ତ୍ନେ ତ୍ନୈ ତ୍ନୋ ତ୍ନୌ ତ୍ନୖ ତ୍ନୗ ତ୍ନୢ ତ୍ନୣ ତ୍ନୃ ତ୍ନୄ",
    "ତ୍ସ୍ନା ତ୍ସ୍ନି ତ୍ସ୍ନୀ ତ୍ସ୍ନୁ ତ୍ସ୍ନୂ ତ୍ସ୍ନେ ତ୍ସ୍ନୈ ତ୍ସ୍ନୋ ତ୍ସ୍ନୌ ତ୍ସ୍ନୖ ତ୍ସ୍ନୗ ତ୍ସ୍ନୢ ତ୍ସ୍ନୣ ତ୍ସ୍ନୃ ତ୍ସ୍ନୄ",
    "ତ୍ପା ତ୍ପି ତ୍ପୀ ତ୍ପୁ ତ୍ପୂ ତ୍ପେ ତ୍ପୈ ତ୍ପୋ ତ୍ପୌ ତ୍ପୖ ତ୍ପୗ ତ୍ପୢ ତ୍ପୣ ତ୍ପୃ ତ୍ପୄ",
    "ତ୍ତ୍ବା ତ୍ତ୍ବି ତ୍ତ୍ବୀ ତ୍ତ୍ବୁ ତ୍ତ୍ବୂ ତ୍ତ୍ବେ ତ୍ତ୍ବୈ ତ୍ତ୍ବୋ ତ୍ତ୍ବୌ ତ୍ତ୍ବୖ ତ୍ତ୍ବୗ ତ୍ତ୍ବୢ ତ୍ତ୍ବୣ ତ୍ତ୍ବୃ ତ୍ତ୍ବୄ",
    "ତ୍ବା ତ୍ବି ତ୍ବୀ ତ୍ବୁ ତ୍ବୂ ତ୍ବେ ତ୍ବୈ ତ୍ବୋ ତ୍ବୌ ତ୍ବୖ ତ୍ବୗ ତ୍ବୢ ତ୍ବୣ ତ୍ବୃ ତ୍ବୄ",
    "ତ୍ମା ତ୍ମି ତ୍ମୀ ତ୍ମୁ ତ୍ମୂ ତ୍ମେ ତ୍ମୈ ତ୍ମୋ ତ୍ମୌ ତ୍ମୖ ତ୍ମୗ ତ୍ମୢ ତ୍ମୣ ତ୍ମୃ ତ୍ମୄ",
    "ତ୍ସା ତ୍ସି ତ୍ସୀ ତ୍ସୁ ତ୍ସୂ ତ୍ସେ ତ୍ସୈ ତ୍ସୋ ତ୍ସୌ ତ୍ସୖ ତ୍ସୗ ତ୍ସୢ ତ୍ସୣ ତ୍ସୃ ତ୍ସୄ",
    "ଦ୍ଗା ଦ୍ଗି ଦ୍ଗୀ ଦ୍ଗୁ ଦ୍ଗୂ ଦ୍ଗେ ଦ୍ଗୈ ଦ୍ଗୋ ଦ୍ଗୌ ଦ୍ଗୖ ଦ୍ଗୗ ଦ୍ଗୢ ଦ୍ଗୣ ଦ୍ଗୃ ଦ୍ଗୄ",
    "ଦ୍ଘା ଦ୍ଘି ଦ୍ଘୀ ଦ୍ଘୁ ଦ୍ଘୂ ଦ୍ଘେ ଦ୍ଘୈ ଦ୍ଘୋ ଦ୍ଘୌ ଦ୍ଘୖ ଦ୍ଘୗ ଦ୍ଘୢ ଦ୍ଘୣ ଦ୍ଘୃ ଦ୍ଘୄ",
    "ଦ୍ଦା ଦ୍ଦି ଦ୍ଦୀ ଦ୍ଦୁ ଦ୍ଦୂ ଦ୍ଦେ ଦ୍ଦୈ ଦ୍ଦୋ ଦ୍ଦୌ ଦ୍ଦୖ ଦ୍ଦୗ ଦ୍ଦୢ ଦ୍ଦୣ ଦ୍ଦୃ ଦ୍ଦୄ",
    "ଦ୍ଧା ଦ୍ଧି ଦ୍ଧୀ ଦ୍ଧୁ ଦ୍ଧୂ ଦ୍ଧେ ଦ୍ଧୈ ଦ୍ଧୋ ଦ୍ଧୌ ଦ୍ଧୖ ଦ୍ଧୗ ଦ୍ଧୢ ଦ୍ଧୣ ଦ୍ଧୃ ଦ୍ଧୄ",
    "ଦ୍ବା ଦ୍ବି ଦ୍ବୀ ଦ୍ବୁ ଦ୍ବୂ ଦ୍ବେ ଦ୍ବୈ ଦ୍ବୋ ଦ୍ବୌ ଦ୍ବୖ ଦ୍ବୗ ଦ୍ବୢ ଦ୍ବୣ ଦ୍ବୃ ଦ୍ବୄ",
    "ଦ୍ଭା ଦ୍ଭି ଦ୍ଭୀ ଦ୍ଭୁ ଦ୍ଭୂ ଦ୍ଭେ ଦ୍ଭୈ ଦ୍ଭୋ ଦ୍ଭୌ ଦ୍ଭୖ ଦ୍ଭୗ ଦ୍ଭୢ ଦ୍ଭୣ ଦ୍ଭୃ ଦ୍ଭୄ",
    "ଦ୍ମା ଦ୍ମି ଦ୍ମୀ ଦ୍ମୁ ଦ୍ମୂ ଦ୍ମେ ଦ୍ମୈ ଦ୍ମୋ ଦ୍ମୌ ଦ୍ମୖ ଦ୍ମୗ ଦ୍ମୢ ଦ୍ମୣ ଦ୍ମୃ ଦ୍ମୄ",
    "ଧ୍ବା ଧ୍ବି ଧ୍ବୀ ଧ୍ବୁ ଧ୍ବୂ ଧ୍ବେ ଧ୍ବୈ ଧ୍ବୋ ଧ୍ବୌ ଧ୍ବୖ ଧ୍ବୗ ଧ୍ବୢ ଧ୍ବୣ ଧ୍ବୃ ଧ୍ବୄ",
    "ଧ୍ଯା ଧ୍ଯି ଧ୍ଯୀ ଧ୍ଯୁ ଧ୍ଯୂ ଧ୍ଯେ ଧ୍ଯୈ ଧ୍ଯୋ ଧ୍ଯୌ ଧ୍ଯୖ ଧ୍ଯୗ ଧ୍ଯୢ ଧ୍ଯୣ ଧ୍ଯୃ ଧ୍ଯୄ",
    "ଧ୍ୟା ଧ୍ୟି ଧ୍ୟୀ ଧ୍ୟୁ ଧ୍ୟୂ ଧ୍ୟେ ଧ୍ୟୈ ଧ୍ୟୋ ଧ୍ୟୌ ଧ୍ୟୖ ଧ୍ୟୗ ଧ୍ୟୢ ଧ୍ୟୣ ଧ୍ୟୃ ଧ୍ୟୄ",
    "ନ୍ତା ନ୍ତି ନ୍ତୀ ନ୍ତୁ ନ୍ତୂ ନ୍ତେ ନ୍ତୈ ନ୍ତୋ ନ୍ତୌ ନ୍ତୖ ନ୍ତୗ ନ୍ତୢ ନ୍ତୣ ନ୍ତୃ ନ୍ତୄ",
    "ନ୍ତ୍ରା ନ୍ତ୍ରି ନ୍ତ୍ରୀ ନ୍ତ୍ରୁ ନ୍ତ୍ରୂ ନ୍ତ୍ରେ ନ୍ତ୍ରୈ ନ୍ତ୍ରୋ ନ୍ତ୍ରୌ ନ୍ତ୍ରୖ ନ୍ତ୍ରୗ ନ୍ତ୍ରୢ ନ୍ତ୍ରୣ ନ୍ତ୍ରୃ ନ୍ତ୍ରୄ",
    "ନ୍ଥା ନ୍ଥି ନ୍ଥୀ ନ୍ଥୁ ନ୍ଥୂ ନ୍ଥେ ନ୍ଥୈ ନ୍ଥୋ ନ୍ଥୌ ନ୍ଥୖ ନ୍ଥୗ ନ୍ଥୢ ନ୍ଥୣ ନ୍ଥୃ ନ୍ଥୄ",
    "ନ୍ଦା ନ୍ଦି ନ୍ଦୀ ନ୍ଦୁ ନ୍ଦୂ ନ୍ଦେ ନ୍ଦୈ ନ୍ଦୋ ନ୍ଦୌ ନ୍ଦୖ ନ୍ଦୗ ନ୍ଦୢ ନ୍ଦୣ ନ୍ଦୃ ନ୍ଦୄ",
    "ନ୍ଧା ନ୍ଧି ନ୍ଧୀ ନ୍ଧୁ ନ୍ଧୂ ନ୍ଧେ ନ୍ଧୈ ନ୍ଧୋ ନ୍ଧୌ ନ୍ଧୖ ନ୍ଧୗ ନ୍ଧୢ ନ୍ଧୣ ନ୍ଧୃ ନ୍ଧୄ",
    "ନ୍ନା ନ୍ନି ନ୍ନୀ ନ୍ନୁ ନ୍ନୂ ନ୍ନେ ନ୍ନୈ ନ୍ନୋ ନ୍ନୌ ନ୍ନୖ ନ୍ନୗ ନ୍ନୢ ନ୍ନୣ ନ୍ନୃ ନ୍ନୄ",
    "ନ୍ତ୍ବା ନ୍ତ୍ବି ନ୍ତ୍ବୀ ନ୍ତ୍ବୁ ନ୍ତ୍ବୂ ନ୍ତ୍ବେ ନ୍ତ୍ବୈ ନ୍ତ୍ବୋ ନ୍ତ୍ବୌ ନ୍ତ୍ବୖ ନ୍ତ୍ବୗ ନ୍ତ୍ବୢ ନ୍ତ୍ବୣ ନ୍ତ୍ବୃ ନ୍ତ୍ବୄ",
    "ନ୍ଦ୍ବା ନ୍ଦ୍ବି ନ୍ଦ୍ବୀ ନ୍ଦ୍ବୁ ନ୍ଦ୍ବୂ ନ୍ଦ୍ବେ ନ୍ଦ୍ବୈ ନ୍ଦ୍ବୋ ନ୍ଦ୍ବୌ ନ୍ଦ୍ବୖ ନ୍ଦ୍ବୗ ନ୍ଦ୍ବୢ ନ୍ଦ୍ବୣ ନ୍ଦ୍ବୃ ନ୍ଦ୍ବୄ",
    "ନ୍ବା ନ୍ବି ନ୍ବୀ ନ୍ବୁ ନ୍ବୂ ନ୍ବେ ନ୍ବୈ ନ୍ବୋ ନ୍ବୌ ନ୍ବୖ ନ୍ବୗ ନ୍ବୢ ନ୍ବୣ ନ୍ବୃ ନ୍ବୄ",
    "ନ୍ଧ୍ଭା ନ୍ଧ୍ଭି ନ୍ଧ୍ଭୀ ନ୍ଧ୍ଭୁ ନ୍ଧ୍ଭୂ ନ୍ଧ୍ଭେ ନ୍ଧ୍ଭୈ ନ୍ଧ୍ଭୋ ନ୍ଧ୍ଭୌ ନ୍ଧ୍ଭୖ ନ୍ଧ୍ଭୗ ନ୍ଧ୍ଭୢ ନ୍ଧ୍ଭୣ ନ୍ଧ୍ଭୃ ନ୍ଧ୍ଭୄ",
    "ନ୍ମା ନ୍ମି ନ୍ମୀ ନ୍ମୁ ନ୍ମୂ ନ୍ମେ ନ୍ମୈ ନ୍ମୋ ନ୍ମୌ ନ୍ମୖ ନ୍ମୗ ନ୍ମୢ ନ୍ମୣ ନ୍ମୃ ନ୍ମୄ",
    "ନ୍ସା ନ୍ସି ନ୍ସୀ ନ୍ସୁ ନ୍ସୂ ନ୍ସେ ନ୍ସୈ ନ୍ସୋ ନ୍ସୌ ନ୍ସୖ ନ୍ସୗ ନ୍ସୢ ନ୍ସୣ ନ୍ସୃ ନ୍ସୄ",
    "ପ୍ଟା ପ୍ଟି ପ୍ଟୀ ପ୍ଟୁ ପ୍ଟୂ ପ୍ଟେ ପ୍ଟୈ ପ୍ଟୋ ପ୍ଟୌ ପ୍ଟୖ ପ୍ଟୗ ପ୍ଟୢ ପ୍ଟୣ ପ୍ଟୃ ପ୍ଟୄ",
    "ପ୍ତା ପ୍ତି ପ୍ତୀ ପ୍ତୁ ପ୍ତୂ ପ୍ତେ ପ୍ତୈ ପ୍ତୋ ପ୍ତୌ ପ୍ତୖ ପ୍ତୗ ପ୍ତୢ ପ୍ତୣ ପ୍ତୃ ପ୍ତୄ",
    "ପ୍ନା ପ୍ନି ପ୍ନୀ ପ୍ନୁ ପ୍ନୂ ପ୍ନେ ପ୍ନୈ ପ୍ନୋ ପ୍ନୌ ପ୍ନୖ ପ୍ନୗ ପ୍ନୢ ପ୍ନୣ ପ୍ନୃ ପ୍ନୄ",
    "ପ୍ପା ପ୍ପି ପ୍ପୀ ପ୍ପୁ ପ୍ପୂ ପ୍ପେ ପ୍ପୈ ପ୍ପୋ ପ୍ପୌ ପ୍ପୖ ପ୍ପୗ ପ୍ପୢ ପ୍ପୣ ପ୍ପୃ ପ୍ପୄ",
    "ପ୍ଳା ପ୍ଳି ପ୍ଳୀ ପ୍ଳୁ ପ୍ଳୂ ପ୍ଳେ ପ୍ଳୈ ପ୍ଳୋ ପ୍ଳୌ ପ୍ଳୖ ପ୍ଳୗ ପ୍ଳୢ ପ୍ଳୣ ପ୍ଳୃ ପ୍ଳୄ",
    "ପ୍ସା ପ୍ସି ପ୍ସୀ ପ୍ସୁ ପ୍ସୂ ପ୍ସେ ପ୍ସୈ ପ୍ସୋ ପ୍ସୌ ପ୍ସୖ ପ୍ସୗ ପ୍ସୢ ପ୍ସୣ ପ୍ସୃ ପ୍ସୄ",
    "ଫ୍ଟା ଫ୍ଟି ଫ୍ଟୀ ଫ୍ଟୁ ଫ୍ଟୂ ଫ୍ଟେ ଫ୍ଟୈ ଫ୍ଟୋ ଫ୍ଟୌ ଫ୍ଟୖ ଫ୍ଟୗ ଫ୍ଟୢ ଫ୍ଟୣ ଫ୍ଟୃ ଫ୍ଟୄ",
    "ବ୍ଘା ବ୍ଘି ବ୍ଘୀ ବ୍ଘୁ ବ୍ଘୂ ବ୍ଘେ ବ୍ଘୈ ବ୍ଘୋ ବ୍ଘୌ ବ୍ଘୖ ବ୍ଘୗ ବ୍ଘୢ ବ୍ଘୣ ବ୍ଘୃ ବ୍ଘୄ",
    "ବ୍ଜା ବ୍ଜି ବ୍ଜୀ ବ୍ଜୁ ବ୍ଜୂ ବ୍ଜେ ବ୍ଜୈ ବ୍ଜୋ ବ୍ଜୌ ବ୍ଜୖ ବ୍ଜୗ ବ୍ଜୢ ବ୍ଜୣ ବ୍ଜୃ ବ୍ଜୄ",
    "ବ୍ଦା ବ୍ଦି ବ୍ଦୀ ବ୍ଦୁ ବ୍ଦୂ ବ୍ଦେ ବ୍ଦୈ ବ୍ଦୋ ବ୍ଦୌ ବ୍ଦୖ ବ୍ଦୗ ବ୍ଦୢ ବ୍ଦୣ ବ୍ଦୃ ବ୍ଦୄ",
    "ବ୍ଧା ବ୍ଧି ବ୍ଧୀ ବ୍ଧୁ ବ୍ଧୂ ବ୍ଧେ ବ୍ଧୈ ବ୍ଧୋ ବ୍ଧୌ ବ୍ଧୖ ବ୍ଧୗ ବ୍ଧୢ ବ୍ଧୣ ବ୍ଧୃ ବ୍ଧୄ",
    "ମ୍ନା ମ୍ନି ମ୍ନୀ ମ୍ନୁ ମ୍ନୂ ମ୍ନେ ମ୍ନୈ ମ୍ନୋ ମ୍ନୌ ମ୍ନୖ ମ୍ନୗ ମ୍ନୢ ମ୍ନୣ ମ୍ନୃ ମ୍ନୄ",
    "ମ୍ପା ମ୍ପି ମ୍ପୀ ମ୍ପୁ ମ୍ପୂ ମ୍ପେ ମ୍ପୈ ମ୍ପୋ ମ୍ପୌ ମ୍ପୖ ମ୍ପୗ ମ୍ପୢ ମ୍ପୣ ମ୍ପୃ ମ୍ପୄ",
    "ମ୍ଫା ମ୍ଫି ମ୍ଫୀ ମ୍ଫୁ ମ୍ଫୂ ମ୍ଫେ ମ୍ଫୈ ମ୍ଫୋ ମ୍ଫୌ ମ୍ଫୖ ମ୍ଫୗ ମ୍ଫୢ ମ୍ଫୣ ମ୍ଫୃ ମ୍ଫୄ",
    "ମ୍ବା ମ୍ବି ମ୍ବୀ ମ୍ବୁ ମ୍ବୂ ମ୍ବେ ମ୍ବୈ ମ୍ବୋ ମ୍ବୌ ମ୍ବୖ ମ୍ବୗ ମ୍ବୢ ମ୍ବୣ ମ୍ବୃ ମ୍ବୄ",
    "ମ୍ଭା ମ୍ଭି ମ୍ଭୀ ମ୍ଭୁ ମ୍ଭୂ ମ୍ଭେ ମ୍ଭୈ ମ୍ଭୋ ମ୍ଭୌ ମ୍ଭୖ ମ୍ଭୗ ମ୍ଭୢ ମ୍ଭୣ ମ୍ଭୃ ମ୍ଭୄ",
    "ମ୍ମା ମ୍ମି ମ୍ମୀ ମ୍ମୁ ମ୍ମୂ ମ୍ମେ ମ୍ମୈ ମ୍ମୋ ମ୍ମୌ ମ୍ମୖ ମ୍ମୗ ମ୍ମୢ ମ୍ମୣ ମ୍ମୃ ମ୍ମୄ",
    "ଲ୍କା ଲ୍କି ଲ୍କୀ ଲ୍କୁ ଲ୍କୂ ଲ୍କେ ଲ୍କୈ ଲ୍କୋ ଲ୍କୌ ଲ୍କୖ ଲ୍କୗ ଲ୍କୢ ଲ୍କୣ ଲ୍କୃ ଲ୍କୄ",
    "ଲ୍ଗା ଲ୍ଗି ଲ୍ଗୀ ଲ୍ଗୁ ଲ୍ଗୂ ଲ୍ଗେ ଲ୍ଗୈ ଲ୍ଗୋ ଲ୍ଗୌ ଲ୍ଗୖ ଲ୍ଗୗ ଲ୍ଗୢ ଲ୍ଗୣ ଲ୍ଗୃ ଲ୍ଗୄ",
    "ଲ୍ଡା ଲ୍ଡି ଲ୍ଡୀ ଲ୍ଡୁ ଲ୍ଡୂ ଲ୍ଡେ ଲ୍ଡୈ ଲ୍ଡୋ ଲ୍ଡୌ ଲ୍ଡୖ ଲ୍ଡୗ ଲ୍ଡୢ ଲ୍ଡୣ ଲ୍ଡୃ ଲ୍ଡୄ",
    "ଲ୍ପା ଲ୍ପି ଲ୍ପୀ ଲ୍ପୁ ଲ୍ପୂ ଲ୍ପେ ଲ୍ପୈ ଲ୍ପୋ ଲ୍ପୌ ଲ୍ପୖ ଲ୍ପୗ ଲ୍ପୢ ଲ୍ପୣ ଲ୍ପୃ ଲ୍ପୄ",
    "ଲ୍ମା ଲ୍ମି ଲ୍ମୀ ଲ୍ମୁ ଲ୍ମୂ ଲ୍ମେ ଲ୍ମୈ ଲ୍ମୋ ଲ୍ମୌ ଲ୍ମୖ ଲ୍ମୗ ଲ୍ମୢ ଲ୍ମୣ ଲ୍ମୃ ଲ୍ମୄ",
    "ଲ୍ଲା ଲ୍ଲି ଲ୍ଲୀ ଲ୍ଲୁ ଲ୍ଲୂ ଲ୍ଲେ ଲ୍ଲୈ ଲ୍ଲୋ ଲ୍ଲୌ ଲ୍ଲୖ ଲ୍ଲୗ ଲ୍ଲୢ ଲ୍ଲୣ ଲ୍ଲୃ ଲ୍ଲୄ",
    "ଳ୍କା ଳ୍କି ଳ୍କୀ ଳ୍କୁ ଳ୍କୂ ଳ୍କେ ଳ୍କୈ ଳ୍କୋ ଳ୍କୌ ଳ୍କୖ ଳ୍କୗ ଳ୍କୢ ଳ୍କୣ ଳ୍କୃ ଳ୍କୄ",
    "ଳ୍ପା ଳ୍ପି ଳ୍ପୀ ଳ୍ପୁ ଳ୍ପୂ ଳ୍ପେ ଳ୍ପୈ ଳ୍ପୋ ଳ୍ପୌ ଳ୍ପୖ ଳ୍ପୗ ଳ୍ପୢ ଳ୍ପୣ ଳ୍ପୃ ଳ୍ପୄ",
    "ଳ୍ଫା ଳ୍ଫି ଳ୍ଫୀ ଳ୍ଫୁ ଳ୍ଫୂ ଳ୍ଫେ ଳ୍ଫୈ ଳ୍ଫୋ ଳ୍ଫୌ ଳ୍ଫୖ ଳ୍ଫୗ ଳ୍ଫୢ ଳ୍ଫୣ ଳ୍ଫୃ ଳ୍ଫୄ",
    "ଳ୍ଭା ଳ୍ଭି ଳ୍ଭୀ ଳ୍ଭୁ ଳ୍ଭୂ ଳ୍ଭେ ଳ୍ଭୈ ଳ୍ଭୋ ଳ୍ଭୌ ଳ୍ଭୖ ଳ୍ଭୗ ଳ୍ଭୢ ଳ୍ଭୣ ଳ୍ଭୃ ଳ୍ଭୄ",
    "ଶ୍ଚା ଶ୍ଚି ଶ୍ଚୀ ଶ୍ଚୁ ଶ୍ଚୂ ଶ୍ଚେ ଶ୍ଚୈ ଶ୍ଚୋ ଶ୍ଚୌ ଶ୍ଚୖ ଶ୍ଚୗ ଶ୍ଚୢ ଶ୍ଚୣ ଶ୍ଚୃ ଶ୍ଚୄ",
    "ଶ୍ଛା ଶ୍ଛି ଶ୍ଛୀ ଶ୍ଛୁ ଶ୍ଛୂ ଶ୍ଛେ ଶ୍ଛୈ ଶ୍ଛୋ ଶ୍ଛୌ ଶ୍ଛୖ ଶ୍ଛୗ ଶ୍ଛୢ ଶ୍ଛୣ ଶ୍ଛୃ ଶ୍ଛୄ",
    "ଶ୍ନା ଶ୍ନି ଶ୍ନୀ ଶ୍ନୁ ଶ୍ନୂ ଶ୍ନେ ଶ୍ନୈ ଶ୍ନୋ ଶ୍ନୌ ଶ୍ନୖ ଶ୍ନୗ ଶ୍ନୢ ଶ୍ନୣ ଶ୍ନୃ ଶ୍ନୄ",
    "ଶ୍ଳା ଶ୍ଳି ଶ୍ଳୀ ଶ୍ଳୁ ଶ୍ଳୂ ଶ୍ଳେ ଶ୍ଳୈ ଶ୍ଳୋ ଶ୍ଳୌ ଶ୍ଳୖ ଶ୍ଳୗ ଶ୍ଳୢ ଶ୍ଳୣ ଶ୍ଳୃ ଶ୍ଳୄ",
    "ଷ୍କା ଷ୍କି ଷ୍କୀ ଷ୍କୁ ଷ୍କୂ ଷ୍କେ ଷ୍କୈ ଷ୍କୋ ଷ୍କୌ ଷ୍କୖ ଷ୍କୗ ଷ୍କୢ ଷ୍କୣ ଷ୍କୃ ଷ୍କୄ",
    "ଷ୍ଟା ଷ୍ଟି ଷ୍ଟୀ ଷ୍ଟୁ ଷ୍ଟୂ ଷ୍ଟେ ଷ୍ଟୈ ଷ୍ଟୋ ଷ୍ଟୌ ଷ୍ଟୖ ଷ୍ଟୗ ଷ୍ଟୢ ଷ୍ଟୣ ଷ୍ଟୃ ଷ୍ଟୄ",
    "ଷ୍ଠା ଷ୍ଠି ଷ୍ଠୀ ଷ୍ଠୁ ଷ୍ଠୂ ଷ୍ଠେ ଷ୍ଠୈ ଷ୍ଠୋ ଷ୍ଠୌ ଷ୍ଠୖ ଷ୍ଠୗ ଷ୍ଠୢ ଷ୍ଠୣ ଷ୍ଠୃ ଷ୍ଠୄ",
    "ଷ୍ଣା ଷ୍ଣି ଷ୍ଣୀ ଷ୍ଣୁ ଷ୍ଣୂ ଷ୍ଣେ ଷ୍ଣୈ ଷ୍ଣୋ ଷ୍ଣୌ ଷ୍ଣୖ ଷ୍ଣୗ ଷ୍ଣୢ ଷ୍ଣୣ ଷ୍ଣୃ ଷ୍ଣୄ",
    "ଷ୍ପା ଷ୍ପି ଷ୍ପୀ ଷ୍ପୁ ଷ୍ପୂ ଷ୍ପେ ଷ୍ପୈ ଷ୍ପୋ ଷ୍ପୌ ଷ୍ପୖ ଷ୍ପୗ ଷ୍ପୢ ଷ୍ପୣ ଷ୍ପୃ ଷ୍ପୄ",
    "ଷ୍ଫା ଷ୍ଫି ଷ୍ଫୀ ଷ୍ଫୁ ଷ୍ଫୂ ଷ୍ଫେ ଷ୍ଫୈ ଷ୍ଫୋ ଷ୍ଫୌ ଷ୍ଫୖ ଷ୍ଫୗ ଷ୍ଫୢ ଷ୍ଫୣ ଷ୍ଫୃ ଷ୍ଫୄ",
    "ଷ୍ମା ଷ୍ମି ଷ୍ମୀ ଷ୍ମୁ ଷ୍ମୂ ଷ୍ମେ ଷ୍ମୈ ଷ୍ମୋ ଷ୍ମୌ ଷ୍ମୖ ଷ୍ମୗ ଷ୍ମୢ ଷ୍ମୣ ଷ୍ମୃ ଷ୍ମୄ",
    "ସ୍କା ସ୍କି ସ୍କୀ ସ୍କୁ ସ୍କୂ ସ୍କେ ସ୍କୈ ସ୍କୋ ସ୍କୌ ସ୍କୖ ସ୍କୗ ସ୍କୢ ସ୍କୣ ସ୍କୃ ସ୍କୄ",
    "ସ୍ଖା ସ୍ଖି ସ୍ଖୀ ସ୍ଖୁ ସ୍ଖୂ ସ୍ଖେ ସ୍ଖୈ ସ୍ଖୋ ସ୍ଖୌ ସ୍ଖୖ ସ୍ଖୗ ସ୍ଖୢ ସ୍ଖୣ ସ୍ଖୃ ସ୍ଖୄ",
    "ସ୍ଟା ସ୍ଟି ସ୍ଟୀ ସ୍ଟୁ ସ୍ଟୂ ସ୍ଟେ ସ୍ଟୈ ସ୍ଟୋ ସ୍ଟୌ ସ୍ଟୖ ସ୍ଟୗ ସ୍ଟୢ ସ୍ଟୣ ସ୍ଟୃ ସ୍ଟୄ",
    "ସ୍ତା ସ୍ତି ସ୍ତୀ ସ୍ତୁ ସ୍ତୂ ସ୍ତେ ସ୍ତୈ ସ୍ତୋ ସ୍ତୌ ସ୍ତୖ ସ୍ତୗ ସ୍ତୢ ସ୍ତୣ ସ୍ତୃ ସ୍ତୄ",
    "ସ୍ଥା ସ୍ଥି ସ୍ଥୀ ସ୍ଥୁ ସ୍ଥୂ ସ୍ଥେ ସ୍ଥୈ ସ୍ଥୋ ସ୍ଥୌ ସ୍ଥୖ ସ୍ଥୗ ସ୍ଥୢ ସ୍ଥୣ ସ୍ଥୃ ସ୍ଥୄ",
    "ସ୍ନା ସ୍ନି ସ୍ନୀ ସ୍ନୁ ସ୍ନୂ ସ୍ନେ ସ୍ନୈ ସ୍ନୋ ସ୍ନୌ ସ୍ନୖ ସ୍ନୗ ସ୍ନୢ ସ୍ନୣ ସ୍ନୃ ସ୍ନୄ",
    "ସ୍ପା ସ୍ପି ସ୍ପୀ ସ୍ପୁ ସ୍ପୂ ସ୍ପେ ସ୍ପୈ ସ୍ପୋ ସ୍ପୌ ସ୍ପୖ ସ୍ପୗ ସ୍ପୢ ସ୍ପୣ ସ୍ପୃ ସ୍ପୄ",
    "ସ୍ଫା ସ୍ଫି ସ୍ଫୀ ସ୍ଫୁ ସ୍ଫୂ ସ୍ଫେ ସ୍ଫୈ ସ୍ଫୋ ସ୍ଫୌ ସ୍ଫୖ ସ୍ଫୗ ସ୍ଫୢ ସ୍ଫୣ ସ୍ଫୃ ସ୍ଫୄ",
    "ସ୍ବା ସ୍ବି ସ୍ବୀ ସ୍ବୁ ସ୍ବୂ ସ୍ବେ ସ୍ବୈ ସ୍ବୋ ସ୍ବୌ ସ୍ବୖ ସ୍ବୗ ସ୍ବୢ ସ୍ବୣ ସ୍ବୃ ସ୍ବୄ",
    "ସ୍ମା ସ୍ମି ସ୍ମୀ ସ୍ମୁ ସ୍ମୂ ସ୍ମେ ସ୍ମୈ ସ୍ମୋ ସ୍ମୌ ସ୍ମୖ ସ୍ମୗ ସ୍ମୢ ସ୍ମୣ ସ୍ମୃ ସ୍ମୄ",
    "ସ୍ତ୍ରା ସ୍ତ୍ରି ସ୍ତ୍ରୀ ସ୍ତ୍ରୁ ସ୍ତ୍ରୂ ସ୍ତ୍ରେ ସ୍ତ୍ରୈ ସ୍ତ୍ରୋ ସ୍ତ୍ରୌ ସ୍ତ୍ରୖ ସ୍ତ୍ରୗ ସ୍ତ୍ରୢ ସ୍ତ୍ରୣ ସ୍ତ୍ରୃ ସ୍ତ୍ରୄ",
    "ହ୍ଣା ହ୍ଣି ହ୍ଣୀ ହ୍ଣୁ ହ୍ଣୂ ହ୍ଣେ ହ୍ଣୈ ହ୍ଣୋ ହ୍ଣୌ ହ୍ଣୖ ହ୍ଣୗ ହ୍ଣୢ ହ୍ଣୣ ହ୍ଣୃ ହ୍ଣୄ",
    "ହ୍ନା ହ୍ନି ହ୍ନୀ ହ୍ନୁ ହ୍ନୂ ହ୍ନେ ହ୍ନୈ ହ୍ନୋ ହ୍ନୌ ହ୍ନୖ ହ୍ନୗ ହ୍ନୢ ହ୍ନୣ ହ୍ନୃ ହ୍ନୄ",
    "ହ୍ବା ହ୍ବି ହ୍ବୀ ହ୍ବୁ ହ୍ବୂ ହ୍ବେ ହ୍ବୈ ହ୍ବୋ ହ୍ବୌ ହ୍ବୖ ହ୍ବୗ ହ୍ବୢ ହ୍ବୣ ହ୍ବୃ ହ୍ବୄ",
    "ହ୍ଲା ହ୍ଲି ହ୍ଲୀ ହ୍ଲୁ ହ୍ଲୂ ହ୍ଲେ ହ୍ଲୈ ହ୍ଲୋ ହ୍ଲୌ ହ୍ଲୖ ହ୍ଲୗ ହ୍ଲୢ ହ୍ଲୣ ହ୍ଲୃ ହ୍ଲୄ",
]
