[meta]
build_commit = ""

[input]
script = "ory2"
language = "dflt"
comparison_mode = "full"
text = [
    "କି ଖି ଗି ଘି ଙି ଚି ଛି ଜି ଝି ଞି ଟି ଠି ଡି ଢି ଣି ତି ଥି ଦି ଧି ନି ପି ଫି ବି ଭି ମି ଯି ରି ଲି ଳି ଵି ଶି ଷି ସି ହି ଡ଼ି ଢ଼ି ୟି ୱି କ୍କି କ୍ଟି କ୍ଠି କ୍ତି କ୍ଷ୍ନି କ୍ବି କ୍ଷ୍ମି କ୍ଳି କ୍ଶି କ୍ଷି କ୍ସି ଗ୍ଦି ଗ୍ଧି ଗ୍ନି ଗ୍ଲି ଗ୍ଳି ଘ୍ନି ଙ୍କି ଙ୍ଖି ଙ୍ଗି ଙ୍ଘି ଙ୍କ୍ତି ଙ୍କ୍ତ୍ରି ଙ୍କ୍ଷି ଚ୍ଚି ଚ୍ଛି ଜ୍ଜି ଜ୍ଝି ଜ୍ଞି ଜ୍ଜ୍ବି ଞ୍ଚି ଞ୍ଛି ଞ୍ଜି ଞ୍ଝି ଟ୍ଟି ଡ୍ଗି ଡ୍ଡି ଣ୍ଟି ଣ୍ଠି ଣ୍ଡି ଣ୍ଢି ଣ୍ଣି ଣ୍ବି ତ୍କି ତ୍ତି ତ୍ଥି ତ୍ନି ତ୍ସ୍ନି ତ୍ପି ତ୍ତ୍ବି ତ୍ବି ତ୍ମି ତ୍ସି ଦ୍ଗି ଦ୍ଘି ଦ୍ଦି ଦ୍ଧି ଦ୍ବି ଦ୍ଭି ଦ୍ମି ଧ୍ବି ଧ୍ଯି ଧ୍ୟି ନ୍ତି ନ୍ତ୍ରି ନ୍ଥି ନ୍ଦି ନ୍ଧି ନ୍ନି ନ୍ତ୍ବି ନ୍ଦ୍ବି ନ୍ବି ନ୍ଧ୍ଭି ନ୍ମି ନ୍ସି ପ୍ଟି ପ୍ତି ପ୍ନି ପ୍ପି ପ୍ଳି ପ୍ସି ଫ୍ଟି ବ୍ଘି ବ୍ଜି ବ୍ଦି ବ୍ଧି ମ୍ନି ମ୍ପି ମ୍ଫି ମ୍ବି ମ୍ଭି ମ୍ମି ଲ୍କି ଲ୍ଗି ଲ୍ଡି ଲ୍ପି ଲ୍ମି ଲ୍ଲି ଳ୍କି ଳ୍ପି ଳ୍ଫି ଳ୍ଭି ଶ୍ଚି ଶ୍ଛି ଶ୍ନି ଶ୍ଳି ଷ୍କି ଷ୍ଟି ଷ୍ଠି ଷ୍ଣି ଷ୍ପି ଷ୍ଫି ଷ୍ମି ସ୍କି ସ୍ଖି ସ୍ଟି ସ୍ତି ସ୍ଥି ସ୍ନି ସ୍ପି ସ୍ଫି ସ୍ବି ସ୍ମି ସ୍ତ୍ରି ହ୍ଣି ହ୍ନି ହ୍ବି ହ୍ଲି",
]
