[meta]
build_commit  = ""

[input.features]
abvs = true

[input]
script = "sinh"
language = "dflt"
comparison_mode = "full"
text = [
	"කි ඛි ගි ඝි ඞි ඟි චි ඡි ජි ඣි ඤි ඥි ඦි ටි ඨි ඩි ඪි ණි ඬි ති ථි දි ධි නි ඳි පි ඵි බි භි මි ඹි යි රි ලි වි ශි ෂි සි හි ළි ෆි ක්‍ෂි ක්‍රි ඛ්‍රි ග්‍රි ඝ්‍රි ඞ්‍රි ඟ්‍රි ච්‍රි ඡ්‍රි ජ්‍රි ඣ්‍රි ඤ්‍රි ඥ්‍රි ඦ්‍රි ට්‍රි ඨ්‍රි ඩ්‍රි ඪ්‍රි ණ්‍රි ඬ්‍රි ත්‍රි ථ්‍රි ද්‍රි ධ්‍රි න්‍රි ඳ්‍රි ප්‍රි ඵ්‍රි බ්‍රි භ්‍රි ම්‍රි ඹ්‍රි ය්‍රි ල්‍රි ළ්‍රි ව්‍රි ශ්‍රි ෂ්‍රි ස්‍රි හ්‍රි ෆ්‍රි", # iMatra ligature
	"කී ඛී ගී ඝී ඞී ඟී චී ඡී ජී ඣී ඤී ඥී ඦී ටී ඨී ඩී ඪී ණී ඬී තී ථී දී ධී නී ඳී පී ඵී බී භී මී ඹී යී රී ලී වී ශී ෂී සී හී ළී ෆී ක්‍ෂී ක්‍රී ඛ්‍රී ග්‍රී ඝ්‍රී ඞ්‍රී ඟ්‍රී ච්‍රී ඡ්‍රී ජ්‍රී ඣ්‍රී ඤ්‍රී ඥ්‍රී ඦ්‍රී ට්‍රී ඨ්‍රී ඩ්‍රී ඪ්‍රී ණ්‍රී ඬ්‍රී ත්‍රී ථ්‍රී ද්‍රී ධ්‍රී න්‍රී ඳ්‍රී ප්‍රී ඵ්‍රී බ්‍රී භ්‍රී ම්‍රී ඹ්‍රී ය්‍රී ල්‍රී ළ්‍රී ව්‍රී ශ්‍රී ෂ්‍රී ස්‍රී හ්‍රී ෆ්‍රී" # iiMatra ligature
]