[meta]
build_commit  = "87f9230ee9b914f876f3c0274b6a9892b4eb2cc7"

[input.features]
akhn  = true
abvs = true
blws = true
psts = true

[input]
script = "sinh"
language = "dflt"
comparison_mode = "full"
text = [
	"ක්‍ ක්‍ ක්‍ ක්‍ෂු" # K_Ssa conjuncts and vowel ligs
]