[meta]
build_commit  = "87f9230ee9b914f876f3c0274b6a9892b4eb2cc7"

[input.features]
rphf = true
abvs = true

[input]
script = "sinh"
comparison_mode = "full"
text = [
	"ර්‍ක ර්‍ඛ ර්‍ග ර්‍ඝ ර්‍ඞ ර්‍ඟ ර්‍ච ර්‍ඡ ර්‍ජ ර්‍ඣ ර්‍ඤ ර්‍ඥ ර්‍ඦ ර්‍ට ර්‍ඨ ර්‍ඩ ර්‍ඪ ර්‍ණ ර්‍ඬ ර්‍ත ර්‍ථ ර්‍ද ර්‍ධ ර්‍න ර්‍ඳ ර්‍ප ර්‍ඵ ර්‍බ ර්‍භ ර්‍ම ර්‍ඹ ර්‍ය ර්‍ල ර්‍ව ර්‍ශ ර්‍ෂ ර්‍ස ර්‍හ ර්‍ළ ර්‍ෆ" # Reph positioning
]