[meta]
build_commit  = ""

[input.features]
c2sc = true
smcp = true

[input]
script = "DFLT"
language = "dflt"
direction = "ltr"
comparison_mode = "glyphstream"
text = [
    "AÁĂẮẶẰẲẴÂẤẬẦẨẪÄẠÀẢĀĄÅǺÃÆǼBCĆČÇĈĊDÐĎĐEÉĔĚÊẾỆỀỂỄËĖẸÈẺĒĘẼFGĞĜĢĠHĦĤIÍĬÎÏỊÌỈĪĮĨJĴKĶLĹĽĻŁMNŃŇŅŊÑOÓŎÔỐỘỒỔỖÖỌÒỎƠỚỢỜỞỠŐŌØǾÕŒPÞQRŔŘŖSŚŠŞŜȘTŦŤŢȚUÚŬÛÜỤÙỦƯỨỰỪỬỮŰŪŲŮŨVWẂŴẄẀXYÝŶŸỴỲỶỸZŹŽŻАБВГЃҐДЕЀЁЖЗИЙЍҊКЌЛМНОПРСТУЎФХЧЦШЩЏЬЪЫЉЊЅЄЭІЇЈЋЮЯЂѢѪѲѴҒҔҖҘҚҜҞҠҢҤԤҨҪҬҲҶҸҺԦԨԮҼҾӀӁӃӅӇӉӋӍӐӒӔӖӘӚӜӞӠӢӤӦӨӪӬӮӰӲӴӶӸӺӼӾԐԒԚԜҌҎΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΣΤΥΦΧΨΩΊΪΎΫΌΏΆΈΉϏἈἉἊἋἌἍἎἏᾺΆᾸᾹᾼᾈᾉᾊᾋᾌᾍᾎᾏἘἙἚἛἜἝῈΈἨἩἪἫἬἭἮἯῊΉῌᾘᾙᾚᾛᾜᾝᾞᾟἸἹἺἻἼἽἾἿῚΊῘῙὈὉὊὋὌὍῸΌῬὙὛὝὟῪΎῨῩὨὩὪὫὬὭὮὯῺΏῼᾨᾩᾪᾫᾬᾭᾮᾯ0123456789·̈̇̀́̋̂̌̆̊̃̄̉΄΅᾿᾽῾῍῝῎῞῏῟῭΅῁`´῀ҴҮҰ",
    "aáăắặằẳẵâấậầẩẫäạàảāąåǻãæǽbcćčçĉċdðďđeéĕěêếệềểễëėẹèẻēęẽfgğĝģġhħĥiíĭîïịìỉīįĩjĵkķlŀĺľļłmnńňņŋñoóŏôốộồổỗöọòỏơớợờởỡőōøǿõœpþqrŕřŗsśšşŝștŧťţțuúŭûüụùủưứựừửữűūųůũvwẃŵẅẁxyýŷÿỵỳỷỹzźžżабвгѓґдеѐёжзийѝҋкќлмнопрстуўфхчцшщџьъыљњѕєэіїјћюяђѣѫѳѵғҕҗҙқҝҟҡңҥԥҩҫҭҳҷҹһԧԩԯҽҿӏӂӄӆӈӊӌӎӑӓӕӗәӛӝӟӡӣӥӧөӫӭӯӱӳӵӷӹӻӽӿԑԓԛԝҍҏαβγδεζηθικλμνξοπρςστυφχψωίϊΐύϋΰόώάέήϗἀἁἂἃἄἅἆἇὰάᾶᾰᾱᾳᾲᾴᾀᾁᾂᾃᾄᾅᾆᾇᾷἐἑἒἓἔἕὲέἠἡἢἣἤἥἦἧὴήῆῃῂῄᾐᾑᾒᾓᾔᾕᾖᾗῇἰἱἲἳἴἵἶἷὶίῖῐῑῒΐῗὀὁὂὃὄὅὸόῤῥὐὑὒὓὔὕὖὗὺύῦῠῡῢΰῧὠὡὢὣὤὥὦὧὼώῶῳῲῴᾠᾡᾢᾣᾤᾥᾦᾧῷ0123456789·̈̇̀́̋̂̌̆̊̃̄̉΄΅᾿᾽῾῍῝῎῞῏῟῭΅῁`´῀ҵүұ", # all default smcp
    "ᾳᾲᾴᾀᾁᾂᾃᾄᾅᾆᾇᾷῃῂῄᾐᾑᾒᾓᾔᾕᾖᾗῇῳῲῴᾠᾡᾢᾣᾤᾥᾦᾧῷ", # .ad Greek glyphs
    "ffb ffh ffi ffj ffk ffl fft rff",  # ligature decompositions, three letter
    "fb ff fh fi fj fk fl ft rf rt tf tt", # ligature decompositions, two letter
]
