[meta]
build_commit  = ""

[input.features]
smcp = true

[input]
script = "DFLT"
language = "dflt"
direction = "ltr"
comparison_mode = "glyphstream"
text = [ 
    "aáăắặằẳẵâấậầẩẫäạàảāąåǻãæǽbcćčçĉċdðďđeéĕěêếệềểễëėẹèẻēęẽfgğĝģġhħĥiíĭîïịìỉīįĩjĵkķlĺľļłmnńňņŋñoóŏôốộồổỗöọòỏơớợờởỡőōøǿõœpþqrŕřŗsśšşŝștŧťţțuúŭûüụùủưứựừửữűūųůũvwẃŵẅẁxyýŷÿỵỳỷỹzźžżабвгѓґдеѐёжзийѝҋкќлмнопрстуўфхчцшщџьъыљњѕєэіїјћюяђѣѫѳѵғҕҗҙқҝҟҡңҥԥҩҫҭҳҷҹһԧԩԯҽҿӏӂӄӆӈӊӌӎӑӓӕӗәӛӝӟӡӣӥӧөӫӭӯӱӳӵӷӹӻӽӿԑԓԛԝҍҏαβγδεζηθικλμνξοπρςστυφχψωίϊΐύϋΰόώάέήϗἀἁἂἃἄἅἆἇὰάᾶᾰᾱᾳᾲᾴᾀᾁᾂᾃᾄᾅᾆᾇᾷἐἑἒἓἔἕὲέἠἡἢἣἤἥἦἧὴήῆῃῂῄᾐᾑᾒᾓᾔᾕᾖᾗῇἰἱἲἳἴἵἶἷὶίῖῐῑῒΐῗὀὁὂὃὄὅὸόῤῥὐὑὒὓὔὕὖὗὺύῦῠῡῢΰῧὠὡὢὣὤὥὦὧὼώῶῳῲῴᾠᾡᾢᾣᾤᾥᾦᾧῷ0123456789·̈̇̀́̋̂̌̆̊̃̄̉΄΅᾿᾽῾῍῝῎῞῏῟῭΅῁`´῀ҵүұ",
]
