[meta]
build_commit  = "b40faa74c37711ac399d71a677cc1c0229072da5"

[input.features]
c2sc = true
smcp = true

[input]
direction = "ltr"
comparison_mode = "glyphstream"
text = [
    "AÁĂẮẶẰẲẴÂẤẬẦẨẪÄẠÀẢĀĄÅǺÃÆǼBCĆČÇĈĊDÐĎĐEÉĔĚÊẾỆỀỂỄËĖẸÈẺĒĘẼFGĞĜĢĠHĦĤIÍĬÎÏỊÌỈĪĮĨJĴKĶLĿĹĽĻŁMNŃŇŅŊÑOÓŎÔỐỘỒỔỖÖỌÒỎƠỚỢỜỞỠŐŌØǾÕŒPÞQRŔŘŖSŚŠŞŜȘTŦŤŢȚUÚŬÛÜỤÙỦƯỨỰỪỬỮŰŪŲŮŨVWẂŴẄẀXYÝŶŸỴỲỶỸZŹŽŻ",
    "aáăắặằẳẵâấậầẩẫäạàảāąåǻãæǽbcćčçĉċdðďđeéĕěêếệềểễëėẹèẻēęẽfgğĝģġhħĥiíĭîïịìỉīįĩjĵkķlŀĺľļłmnńňņŋñoóŏôốộồổỗöọòỏơớợờởỡőōøǿõœpþqrŕřŗsśšşŝștŧťţțuúŭûüụùủưứựừửữűūųůũvwẃŵẅẁxyýŷÿỵỳỷỹzźžż",
    "АБВГЃҐДЕЀЁЖЗИЙЍҊКЌЛМНОПРСТУЎФХЧЦШЩЏЬЪЫЉЊЅЄЭІЇЈЋЮЯЂѢѪѲѴҒҔҖҘҚҜҞҠҢҤԤҨҪҬҲҶҸҺԦԨԮҼҾӀӁӃӅӇӉӋӍӐӒӔӖӘӚӜӞӠӢӤӦӨӪӬӮӰӲӴӶӸӺӼӾԐԒԚԜҌҎҴҮҰ",
    "абвгѓґдеѐёжзийѝҋкќлмнопрстуўфхчцшщџьъыљњѕєэіїјћюяђѣѫѳѵғҕҗҙқҝҟҡңҥԥҩҫҭҳҷҹһԧԩԯҽҿӏӂӄӆӈӊӌӎӑӓӕӗәӛӝӟӡӣӥӧөӫӭӯӱӳӵӷӹӻӽӿԑԓԛԝҍҏҵүұ",
    "ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΣΤΥΦΧΨΩΊΪΎΫΌΏΆΈΉϏἈἉἊἋἌἍἎἏᾺΆᾸᾹᾼᾈᾉᾊᾋᾌᾍᾎᾏἘἙἚἛἜἝῈΈἨἩἪἫἬἭἮἯῊΉῌᾘᾙᾚᾛᾜᾝᾞᾟἸἹἺἻἼἽἾἿῚΊῘῙὈὉὊὋὌὍῸΌῬὙὛὝὟῪΎῨῩὨὩὪὫὬὭὮὯῺΏῼᾨᾩᾪᾫᾬᾭᾮᾯ0123456789·̈̇̀́̋̂̌̆̊̃̄̉΄΅᾿᾽῾῍῝῎῞῏῟῭΅῁`´῀",
    "αβγδεζηθικλμνξοπρςστυφχψωίϊΐύϋΰόώάέήϗἀἁἂἃἄἅἆἇὰάᾶᾰᾱἐἑἒἓἔἕὲέἠἡἢἣἤἥἦἧὴήῆἰἱἲἳἴἵἶἷὶίῖῐῑῒΐῗὀὁὂὃὄὅὸόῤῥὐὑὒὓὔὕὖὗὺύῦῠῡῢΰῧὠὡὢὣὤὥὦὧὼώῶ0123456789·̈̇̀́̋̂̌̆̊̃̄̉΄΅᾿᾽῾῍῝῎῞῏῟῭΅῁`´῀",
    "ᾳᾲᾴᾀᾁᾂᾃᾄᾅᾆᾇᾷῃῂῄᾐᾑᾒᾓᾔᾕᾖᾗῇῳῲῴᾠᾡᾢᾣᾤᾥᾦᾧῷ", # .ad Greek glyphs
    "ffb ffh ffi ffj ffk ffl fft rff",  # ligature decompositions, three letter
    "fb ff fh fi fj fk fl ft rf rt tf tt", # ligature decompositions, two letter
]
