[meta]
build_commit  = "e2766096416e641da5edff0ced5c1f8f9dcc0e5b"

[input.features]
ss01 = true

[input]
script = "DFLT"
language = "dflt"
direction = "ltr"
comparison_mode = "glyphstream"
text = [ 
    "*", # replaced with number pad asterisk form
]