[meta]
build_commit  = ""

[input.features]
ss06 = true
smcp = true

[input]
script = "DFLT"
language = "dflt"
direction = "ltr"
comparison_mode = "glyphstream"
text = [ 
    "ᾳᾲᾴᾀᾁᾂᾃᾄᾅᾆᾇᾷῃῂῄᾐᾑᾒᾓᾔᾕᾖᾗῇῳῲῴᾠᾡᾢᾣᾤᾥᾦᾧῷίϊΐύϋΰόώάέήἀἁἂἃἄἅἆἇὰάᾶᾰᾱᾳᾲᾴᾀᾁᾂᾃᾄᾅᾆᾇᾷἐἑἒἓἔἕὲέἠἡἢἣἤἥἦἧὴήῆῃῂῄᾐᾑᾒᾓᾔᾕᾖᾗῇἰἱἲἳἴἵἶἷὶίῖῐῑῒΐῗὀὁὂὃὄὅὸόῤῥὐὑὒὓὔὕὖὗὺύῦῠῡῢΰῧὠὡὢὣὤὥὦὧὼώῶῳῲῴᾠᾡᾢᾣᾤᾥᾦᾧῷ", # Greek smcp 06 stylistic set
]


