[meta]
build_commit  = ""

[input.features]
ss08 = true
smcp = true

[input]
script = "DFLT"
language = "dflt"
direction = "ltr"
comparison_mode = "glyphstream"
text = [ 
    "aáăắặằẳẵâấậầẩẫäạàảāąåǻãæǽ",
]


