[meta]
build_commit  = "44c98803191588250d36978c8c702912ca431084"

[input.features]
ss08 = true

[input]
direction = "ltr"
comparison_mode = "glyphstream"
text = [ 
    "aáăắặằẳẵâấậầẩẫäạàảāąåǻãæǽ",
]


