[meta]
build_commit  = "6fa8f452339869d61bb9319b3c9f093044edd3a7"

[input.features]
akhn = true
abvs = true

[input]
script = "taml"
comparison_mode = "full"
text = [
    "ஙீ பீ யீ வீ", # Alternate iiMatra
    "ஜீ மீ றீ லீ ழீ ஷீ ஸீ ஹீ க்ஷீ", # iiMatra Ligatures
    "ஶ்ரீ" # ShRii Ligature (Sha + Virama/Pulli + Ra + iiMatra)
]
