[meta]
build_commit  = "a8924bb0bc05183c426b083a1cad0f49ef74f0fc"

[input.features]
blwf = true
blwm = true

[input]
script = "tel2"
language = "dflt"
comparison_mode = "full"
text = [
	"క్క క్ఖ క్గ క్ఘ క్ఙ క్చ క్ఛ క్జ క్ఝ క్ఞ క్ట క్ఠ క్డ క్ఢ క్ణ క్త క్థ క్ద క్ధ క్న క్ప క్ఫ క్బ క్భ క్మ క్య క్ర క్ఱ క్ల క్ళ క్ఴ క్వ క్శ క్స క్హ" # Below base consonants or 'vattus'
]