[meta]
build_commit  = "a8924bb0bc05183c426b083a1cad0f49ef74f0fc"

[input.features]
akhn = true
abvs = true
blwf = true
blws = true
blwm = true
dist = true

[input]
script = "telu"
language = "dflt"
comparison_mode = "full"
text = [
	"క్ష్ఖద ద్ఖ్ఖద ద్క్ఖద ద్ఖ్ఖైద" # Space after double vattus
]