[meta]
build_commit  = ""

[input.features]
akhn  = true
blwf = true
psts = true
haln = true
blwm = true

[input]
script = "tel2"
language = "dflt"
comparison_mode = "full"
text = [
	"క్ష్ క్ థ్ క్క్ ధ్క్ క్ఖ్ ధ్ఖ్"
]