[meta]
build_commit  = ""

[input.features]
akhn  = true
blwf = true
abvs = true
blws = true
psts = true
blwm = true

[input]
script = "tel2"
language = "dflt"
comparison_mode = "full"
text = [
	"క్ష జ్ఞ క్షా క్షి క్షీ క్షు క్షూ క్షే క్షై క్షో క్షౌ జ్ఞా జ్ఞి జ్ఞీ జ్ఞు జ్ఞూ జ్ఞే జ్ఞై జ్ఞో జ్ఞౌ"
]