[meta]
build_commit  = "a8924bb0bc05183c426b083a1cad0f49ef74f0fc"

[input.features]
abvs = true

[input]
script = "telu"
comparison_mode = "full"
text = [
	"కి ఖి గి ఘి ఙి చి జి ఝి ఞి టి ఠి డి ణి తి థి ని పి బి మి యి రి ఱి లి ళి ఴి వి శి షి సి హి", # iMatra ligatures
	"కీ ఖీ గీ ఘీ ఙీ చీ జీ ఝీ ఞీ టీ ఠీ డీ ణీ తీ థీ నీ పీ బీ మీ యీ రీ ఱీ లీ ళీ ఴీ వీ శీ షీ సీ హీ", # iiMatra ligatures
	"కె ఖె గె ఘె ఙె చె జే ఝె ఞె టె ఠె డె ణె తె థె నె పె బె మె యె రె ఱె లె ళె ఴె వె శె షె సె హె", # eMatra ligatures
	"కే ఖే గే ఘే ఙే చే జే ఝే ఞే టే ఠే డే ణే తే థే నే పే బే మే యే రే ఱే లే ళే ఴే వే శే షే సే హే", # eeMatra ligatures
	"కొ ఖొ గొ ఘొ ఙొ చొ జొ ఝొ ఞొ టొ ఠొ డొ ణొ తొ థొ నొ పొ బొ మొ యొ రొ ఱొ లొ ళొ ఴొ వొ శొ షొ సొ హొ", # oMatra ligatures
	"కో ఖో గో ఘో ఙో చో జో ఝో ఞో టో ఠో డో ణో తో థో నో పో బో మో యో రో ఱో లో ళో ఴో వో శో షో సో హో", # ooMatra ligatures
	"కౌ ఖౌ గౌ ఘౌ ఙౌ చౌ జౌ ఝౌ ఞౌ టౌ ఠౌ డౌ ణౌ తౌ థౌ దౌ నౌ పౌ బౌ మౌ యౌ రౌ ఱౌ లౌ ళౌ ఴౌ వౌ శౌ షౌ సౌ హౌ" # auMatra ligatures
]