[meta]
build_commit  = ""

[input.features]
akhn = true
blwf = true
abvs = true
blws = true
psts = true
blwm = true

[input]
script = "tel2"
language = "dflt"
comparison_mode = "full"
text = [
	"కా పా సా", # aaMatra ligatures
	"కు డు పు", # uMatra ligatures
	"కూ డూ పూ", # uuMatra ligatures
	"డ్క్రై డ్గ్రై క్ష్ర", # post-base Ra
	"గ్ర ఖ్ర ష్ర క్రు ఘ్ర ఱ్రు ఝ్ర ఘ్రో ఝ్రో", # vattu Ra variants
	"ష్ఖ ష్ఖై", # Alternate Ssa
	"ధ్ద ఢ్ద భ్ద ఛ్ద ఖ్ద ఝ్ద", # Alternate bases with smaller drop
	"క్షే క్షై" # Use alternate Ssa vattu when ka-ligatures in use
]