[meta]
build_commit  = "a8924bb0bc05183c426b083a1cad0f49ef74f0fc"

[input.features]
blwf = true
abvs = true
blws = true
blwm = true

[input]
script = "telu"
comparison_mode = "full"
text = [
	"క్త్ర", # Ta-Ra below-base ligature
	"ప్ఖై ల్గై", # vattu-lengthMatra ligatures
	"కై గై" # short, alternate lengthMark 
]