[meta]
build_commit  = ""

[input.features]
akhn = true
abvs = true
blwf = true
blws = true
blwm = true
dist = true

[input]
script = "tel2"
language = "dflt"
comparison_mode = "full"
text = [
	"క్ష్ఖద ద్ఖ్ఖద ద్క్ఖద ద్ఖ్ఖైద" # Space after double vattus
]