[meta]
build_commit  = ""

[input.features]
akhn = true
blwf = true
blws = true
blwm = true
dist = true

[input]
script = "tel2"
language = "dflt"
comparison_mode = "full"
text = [
	"ద్ఖ్ఖ ద్క్ఖ ద్ర్ఖ క్ష్ఖ ద్త్ర్ఖ" # Space after double vattus
]