[meta]
build_commit  = "a8924bb0bc05183c426b083a1cad0f49ef74f0fc"

[input.features]

[input]
script = "tel2"
language = "dflt"
comparison_mode = "full"
text = [
	"త్క్ఝత ల్య్హల క్ఖ్హక ఠ్ల్హక క్ష్లక"
]