[meta]
build_commit  = "f4d2bd5f344b5cbe633b90b3c92678fb47a9ec5f"

[input]
script = "thai"
direction = "ltr"
text = [ 
    "กถภฤฤๅฦฦๅฎฎฺฏฏฺญญูฌณ",
    "ขฃชซคฅศดตทฑนมฒฆธร",
    "จวงฐฐูฉลสบปษยหผฝฟพฬฬิ",
    "อฮ๐๑๒๓๔๕๖๗๘๙",
    "กถภฤฤๅฦฦๅฎฏญฌณขฃชซ",
    "คฅศดตทฑนมฒฆธรจวงฐฉล",
    "สบปษยหผฝฟพฬอฮ",
    "๐๑๒๓๔๕๖๗๘๙",
    "อะอาอิอีอึอืปิปีปึปื",
    "อุอูอฺฎุฎูฎฺ",
    "อ่อ้อ๊อ๋อ็อ์อ๎ป่ป้ป๊ป๋ป็ป์ป๎",
    "๏๛ๆฯ๚",
    "ะกะขะฃะคะฅะฆะงะจะฉะชะซะฌะญะฎะฏะฐะฑะฒะณะดะตะถะทะ",
    "ะธะนะบะปะผะฝะพะฟะภะมะยะระฤะละฦะวะศะษะสะหะฬะอะฮะ",
    "ากาขาฃาคาฅาฆางาจาฉาชาซาฌาญาฎาฏาฐาฑาฒาณาดาตาถาทา",
    "าธานาบาปาผาฝาพาฟาภามายาราฤาลาฦาวาศาษาสาหาฬาอาฮา",
    "เกเขเฃเคเฅเฆเงเจเฉเชเซเฌเญเฎเฏเฐเฑเฒเณเดเตเถเทเ",
    "เธเนเบเปเผเฝเพเฟเภเมเยเรเฤเลเฦเวเศเษเสเหเฬเอเฮเ",
    "แกแขแฃแคแฅแฆแงแจแฉแชแซแฌแญแฎแฏแฐแฑแฒแณแดแตแถแทแ",
    "แธแนแบแปแผแฝแพแฟแภแมแยแรแฤแลแฦแวแศแษแสแหแฬแอแฮแ ",
    "โกโขโฃโคโฅโฆโงโจโฉโชโซโฌโญโฎโฏโฐโฑโฒโณโดโตโถโทโ",
    "โธโนโบโปโผโฝโพโฟโภโมโยโรโฤโลโฦโวโศโษโสโหโฬโอโฮโ",
    "ไกไขไฃไคไฅไฆไงไจไฉไชไซไฌไญไฎไฏไฐไฑไฒไณไดไตไถไทไ",
    "ไธไนไบไปไผไฝไพไฟไภไมไยไรไฤไลไฦไวไศไษไสไหไฬไอไฮไ",
    "ใกใขใฃใคใฅใฆใงใจใฉใชใซใฌใญใฎใฏใฐใฑใฒใณใดใตใถใทใ",
    "ใธในใบใปใผใฝใพใฟใภใมใยใรใฤใลใฦใวใศใษใสใหใฬใอใฮใ",
]
