[meta]
build_commit  = ""

[input]
script = "thai"
direction = "ltr"
comparison_mode = "glyphstream"
text = [
    "ก่ข่ฃ่ค่ฅ่ฆ่ง่จ่ฉ่ช่ซ่ฌ่ญ่ฎ่ฏ่ฐ่ฑ่ฒ่ณ่ด่ต่ถ่ท่ธ่น่บ่ป่ผ่ฝ่พ่ฟ่ภ่ม่ย่ร่ฤ่ล่ฦ่ว่ศ่ษ่ส่ห่ฬ่อ่ฮ่",
    "ก้ข้ฃ้ค้ฅ้ฆ้ง้จ้ฉ้ช้ซ้ฌ้ญ้ฎ้ฏ้ฐ้ฑ้ฒ้ณ้ด้ต้ถ้ท้ธ้น้บ้ป้ผ้ฝ้พ้ฟ้ภ้ม้ย้ร้ฤ้ล้ฦ้ว้ศ้ษ้ส้ห้ฬ้อ้ฮ้",
    "ก๊ข๊ฃ๊ค๊ฅ๊ฆ๊ง๊จ๊ฉ๊ช๊ซ๊ฌ๊ญ๊ฎ๊ฏ๊ฐ๊ฑ๊ฒ๊ณ๊ด๊ต๊ถ๊ท๊ธ๊น๊บ๊ป๊ผ๊ฝ๊พ๊ฟ๊ภ๊ม๊ย๊ร๊ฤ๊ล๊ฦ๊ว๊ศ๊ษ๊ส๊ห๊ฬ๊อ๊ฮ๊",
    "ก๋ข๋ฃ๋ค๋ฅ๋ฆ๋ง๋จ๋ฉ๋ช๋ซ๋ฌ๋ญ๋ฎ๋ฏ๋ฐ๋ฑ๋ฒ๋ณ๋ด๋ต๋ถ๋ท๋ธ๋น๋บ๋ป๋ผ๋ฝ๋พ๋ฟ๋ภ๋ม๋ย๋ร๋ฤ๋ล๋ฦ๋ว๋ศ๋ษ๋ส๋ห๋ฬ๋อ๋ฮ๋",
    "ก์ข์ฃ์ค์ฅ์ฆ์ง์จ์ฉ์ช์ซ์ฌ์ญ์ฎ์ฏ์ฐ์ฑ์ฒ์ณ์ด์ต์ถ์ท์ธ์น์บ์ป์ผ์ฝ์พ์ฟ์ภ์ม์ย์ร์ฤ์ล์ฦ์ว์ศ์ษ์ส์ห์ฬ์อ์ฮ์",
    "ก็ข็ฃ็ค็ฅ็ฆ็ง็จ็ฉ็ช็ซ็ฌ็ญ็ฎ็ฏ็ฐ็ฑ็ฒ็ณ็ด็ต็ถ็ท็ธ็น็บ็ป็ผ็ฝ็พ็ฟ็ภ็ม็ย็ร็ฤ็ล็ฦ็ว็ศ็ษ็ส็ห็ฬ็อ็ฮ็",
    "กัขัฃัคัฅัฆังัจัฉัชัซัฌัญัฎัฏัฐัฑัฒัณัดัตัถัทัธันับัปัผัฝัพัฟัภัมัยัรัฤัลัฦัวัศัษัสัหัฬัอัฮั",
    "กั่ขั่ฃั่คั่ฅั่ฆั่งั่จั่ฉั่ชั่ซั่ฌั่ญั่ฎั่ฏั่ฐั่ฑั่ฒั่ณั่ดั่ตั่ถั่ทั่ธั่นั่บั่ปั่ผั่ฝั่พั่ฟั่ภั่มั่ยั่รั่ฤั่ลั่ฦั่วั่ศั่ษั่สั่หั่ฬั่อั่ฮั่",
    "กั้ขั้ฃั้คั้ฅั้ฆั้งั้จั้ฉั้ชั้ซั้ฌั้ญั้ฎั้ฏั้ฐั้ฑั้ฒั้ณั้ดั้ตั้ถั้ทั้ธั้นั้บั้ปั้ผั้ฝั้พั้ฟั้ภั้มั้ยั้รั้ฤั้ลั้ฦั้วั้ศั้ษั้สั้หั้ฬั้อั้ฮั้",
    "กั๊ขั๊ฃั๊คั๊ฅั๊ฆั๊งั๊จั๊ฉั๊ชั๊ซั๊ฌั๊ญั๊ฎั๊ฏั๊ฐั๊ฑั๊ฒั๊ณั๊ดั๊ตั๊ถั๊ทั๊ธั๊นั๊บั๊ปั๊ผั๊ฝั๊พั๊ฟั๊ภั๊มั๊ยั๊รั๊ฤั๊ลั๊ฦั๊วั๊ศั๊ษั๊สั๊หั๊ฬั๊อั๊ฮั๊",
    "กั๋ขั๋ฃั๋คั๋ฅั๋ฆั๋งั๋จั๋ฉั๋ชั๋ซั๋ฌั๋ญั๋ฎั๋ฏั๋ฐั๋ฑั๋ฒั๋ณั๋ดั๋ตั๋ถั๋ทั๋ธั๋นั๋บั๋ปั๋ผั๋ฝั๋พั๋ฟั๋ภั๋มั๋ยั๋รั๋ฤั๋ลั๋ฦั๋วั๋ศั๋ษั๋สั๋หั๋ฬั๋อั๋ฮั๋",
    "กำขำฃำคำฅำฆำงำจำฉำชำซำฌำญำฎำฏำฐำฑำฒำณำดำตำถำทำ",
    "ธำนำบำปำผำฝำพำฟำภำมำยำรำฤำลำฦำวำศำษำสำหำฬำอำฮำ",
    "ก่ำข่ำฃ่ำค่ำฅ่ำฆ่ำง่ำจ่ำฉ่ำช่ำซ่ำฌ่ำญ่ำฎ่ำฏ่ำฐ่ำฑ่ำฒ่ำณ่ำด่ำต่ำถ่ำท่ำ",
    "ธ่ำน่ำบ่ำป่ำผ่ำฝ่ำพ่ำฟ่ำภ่ำม่ำย่ำร่ำฤ่ำล่ำฦ่ำว่ำศ่ำษ่ำส่ำห่ำฬ่ำอ่ำฮ่ำ",
    "ก้ำข้ำฃ้ำค้ำฅ้ำฆ้ำง้ำจ้ำฉ้ำช้ำซ้ำฌ้ำญ้ำฎ้ำฏ้ำฐ้ำฑ้ำฒ้ำณ้ำด้ำต้ำถ้ำท้ำ",
    "ธ้ำน้ำบ้ำป้ำผ้ำฝ้ำพ้ำฟ้ำภ้ำม้ำย้ำร้ำฤ้ำล้ำฦ้ำว้ำศ้ำษ้ำส้ำห้ำฬ้ำอ้ำฮ้ำ",
    "ก๊ำข๊ำฃ๊ำค๊ำฅ๊ำฆ๊ำง๊ำจ๊ำฉ๊ำช๊ำซ๊ำฌ๊ำญ๊ำฎ๊ำฏ๊ำฐ๊ำฑ๊ำฒ๊ำณ๊ำด๊ำต๊ำถ๊ำท๊ำ",
    "ธ๊ำน๊ำบ๊ำป๊ำผ๊ำฝ๊ำพ๊ำฟ๊ำภ๊ำม๊ำย๊ำร๊ำฤ๊ำล๊ำฦ๊ำว๊ำศ๊ำษ๊ำส๊ำห๊ำฬ๊ำอ๊ำฮ๊ำ",
    "ก๋ำข๋ำฃ๋ำค๋ำฅ๋ำฆ๋ำง๋ำจ๋ำฉ๋ำช๋ำซ๋ำฌ๋ำญ๋ำฎ๋ำฏ๋ำฐ๋ำฑ๋ำฒ๋ำณ๋ำด๋ำต๋ำถ๋ำท๋ำ",
    "ธ๋ำน๋ำบ๋ำป๋ำผ๋ำฝ๋ำพ๋ำฟ๋ำภ๋ำม๋ำย๋ำร๋ำฤ๋ำล๋ำฦ๋ำว๋ำศ๋ำษ๋ำส๋ำห๋ำฬ๋ำอ๋ำฮ๋ำ",
    "กิ่ขิ่ฃิ่คิ่ฅิ่ฆิ่งิ่จิ่ฉิ่ชิ่ซิ่ฌิ่ญิ่ฎิ่ฏิ่ฐิ่ฑิ่ฒิ่ณิ่ดิ่ติ่ถิ่ทิ่ธิ่นิ่บิ่ปิ่ผิ่ฝิ่พิ่ฟิ่ภิ่มิ่ยิ่ริ่ฤิ่ลิ่ฦิ่วิ่ศิ่ษิ่สิ่หิ่ฬิ่อิ่ฮิ่",
    "กี่ขี่ฃี่คี่ฅี่ฆี่งี่จี่ฉี่ชี่ซี่ฌี่ญี่ฎี่ฏี่ฐี่ฑี่ฒี่ณี่ดี่ตี่ถี่ที่ธี่นี่บี่ปี่ผี่ฝี่พี่ฟี่ภี่มี่ยี่รี่ฤี่ลี่ฦี่วี่ศี่ษี่สี่หี่ฬี่อี่ฮี่",
    "กึ่ขึ่ฃึ่คึ่ฅึ่ฆึ่งึ่จึ่ฉึ่ชึ่ซึ่ฌึ่ญึ่ฎึ่ฏึ่ฐึ่ฑึ่ฒึ่ณึ่ดึ่ตึ่ถึ่ทึ่ธึ่นึ่บึ่ปึ่ผึ่ฝึ่พึ่ฟึ่ภึ่มึ่ยึ่รึ่ฤึ่ลึ่ฦึ่วึ่ศึ่ษึ่สึ่หึ่ฬึ่อึ่ฮึ่",
    "กื่ขื่ฃื่คื่ฅื่ฆื่งื่จื่ฉื่ชื่ซื่ฌื่ญื่ฎื่ฏื่ฐื่ฑื่ฒื่ณื่ดื่ตื่ถื่ทื่ธื่นื่บื่ปื่ผื่ฝื่พื่ฟื่ภื่มื่ยื่รื่ฤื่ลื่ฦื่วื่ศื่ษื่สื่หื่ฬื่อื่ฮื่",
    "กิ้ขิ้ฃิ้คิ้ฅิ้ฆิ้งิ้จิ้ฉิ้ชิ้ซิ้ฌิ้ญิ้ฎิ้ฏิ้ฐิ้ฑิ้ฒิ้ณิ้ดิ้ติ้ถิ้ทิ้ธิ้นิ้บิ้ปิ้ผิ้ฝิ้พิ้ฟิ้ภิ้มิ้ยิ้ริ้ฤิ้ลิ้ฦิ้วิ้ศิ้ษิ้สิ้หิ้ฬิ้อิ้ฮิ้",
    "กี้ขี้ฃี้คี้ฅี้ฆี้งี้จี้ฉี้ชี้ซี้ฌี้ญี้ฎี้ฏี้ฐี้ฑี้ฒี้ณี้ดี้ตี้ถี้ที้ธี้นี้บี้ปี้ผี้ฝี้พี้ฟี้ภี้มี้ยี้รี้ฤี้ลี้ฦี้วี้ศี้ษี้สี้หี้ฬี้อี้ฮี้",
    "กึ้ขึ้ฃึ้คึ้ฅึ้ฆึ้งึ้จึ้ฉึ้ชึ้ซึ้ฌึ้ญึ้ฎึ้ฏึ้ฐึ้ฑึ้ฒึ้ณึ้ดึ้ตึ้ถึ้ทึ้ธึ้นึ้บึ้ปึ้ผึ้ฝึ้พึ้ฟึ้ภึ้มึ้ยึ้รึ้ฤึ้ลึ้ฦึ้วึ้ศึ้ษึ้สึ้หึ้ฬึ้อึ้ฮึ้",
    "กื้ขื้ฃื้คื้ฅื้ฆื้งื้จื้ฉื้ชื้ซื้ฌื้ญื้ฎื้ฏื้ฐื้ฑื้ฒื้ณื้ดื้ตื้ถื้ทื้ธื้นื้บื้ปื้ผื้ฝื้พื้ฟื้ภื้มื้ยื้รื้ฤื้ลื้ฦื้วื้ศื้ษื้สื้หื้ฬื้อื้ฮื้",
    "กิ๊ขิ๊ฃิ๊คิ๊ฅิ๊ฆิ๊งิ๊จิ๊ฉิ๊ชิ๊ซิ๊ฌิ๊ญิ๊ฎิ๊ฏิ๊ฐิ๊ฑิ๊ฒิ๊ณิ๊ดิ๊ติ๊ถิ๊ทิ๊ธิ๊นิ๊บิ๊ปิ๊ผิ๊ฝิ๊พิ๊ฟิ๊ภิ๊มิ๊ยิ๊ริ๊ฤิ๊ลิ๊ฦิ๊วิ๊ศิ๊ษิ๊สิ๊หิ๊ฬิ๊อิ๊ฮิ๊",
    "กี๊ขี๊ฃี๊คี๊ฅี๊ฆี๊งี๊จี๊ฉี๊ชี๊ซี๊ฌี๊ญี๊ฎี๊ฏี๊ฐี๊ฑี๊ฒี๊ณี๊ดี๊ตี๊ถี๊ที๊ธี๊นี๊บี๊ปี๊ผี๊ฝี๊พี๊ฟี๊ภี๊มี๊ยี๊รี๊ฤี๊ลี๊ฦี๊วี๊ศี๊ษี๊สี๊หี๊ฬี๊อี๊ฮี๊",
    "กึ๊ขึ๊ฃึ๊คึ๊ฅึ๊ฆึ๊งึ๊จึ๊ฉึ๊ชึ๊ซึ๊ฌึ๊ญึ๊ฎึ๊ฏึ๊ฐึ๊ฑึ๊ฒึ๊ณึ๊ดึ๊ตึ๊ถึ๊ทึ๊ธึ๊นึ๊บึ๊ปึ๊ผึ๊ฝึ๊พึ๊ฟึ๊ภึ๊มึ๊ยึ๊รึ๊ฤึ๊ลึ๊ฦึ๊วึ๊ศึ๊ษึ๊สึ๊หึ๊ฬึ๊อึ๊ฮึ๊",
    "กื๊ขื๊ฃื๊คื๊ฅื๊ฆื๊งื๊จื๊ฉื๊ชื๊ซื๊ฌื๊ญื๊ฎื๊ฏื๊ฐื๊ฑื๊ฒื๊ณื๊ดื๊ตื๊ถื๊ทื๊ธื๊นื๊บื๊ปื๊ผื๊ฝื๊พื๊ฟื๊ภื๊มื๊ยื๊รื๊ฤื๊ลื๊ฦื๊วื๊ศื๊ษื๊สื๊หื๊ฬื๊อื๊ฮื๊",
    "กิ๋ขิ๋ฃิ๋คิ๋ฅิ๋ฆิ๋งิ๋จิ๋ฉิ๋ชิ๋ซิ๋ฌิ๋ญิ๋ฎิ๋ฏิ๋ฐิ๋ฑิ๋ฒิ๋ณิ๋ดิ๋ติ๋ถิ๋ทิ๋ธิ๋นิ๋บิ๋ปิ๋ผิ๋ฝิ๋พิ๋ฟิ๋ภิ๋มิ๋ยิ๋ริ๋ฤิ๋ลิ๋ฦิ๋วิ๋ศิ๋ษิ๋สิ๋หิ๋ฬิ๋อิ๋ฮิ๋",
    "กี๋ขี๋ฃี๋คี๋ฅี๋ฆี๋งี๋จี๋ฉี๋ชี๋ซี๋ฌี๋ญี๋ฎี๋ฏี๋ฐี๋ฑี๋ฒี๋ณี๋ดี๋ตี๋ถี๋ที๋ธี๋นี๋บี๋ปี๋ผี๋ฝี๋พี๋ฟี๋ภี๋มี๋ยี๋รี๋ฤี๋ลี๋ฦี๋วี๋ศี๋ษี๋สี๋หี๋ฬี๋อี๋ฮี๋",
    "กึ๋ขึ๋ฃึ๋คึ๋ฅึ๋ฆึ๋งึ๋จึ๋ฉึ๋ชึ๋ซึ๋ฌึ๋ญึ๋ฎึ๋ฏึ๋ฐึ๋ฑึ๋ฒึ๋ณึ๋ดึ๋ตึ๋ถึ๋ทึ๋ธึ๋นึ๋บึ๋ปึ๋ผึ๋ฝึ๋พึ๋ฟึ๋ภึ๋มึ๋ยึ๋รึ๋ฤึ๋ลึ๋ฦึ๋วึ๋ศึ๋ษึ๋สึ๋หึ๋ฬึ๋อึ๋ฮึ๋",
    "กื๋ขื๋ฃื๋คื๋ฅื๋ฆื๋งื๋จื๋ฉื๋ชื๋ซื๋ฌื๋ญื๋ฎื๋ฏื๋ฐื๋ฑื๋ฒื๋ณื๋ดื๋ตื๋ถื๋ทื๋ธื๋นื๋บื๋ปื๋ผื๋ฝื๋พื๋ฟื๋ภื๋มื๋ยื๋รื๋ฤื๋ลื๋ฦื๋วื๋ศื๋ษื๋สื๋หื๋ฬื๋อื๋ฮื๋",
    "กุขุฃุคุฅุฆุงุจุฉุชุซุฌุญุฎุฏุฐุฑุฒุณุดุตุถุทุธุนุบุปุผุฝุพุฟุภุมุยุรุลุวุศุษุสุหุฬุอุฮุ",
    "กูขูฃูคูฅูฆูงูจูฉูชูซูฌูญูฎูฏูฐูฑูฒูณูดูตูถูทูธูนูบูปูผูฝูพูฟูภูมูยูรูลูวูศูษูสูหูฬูอูฮู",
    "กฺขฺฃฺคฺฅฺฆฺงฺจฺฉฺชฺซฺฌฺญฺฎฺฏฺฐฺฑฺฒฺณฺดฺตฺถฺทฺธฺนฺบฺปฺผฺฝฺพฺฟฺภฺมฺยฺรฺลฺวฺศฺษฺสฺหฺฬฺอฺฮฺ",
    "กุ่ขุ่ฃุ่คุ่ฅุ่ฆุ่งุ่จุ่ฉุ่ชุ่ซุ่ฌุ่ญุ่ฎุ่ฏุ่ฐุ่ฑุ่ฒุ่ณุ่ดุ่ตุ่ถุ่ทุ่ธุ่นุ่บุ่ปุ่ผุ่ฝุ่พุ่ฟุ่ภุ่มุ่ยุ่รุ่ลุ่วุ่ศุ่ษุ่สุ่หุ่ฬุ่อุ่ฮุ่",
    "กุ้ขุ้ฃุ้คุ้ฅุ้ฆุ้งุ้จุ้ฉุ้ชุ้ซุ้ฌุ้ญุ้ฎุ้ฏุ้ฐุ้ฑุ้ฒุ้ณุ้ดุ้ตุ้ถุ้ทุ้ธุ้นุ้บุ้ปุ้ผุ้ฝุ้พุ้ฟุ้ภุ้มุ้ยุ้รุ้ลุ้วุ้ศุ้ษุ้สุ้หุ้ฬุ้อุ้ฮุ้",
    "กุ๊ขุ๊ฃุ๊คุ๊ฅุ๊ฆุ๊งุ๊จุ๊ฉุ๊ชุ๊ซุ๊ฌุ๊ญุ๊ฎุ๊ฏุ๊ฐุ๊ฑุ๊ฒุ๊ณุ๊ดุ๊ตุ๊ถุ๊ทุ๊ธุ๊นุ๊บุ๊ปุ๊ผุ๊ฝุ๊พุ๊ฟุ๊ภุ๊มุ๊ยุ๊รุ๊ลุ๊วุ๊ศุ๊ษ๊ส๊ห๊ฬ๊อ๊ฮ๊",
    "กุ๋ขุ๋ฃุ๋คุ๋ฅุ๋ฆุ๋งุ๋จุ๋ฉุ๋ชุ๋ซุ๋ฌุ๋ญุ๋ฎุ๋ฏุ๋ฐุ๋ฑุ๋ฒุ๋ณุ๋ดุ๋ตุ๋ถุ๋ทุ๋ธุ๋นุ๋บุ๋ปุ๋ผุ๋ฝุ๋พุ๋ฟุ๋ภุ๋มุ๋ยุ๋รุ๋ลุ๋วุ๋ศุ๋ษุ๋สุ๋หุ๋ฬุ๋อุ๋ฮุ๋",
    "กู่ขู่ฃู่คู่ฅู่ฆู่งู่จู่ฉู่ชู่ซู่ฌู่ญู่ฎู่ฏู่ฐู่ฑู่ฒู่ณู่ดู่ตู่ถู่ทู่ธู่นู่บู่ปู่ผู่ฝู่พู่ฟู่ภู่มู่ยู่รู่ลู่วู่ศู่ษู่สู่หู่ฬู่อู่ฮู่",
    "กู้ขู้ฃู้คู้ฅู้ฆู้งู้จู้ฉู้ชู้ซู้ฌู้ญู้ฎู้ฏู้ฐู้ฑู้ฒู้ณู้ดู้ตู้ถู้ทู้ธู้นู้บู้ปู้ผู้ฝู้พู้ฟู้ภู้มู้ยู้รู้ลูู้้วู้ศู้ษู้สู้หู้ฬู้อู้ฮู้",
    "กู๊ขู๊ฃู๊คู๊ฅู๊ฆู๊งู๊จู๊ฉู๊ชู๊ซู๊ฌู๊ญู๊ฎู๊ฏู๊ฐู๊ฑู๊ฒู๊ณู๊ดู๊ตู๊ถู๊ทู๊ธู๊นู๊บู๊ปู๊ผู๊ฝู๊พู๊ฟู๊ภู๊มู๊ยู๊รู๊ลู๊วู๊ศู๊ษู๊สู๊หู๊ฬู๊อู๊ฮู๊",
    "กู๋ขู๋ฃู๋คู๋ฅู๋ฆู๋งู๋จู๋ฉู๋ชู๋ซู๋ฌู๋ญู๋ฎู๋ฏู๋ฐู๋ฑู๋ฒู๋ณู๋ดู๋ตู๋ถู๋ทู๋ธู๋นู๋บู๋ปู๋ผู๋ฝู๋พู๋ฟู๋ภู๋มู๋ยู๋รู๋ลู๋วู๋ศู๋ษู๋สู๋หู๋ฬู๋อู๋ฮู๋",
    "กฺ่ขฺ่ฃฺ่คฺ่ฅฺ่ฆฺ่งฺ่จฺ่ฉฺ่ชฺ่ซฺ่ฌฺ่ญฺ่ฎฺ่ฏฺ่ฐฺ่ฑฺ่ฒฺ่ณฺ่ดฺ่ตฺ่ถฺ่ทฺ่ธฺ่นฺ่บฺ่ปฺ่ผฺ่ฝฺ่พฺ่ฟฺ่ภฺ่มฺ่ยฺ่รฺ่ลฺ่วฺ่ศฺ่ษฺ่สฺ่หฺ่ฬฺ่อฺ่ฮฺ่",
    "กฺ้ขฺ้ฃฺ้คฺ้ฅฺ้ฆฺ้งฺ้จฺ้ฉฺ้ชฺ้ซฺ้ฌฺ้ญฺ้ฎฺ้ฏฺ้ฐฺ้ฑฺ้ฒฺ้ณฺ้ดฺ้ตฺ้ถฺ้ทฺ้ธฺ้นฺ้บฺ้ปฺ้ผฺ้ฝฺ้พฺ้ฟฺ้ภฺ้มฺ้ยฺ้รฺ้ลฺ้วฺ้ศฺ้ษฺ้สฺ้หฺ้ฬฺ้อฺ้ฮฺ้",
    "กฺ๊ขฺ๊ฃฺ๊คฺ๊ฅฺ๊ฆฺ๊งฺ๊จฺ๊ฉฺ๊ชฺ๊ซฺ๊ฌฺ๊ญฺ๊ฎฺ๊ฏฺ๊ฐฺ๊ฑฺ๊ฒฺ๊ณฺ๊ดฺ๊ตฺ๊ถฺ๊ทฺ๊ธฺ๊นฺ๊บฺ๊ปฺ๊ผฺ๊ฝฺ๊พฺ๊ฟฺ๊ภฺ๊มฺ๊ยฺ๊รฺ๊ลฺ๊วฺ๊ศฺ๊ษฺ๊สฺ๊หฺ๊ฬฺ๊อฺ๊ฮฺ๊",
    "กฺ๋ขฺ๋ฃฺ๋คฺ๋ฅฺ๋ฆฺ๋งฺ๋จฺ๋ฉฺ๋ชฺ๋ซฺ๋ฌฺ๋ญฺ๋ฎฺ๋ฏฺ๋ฐฺ๋ฑฺ๋ฒฺ๋ณฺ๋ดฺ๋ตฺ๋ถฺ๋ทฺ๋ธฺ๋นฺ๋บฺ๋ปฺ๋ผฺ๋ฝฺ๋พฺ๋ฟฺ๋ภฺ๋มฺ๋ยฺ๋รฺ๋ลฺ๋วฺ๋ศฺ๋ษฺ๋สฺ๋หฺ๋ฬฺ๋อฺ๋ฮฺ๋",
]
