from pathlib import Path

import ufoLib2

BASES = "ka-khmer kha-khmer ko-khmer kho-khmer ngo-khmer ca-khmer cha-khmer co-khmer cho-khmer nyo-khmer da-khmer ttha-khmer do-khmer ttho-khmer nno-khmer ta-khmer tha-khmer to-khmer tho-khmer no-khmer ba-khmer pha-khmer po-khmer pho-khmer mo-khmer yo-khmer ro-khmer lo-khmer vo-khmer sha-khmer sso-khmer sa-khmer ha-khmer la-khmer qa-khmer nyo-khmer.less kho-khmer.post cho-khmer.post ttho-khmer.post ba-khmer.post yo-khmer.post sa-khmer.post kho-khmer.post2 cho-khmer.post2 ttho-khmer.post2 ba-khmer.post2 yo-khmer.post2 dottedCircle pathamasat-khmer muoykoet-khmer piikoet-khmer beikoet-khmer buonkoet-khmer pramkoet-khmer pramMuoykoet-khmer pramPiikoet-khmer pramBeikoet-khmer pramBuonkoet-khmer dapkoet-khmer dapMuoykoet-khmer dapPiikoet-khmer dapBeikoet-khmer dapBuonkoet-khmer dapPramkoet-khmer tuteyasat-khmer muoyroc-khmer piiroc-khmer beiroc-khmer buonroc-khmer pramroc-khmer pramMuoyroc-khmer pramPiiroc-khmer pramBeiroc-khmer pramBuonroc-khmer daproc-khmer dapMuoyroc-khmer dapPiiroc-khmer dapBeiroc-khmer dapBuonroc-khmer dapPramroc-khmer ka_aaSign-khmer kha_aaSign-khmer ko_aaSign-khmer kho_aaSign-khmer ngo_aaSign-khmer ca_aaSign-khmer cha_aaSign-khmer co_aaSign-khmer cho_aaSign-khmer nyo_aaSign-khmer da_aaSign-khmer ttha_aaSign-khmer do_aaSign-khmer ttho_aaSign-khmer nno_aaSign-khmer ta_aaSign-khmer tha_aaSign-khmer to_aaSign-khmer tho_aaSign-khmer no_aaSign-khmer ba_aaSign-khmer pha_aaSign-khmer po_aaSign-khmer pho_aaSign-khmer mo_aaSign-khmer yo_aaSign-khmer ro_aaSign-khmer lo_aaSign-khmer vo_aaSign-khmer sha_aaSign-khmer sso_aaSign-khmer sso_aaSign-khmer.post_ sa_aaSign-khmer ha_aaSign-khmer la_aaSign-khmer qa_aaSign-khmer nyo_aaSign-khmer.less ka_auSign-khmer kha_auSign-khmer ko_auSign-khmer kho_auSign-khmer ngo_auSign-khmer ca_auSign-khmer cha_auSign-khmer co_auSign-khmer cho_auSign-khmer nyo_auSign-khmer da_auSign-khmer ttha_auSign-khmer do_auSign-khmer ttho_auSign-khmer nno_auSign-khmer ta_auSign-khmer tha_auSign-khmer to_auSign-khmer tho_auSign-khmer no_auSign-khmer ba_auSign-khmer pha_auSign-khmer po_auSign-khmer pho_auSign-khmer mo_auSign-khmer yo_auSign-khmer ro_auSign-khmer lo_auSign-khmer vo_auSign-khmer sha_auSign-khmer sso_auSign-khmer sso_auSign-khmer.post_ sa_auSign-khmer ha_auSign-khmer la_auSign-khmer qa_auSign-khmer nyo_auSign-khmer.less kho_aaSign-khmer.post_ cho_aaSign-khmer.post_ ttho_aaSign-khmer.post_ ba_aaSign-khmer.post_ yo_aaSign-khmer.post_ sa_aaSign-khmer.post_ kho_auSign-khmer.post_ cho_auSign-khmer.post_ ttho_auSign-khmer.post_ ba_auSign-khmer.post_ yo_auSign-khmer.post_ sa_auSign-khmer.post_ kho_aaSign-khmer.post2_ cho_aaSign-khmer.post2_ ttho_aaSign-khmer.post2_ ba_aaSign-khmer.post2_ yo_aaSign-khmer.post2_ kho_auSign-khmer.post2_ cho_auSign-khmer.post2_ ttho_auSign-khmer.post2_ ba_auSign-khmer.post2_ yo_auSign-khmer.post2_ sso-khmer.post".split()
MARKS = "ka-khmer.below kha-khmer.below ko-khmer.below ngo-khmer.below ca-khmer.below cha-khmer.below co-khmer.below nyo-khmer.below nyo-khmer.full.below da-khmer.below ttha-khmer.below do-khmer.below nno-khmer.below ta-khmer.below tha-khmer.below to-khmer.below tho-khmer.below no-khmer.below pha-khmer.below po-khmer.below pho-khmer.below mo-khmer.below lo-khmer.below vo-khmer.below sha-khmer.below ha-khmer.below qa-khmer.below qi-khmer.below qu-khmer.below quu-khmer.below ry-khmer.below ly-khmer.below qe-khmer.below qoo-khmer.below ka-khmer.below2 kha-khmer.below2 ko-khmer.below2 ngo-khmer.below2 ca-khmer.below2 cha-khmer.below2 co-khmer.below2 nyo-khmer.below2 da-khmer.below2 ttha-khmer.below2 do-khmer.below2 nno-khmer.below2 ta-khmer.below2 tha-khmer.below2 to-khmer.below2 tho-khmer.below2 no-khmer.below2 pha-khmer.below2 po-khmer.below2 pho-khmer.below2 mo-khmer.below2 lo-khmer.below2 vo-khmer.below2 sha-khmer.below2 ha-khmer.below2 qa-khmer.below2 iMark-khmer iiMark-khmer yMark-khmer yyMark-khmer iMark_toandakhiat-khmer iMark-khmer.narrow iiMark-khmer.narrow yMark-khmer.narrow yyMark-khmer.narrow iMark_toandakhiat-khmer.narrow uMark-khmer uuMark-khmer uaMark-khmer uMark-khmer.below2 uuMark-khmer.below2 uaMark-khmer.below2 nikahit-khmer muusikatoan-khmer triisap-khmer bantoc-khmer robat-khmer toandakhiat-khmer kakabat-khmer ahsda-khmer samyoksannya-khmer viriam-khmer coeng-khmer bathamasat-khmer atthacan-khmer ahsda-khmer.narrow toandakhiat-khmer.narrow samyoksannya-khmer.narrow nyo-khmer.full.below.narrow nno-khmer.below.narrow1 nno-khmer.below.narrow2 da-khmer.below.ro ta-khmer.below.ro po-khmer.below.ro pho-khmer.below.ro mo-khmer.below.ro uuMark-khmer.ro uaMark-khmer.ro muusikatoan-khmer.ro muusikatoan-khmer.roLiga nikahit-khmer.small kakabat-khmer.small samyoksannya-khmer.small".split()

for p in [
    *Path("source/GoogleSans/staging/u").glob("*.ufo"),
    *Path("source/GoogleSans/staging/i").glob("*.ufo"),
]:
    print(p.name)

    u = ufoLib2.Font.open(p)
    u.lib["public.openTypeCategories"].update({k: "base" for k in BASES})
    u.lib["public.openTypeCategories"].update({k: "mark" for k in MARKS})
    u.save()
