name: 'CI/CD'

on:
  # Run on pushes to the repository's own branches only when one of the
  # conditions below matches. Typically, new things should be added via PRs.
  push:  
    # Sequence of patterns matched against refs/heads:
    branches:
      - main # Push events directly to the main branch
      # The following two directives are for making "build" branches where all
      # jobs should be run. Note: it's best not to open PRs for these branches
      # to avoid jobs running twice (one for the push event, the other for the
      # pull_request).
      - "build/**" # Push events to branches matching refs/heads/build/[ANYTHING]
      - "build-*" # Push events to branches matching refs/heads/build-[ANYTHING]
    tags:
      - "v*" # Push events to matching v*, i.e. v9.000 and v10.001rc1
  # Run on all PRs. Runs a limited set of jobs by default to save time.
  pull_request:

jobs:
  lint-sources:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Lint UFO sources
        run: |
          pip install ufolint
          ufolint source/GoogleSans/*.ufo

  lint-scripts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Lint scripts
        run: |
          pip install flake8
          flake8

  build-variable:
    runs-on: googlefonts-64cores-256GB
    timeout-minutes: 10
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Build variable fonts
        run: |
          make setup
          . .venv/bin/activate && make -j gs-vf
      - uses: actions/upload-artifact@v4
        with:
          name: variable-fonts
          path: |
            build/GoogleSans/variable
            build/GoogleSans/.intermediate

  check-variable:
    needs:
      - build-variable
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - uses: actions/download-artifact@v4
        with:
          name: variable-fonts
          path: 'build/GoogleSans'
      - name: Font Bakery GS profile tests
        uses: f-actions/font-bakery@v3
        with:
          version: 'latest'
          subcmd: 'check-profile'
          args: '--auto-jobs -C --loglevel WARN qa/check-googlesans.py'
          path: 'build/GoogleSans/variable/*.ttf'
      - name: Font Bakery character set profile tests
        uses: f-actions/font-bakery@v3
        with:
          version: 'latest'
          subcmd: 'check-profile'
          args: '--auto-jobs -C --loglevel WARN qa/check-charset.py'
          path: 'build/GoogleSans/variable/*.ttf'
      - name: Font Bakery feature tag and shaping tests
        uses: f-actions/font-bakery@v3
        with:
          version: 'latest'
          subcmd: 'check-profile'
          args: '--auto-jobs -C --loglevel WARN qa/check-fea.py'
          path: 'build/GoogleSans/variable/*.ttf'
      - name: OpenType Sanitizer checks
        uses: f-actions/opentype-sanitizer@v2
        with:
          path: 'build/GoogleSans/variable/*.ttf'
      - name: File size analysis
        run: |
          pip install --upgrade font-size
          font-size build/GoogleSans/variable/*.ttf

  build-statics:
    # Skip running in PRs to save time and resources. Create a "build-*" branch
    # to build all outside a release.
    if: github.event_name != 'pull_request'
    needs:
      - build-variable
    runs-on: googlefonts-64cores-256GB
    timeout-minutes: 10
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - uses: actions/download-artifact@v4
        with:
          name: variable-fonts
          path: 'build/GoogleSans'
      - name: Build static fonts
        run: |
          make setup
          . .venv/bin/activate && make -j gs-static
      - uses: actions/upload-artifact@v4
        with:
          name: static-fonts
          path: 'build/GoogleSans/static'

  check-statics:
    needs:
      - build-statics
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - uses: actions/download-artifact@v4
        with:
          name: static-fonts
          path: 'build/GoogleSans/static'
      - name: Font Bakery GS profile tests
        uses: f-actions/font-bakery@v3
        with:
          version: 'latest'
          subcmd: 'check-profile'
          args: '--auto-jobs -C --loglevel WARN qa/check-googlesans.py'
          path: 'build/GoogleSans/static/*.ttf'
      - name: Font Bakery character set profile tests
        uses: f-actions/font-bakery@v3
        with:
          version: 'latest'
          subcmd: 'check-profile'
          args: '--auto-jobs -C --loglevel WARN qa/check-charset.py'
          path: 'build/GoogleSans/static/*.ttf'
      - name: Font Bakery feature tag and shaping tests
        uses: f-actions/font-bakery@v3
        with:
          version: 'latest'
          subcmd: 'check-profile'
          args: '--auto-jobs -C --loglevel WARN qa/check-fea.py'
          path: 'build/GoogleSans/static/*.ttf'
      - name: OpenType Sanitizer checks
        uses: f-actions/opentype-sanitizer@v2
        with:
          path: 'build/GoogleSans/static/*.ttf'
      - name: File size analysis
        run: |
          pip install --upgrade font-size
          font-size build/GoogleSans/static/*.ttf

  build-interpolatables:
    # Skip running in PRs to save time and resources. Create a "build-*" branch
    # to build all outside a release.
    if: github.event_name != 'pull_request'
    runs-on: googlefonts-64cores-256GB
    timeout-minutes: 10
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Build interpolatable fonts
        run: |
          make setup
          . .venv/bin/activate && make -j gs-compatible-masters
      - uses: actions/upload-artifact@v4
        with:
          name: interpolatable-fonts
          path: 'build/GoogleSans/interpolatable'

  release:
    # only run if the commit is tagged...
    if: startsWith(github.ref, 'refs/tags/v')
    # ... and both the lint and test jobs completed successfully
    needs:
      - build-variable
      - check-variable
      - build-statics
      - check-statics
      - build-interpolatables
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Permission is required for releasing
    permissions:
      contents: write
    steps:
      - name: Set env variables
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      # TODO: no `name` means download all artifacts, but put them into own dir?
      - uses: actions/download-artifact@v4
        with:
          name: variable-fonts
          path: 'build/GoogleSans'
      - uses: actions/download-artifact@v4
        with:
          name: static-fonts
          path: 'build/GoogleSans/static'
      - uses: actions/download-artifact@v4
        with:
          name: interpolatable-fonts
          path: 'build/GoogleSans/interpolatable'
      - name: Delete intermediate VFs
        run: rm -rf build/GoogleSans/.intermediate
      - name: Create build artifact zip archive
        run: zip GoogleSans-${{ steps.vars.outputs.tag }}.zip -r build/GoogleSans
      - name: Create Google Sans release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Google Sans ${{ github.ref }}
          body: |
            Please see the root of the repository for the CHANGELOG.md
          draft: true  # Create a draft release for final review.
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./GoogleSans-${{ steps.vars.outputs.tag }}.zip
          asset_name: GoogleSans-${{ steps.vars.outputs.tag }}.zip
          asset_content_type: application/zip
