name: 'CI/CD'

on:
  # Run on pushes to the repository's own branches only when one of the
  # conditions below matches. Typically, new things should be added via PRs.
  push:  
    # Sequence of patterns matched against refs/heads:
    branches:
      - main # Push events directly to the main branch
      # The following two directives are for making "build" branches where all
      # jobs should be run. Note: it's best not to open PRs for these branches
      # to avoid jobs running twice (one for the push event, the other for the
      # pull_request).
      - "build/**" # Push events to branches matching refs/heads/build/[ANYTHING]
      - "build-*" # Push events to branches matching refs/heads/build-[ANYTHING]
  release:
    # A release, pre-release, or draft of a release was published
    types: [published]
  # Run on all PRs. Runs a limited set of jobs by default to save time.
  pull_request:

jobs:
  lint-sources:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Lint UFO sources
        run: |
          pip install ufolint
          ufolint source/GoogleSans/*.ufo

  lint-scripts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Lint scripts
        run: |
          pip install flake8
          flake8

  build-variable:
    runs-on: googlefonts-64cores-256GB
    timeout-minutes: 15
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Build variable fonts
        run: |
          make setup
          . .venv/bin/activate && make -j gs-vf
      - uses: actions/upload-artifact@v7
        with:
          name: variable-fonts
          path: |
            build/GoogleSans/variable
            build/GoogleSans/.intermediate
          include-hidden-files: true

  check-variable:
    needs:
      - build-variable
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
      - name: Setup fontspector
        uses: fonttools/setup-fontspector@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v8
        with:
          name: variable-fonts
          path: 'build/GoogleSans'
      - name: Fontspector tests
        run: make test-vf
      - name: OpenType Sanitizer checks
        uses: f-actions/opentype-sanitizer@v4.0.0
        with:
          path: 'build/GoogleSans/variable/*.ttf'
      - name: File size analysis
        run: |
          pip install --upgrade font-size
          font-size build/GoogleSans/variable/*.ttf

  build-statics:
    # Skip running in PRs to save time and resources. Create a "build-*" branch
    # to build all outside a release.
    if: github.event_name != 'pull_request'
    needs:
      - build-variable
    runs-on: googlefonts-64cores-256GB
    timeout-minutes: 10
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - uses: actions/download-artifact@v8
        with:
          name: variable-fonts
          path: 'build/GoogleSans'
      - name: Build static fonts
        run: |
          make setup
          . .venv/bin/activate && make -j gs-static
      - uses: actions/upload-artifact@v7
        with:
          name: static-fonts
          path: 'build/GoogleSans/static'

  check-statics:
    needs:
      - build-statics
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
      - name: Setup fontspector
        uses: fonttools/setup-fontspector@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v8
        with:
          name: static-fonts
          path: 'build/GoogleSans/static'
      - name: Fontspector tests
        run: make test-static
      - name: OpenType Sanitizer checks
        uses: f-actions/opentype-sanitizer@v4.0.0
        with:
          path: 'build/GoogleSans/static/*.ttf'
      - name: File size analysis
        run: |
          pip install --upgrade font-size
          font-size build/GoogleSans/static/*.ttf

  build-interpolatables:
    # Skip running in PRs to save time and resources. Create a "build-*" branch
    # to build all outside a release.
    if: github.event_name != 'pull_request'
    runs-on: googlefonts-64cores-256GB
    timeout-minutes: 10
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Build interpolatable fonts
        run: |
          make setup
          . .venv/bin/activate && make -j gs-compatible-masters
      - uses: actions/upload-artifact@v7
        with:
          name: interpolatable-fonts
          path: 'build/GoogleSans/interpolatable'

  build-android:
    # Skip running in PRs to save time and resources. Create a "build-*" branch
    # to build all outside a release.
    if: github.event_name != 'pull_request'
    needs:
      - build-variable
    runs-on: googlefonts-64cores-256GB
    timeout-minutes: 10
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
      - uses: actions/download-artifact@v8
        with:
          name: variable-fonts
          path: 'build/GoogleSans'
      - name: Build Android fonts
        run: |
          make setup
          . .venv/bin/activate && make -j gs-android

  build-and-check-figma:
    # Skip running in PRs to save time and resources. Create a 'build-*' branch
    # to build all outside a release.
    if: github.event_name != 'pull_request'
    needs:
      - build-variable
    runs-on: googlefonts-64cores-256GB
    timeout-minutes: 15
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Set up Python v3.12 environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
      - name: Setup fontspector
        uses: fonttools/setup-fontspector@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v8
        with:
          name: variable-fonts
          path: 'build/GoogleSans'
      - name: Build Figma fonts
        run: |
          make setup
          . .venv/bin/activate && make -j gs-figma
      - name: Fontspector tests
        run: make test-figma
      - uses: actions/upload-artifact@v7
        with:
          name: figma-fonts
          path: 'build/GoogleSans/figma'

  release:
    if: ${{ github.event_name == 'release' }}
    needs:
      - build-variable
      - check-variable
      - build-statics
      - check-statics
      - build-interpolatables
      - build-android
      - build-and-check-figma
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Permission is required for releasing
    permissions:
      contents: write
    steps:
      - name: Save tag name
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Download variable fonts
        uses: actions/download-artifact@v8
        with:
          name: variable-fonts
          path: 'build/GoogleSans'
      - name: Download static fonts
        uses: actions/download-artifact@v8
        with:
          name: static-fonts
          path: 'build/GoogleSans/static'
      - name: Download interpolatable fonts
        uses: actions/download-artifact@v8
        with:
          name: interpolatable-fonts
          path: 'build/GoogleSans/interpolatable'
      - name: Download Android fonts
        uses: actions/download-artifact@v8
        with:
          name: android-fonts
          path: 'build/GoogleSans/android'
      - name: Download Figma fonts
        uses: actions/download-artifact@v8
        with:
          name: figma-fonts
          path: 'build/GoogleSans/figma'
      - name: Delete intermediate VFs
        run: rm -rf build/GoogleSans/.intermediate
      - name: Create build artifact zip archive
        id: release-archives
        run: |
          zip_name="GoogleSans-${{ steps.vars.outputs.tag }}.zip"
          echo "zip-name=$zip_name" >> "$GITHUB_OUTPUT"
          zip -9 "$zip_name" -r build/GoogleSans
      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ steps.release-archives.outputs.zip-name }}
          overwrite: true
