name: Script + Writing System Coverage

on:
  push:
    branches:
      - main # Push events on main branch
      - cldr-coverage # Push events on a cldr-coverage branch

jobs:
  cldr-coverage-support:
    runs-on: googlefonts-64cores-256GB
    timeout-minutes: 30
    name: PyICU Script and Writing System Coverage
    steps:
      - name: Check out the source repository
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: "pip"
          cache-dependency-path: "requirements*.txt"
      - name: Install Python build dependencies
        run: make setup
      - name: Build fonts
        run: .venv/bin/activate && make gs-vf-upright
      - name: CLDR script/language coverage
        uses: f-actions/cldr-coverage@master
        with:
          path: build/GoogleSans/variable/GoogleSans[GRAD,opsz,wght].ttf
