name: Script + Writing System Coverage

on:
  push:
    branches:
      - main # Push events on main branch
      - cldr-coverage # Push events on a cldr-coverage branch

jobs:
  cldr-coverage-support:
    runs-on: [linux, googlefonts-64cores-256GB]
    strategy:
      matrix:
        python-version: ["3.12"]
    name: PyICU Script and Writing System Coverage
    steps:
      - name: Configuration
        id: config
        uses: f-actions/font-setup@master
        with:
          projectname: "Google Sans"
          dependpath: "requirements.txt"
          py-version: ${{ matrix.python-version }}
          buildcommand: "make gs-vf"
      - name: Check out ${{ steps.config.outputs.projectname }} source repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.config.outputs.py-version }}
          cache: "pip"
          cache-dependency-path: "requirements*.txt"
      - name: Install Python build dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          update-wheel: "true"
          update-setuptools: "true"
      - name: Build fonts
        run: ${{ steps.config.outputs.buildcommand }}
      - name: CLDR script/language coverage
        uses: f-actions/cldr-coverage@master
        with:
          path: "/github/workspace/build/GoogleSans/variable/GoogleSans[GRAD,opsz,wght].ttf"
