name: UFO source lints

on: [push]

jobs:
  ufolint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    name: ufolint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python v${{ matrix.python-version }} environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: ufolint tests on UFO sources
        run: |
          pip install ufolint
          ufolint source/GoogleSans/*.ufo
