name: Artifact Uploads
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master # Push events on master branch
      - "build/**" # Push events to branches matching refs/heads/build/[ANYTHING]
      - "build-*" # Push events to branches matching refs/heads/build-[ANYTHING]

jobs:
  static-artifact-uploads:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    name: Upload static artifacts
    steps:
      - name: Configuration
        id: config
        uses: f-actions/font-setup@master
        with:
          projectname: "Google Sans"
          sourcepath: "src"
          buildpath: "build/GoogleSans/static" # static font dir
          dependpath: "requirements.txt"
          py-version: ${{ matrix.python-version }}
          buildcommand: "make gs-static" # static font make target
      - name: Check out ${{ steps.config.outputs.projectname }} source repository
        uses: actions/checkout@v2
      - name: Set up Python v${{ steps.config.outputs.py-version }} environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ steps.config.outputs.py-version }}
      - name: Python build dependency cache lookup
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          # Check for requirements file cache hit
          key: ${{ runner.os }}-pip-${{ hashFiles('${{ steps.config.outputs.dependpath }}') }}
      - name: Install Python build dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          update-wheel: "true"
          update-setuptools: "true"
      - name: Build fonts
        run: ${{ steps.config.outputs.buildcommand }}
      - name: Push static font artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GoogleSans-static
          path: ${{ steps.config.outputs.buildpath }}

  variable-artifact-uploads:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    name: Upload variable artifacts
    steps:
      - name: Configuration
        id: config
        uses: f-actions/font-setup@master
        with:
          projectname: "Google Sans"
          sourcepath: "src"
          buildpath: "build/GoogleSans/variable" # variable font dir
          dependpath: "requirements.txt"
          py-version: ${{ matrix.python-version }}
          buildcommand: "make gs-vf" # static font make target
      - name: Check out ${{ steps.config.outputs.projectname }} source repository
        uses: actions/checkout@v2
      - name: Set up Python v${{ steps.config.outputs.py-version }} environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ steps.config.outputs.py-version }}
      - name: Python build dependency cache lookup
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          # Check for requirements file cache hit
          key: ${{ runner.os }}-pip-${{ hashFiles('${{ steps.config.outputs.dependpath }}') }}
      - name: Install Python build dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          update-wheel: "true"
          update-setuptools: "true"
      - name: Build fonts
        run: ${{ steps.config.outputs.buildcommand }}
      - name: Push variable font artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GoogleSans-variable
          path: ${{ steps.config.outputs.buildpath }}
