name: Variable CI

on: [push]

jobs:
  variable-font-ci-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    name: Google Sans variable font build CI
    steps:
      - name: Configuration
        id: config
        uses: f-actions/font-setup@master
        with:
          projectname: "Google Sans"
          sourcepath: "source"
          buildpath: "build/GoogleSans/variable/expert/*.ttf" # variable font build path
          readmepath: "README.md"
          changelogpath: "CHANGELOG.md"
          dependpath: "requirements.txt"
          py-version: ${{ matrix.python-version }}
          buildcommand: "make gs-vf" # variable font make target
      - name: Check out ${{ steps.config.outputs.projectname }} source repository
        uses: actions/checkout@v2
      - name: Set up Python v${{ steps.config.outputs.py-version }} environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ steps.config.outputs.py-version }}
      - name: Python build dependency cache lookup
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          # Check for requirements file cache hit
          key: ${{ runner.os }}-pip-${{ hashFiles('${{ steps.config.outputs.dependpath }}') }}
      - name: Install Python build dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          update-wheel: "true"
          update-setuptools: "true"
      - name: Build fonts
        run: ${{ steps.config.outputs.buildcommand }}
      - name: Font Bakery GS profile tests (2-axis Expert)
        uses: f-actions/font-bakery@v1
        with:
          version: "latest"
          subcmd: "check-profile"
          args: "-C --loglevel WARN qa/check-googlesans.py"
          path: "${{ steps.config.outputs.buildpath }}"
      - name: Font Bakery character set profile tests (2-axis Expert)
        uses: f-actions/font-bakery@v1
        with:
          version: "latest"
          subcmd: "check-profile"
          args: "-C --loglevel WARN qa/check-charset.py"
          path: "${{ steps.config.outputs.buildpath }}"
      - name: Font Bakery feature tag tests (2-axis Expert)
        uses: f-actions/font-bakery@v1
        with:
          version: "latest"
          subcmd: "check-profile"
          args: "-C --loglevel WARN qa/check-fea.py"
          path: "${{ steps.config.outputs.buildpath }}"
      - name: Font Bakery GS profile tests (1-axis Expert)
        uses: f-actions/font-bakery@v1
        with:
          version: "latest"
          subcmd: "check-profile"
          args: "-C --loglevel WARN qa/check-googlesans.py"
          path: "build/GoogleSans/variable/expert/partial/*.ttf"
      - name: OpenType Sanitizer checks (2-axis Expert)
        uses: f-actions/opentype-sanitizer@v1
        with:
          path: "${{ steps.config.outputs.buildpath }}"
      - name: OpenType Sanitizer checks (1-axis Expert)
        uses: f-actions/opentype-sanitizer@v1
        with:
          path: "build/GoogleSans/variable/expert/partial/*.ttf"
